// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/upstreamdailystat"
	"github.com/Wei-Shaw/sub2api/ent/upstreamgroup"
	"github.com/Wei-Shaw/sub2api/ent/upstreamgroupmultiplierhistory"
	"github.com/Wei-Shaw/sub2api/ent/upstreamsite"
)

// UpstreamSiteUpdate is the builder for updating UpstreamSite entities.
type UpstreamSiteUpdate struct {
	config
	hooks    []Hook
	mutation *UpstreamSiteMutation
}

// Where appends a list predicates to the UpstreamSiteUpdate builder.
func (_u *UpstreamSiteUpdate) Where(ps ...predicate.UpstreamSite) *UpstreamSiteUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UpstreamSiteUpdate) SetUpdatedAt(v time.Time) *UpstreamSiteUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *UpstreamSiteUpdate) SetName(v string) *UpstreamSiteUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UpstreamSiteUpdate) SetNillableName(v *string) *UpstreamSiteUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetBaseURL sets the "base_url" field.
func (_u *UpstreamSiteUpdate) SetBaseURL(v string) *UpstreamSiteUpdate {
	_u.mutation.SetBaseURL(v)
	return _u
}

// SetNillableBaseURL sets the "base_url" field if the given value is not nil.
func (_u *UpstreamSiteUpdate) SetNillableBaseURL(v *string) *UpstreamSiteUpdate {
	if v != nil {
		_u.SetBaseURL(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *UpstreamSiteUpdate) SetPlatform(v upstreamsite.Platform) *UpstreamSiteUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *UpstreamSiteUpdate) SetNillablePlatform(v *upstreamsite.Platform) *UpstreamSiteUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetAuthMode sets the "auth_mode" field.
func (_u *UpstreamSiteUpdate) SetAuthMode(v upstreamsite.AuthMode) *UpstreamSiteUpdate {
	_u.mutation.SetAuthMode(v)
	return _u
}

// SetNillableAuthMode sets the "auth_mode" field if the given value is not nil.
func (_u *UpstreamSiteUpdate) SetNillableAuthMode(v *upstreamsite.AuthMode) *UpstreamSiteUpdate {
	if v != nil {
		_u.SetAuthMode(*v)
	}
	return _u
}

// SetAccount sets the "account" field.
func (_u *UpstreamSiteUpdate) SetAccount(v string) *UpstreamSiteUpdate {
	_u.mutation.SetAccount(v)
	return _u
}

// SetNillableAccount sets the "account" field if the given value is not nil.
func (_u *UpstreamSiteUpdate) SetNillableAccount(v *string) *UpstreamSiteUpdate {
	if v != nil {
		_u.SetAccount(*v)
	}
	return _u
}

// SetCredentialEncrypted sets the "credential_encrypted" field.
func (_u *UpstreamSiteUpdate) SetCredentialEncrypted(v string) *UpstreamSiteUpdate {
	_u.mutation.SetCredentialEncrypted(v)
	return _u
}

// SetNillableCredentialEncrypted sets the "credential_encrypted" field if the given value is not nil.
func (_u *UpstreamSiteUpdate) SetNillableCredentialEncrypted(v *string) *UpstreamSiteUpdate {
	if v != nil {
		_u.SetCredentialEncrypted(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *UpstreamSiteUpdate) SetSortOrder(v int) *UpstreamSiteUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *UpstreamSiteUpdate) SetNillableSortOrder(v *int) *UpstreamSiteUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *UpstreamSiteUpdate) AddSortOrder(v int) *UpstreamSiteUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *UpstreamSiteUpdate) SetEnabled(v bool) *UpstreamSiteUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *UpstreamSiteUpdate) SetNillableEnabled(v *bool) *UpstreamSiteUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *UpstreamSiteUpdate) SetStatus(v upstreamsite.Status) *UpstreamSiteUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UpstreamSiteUpdate) SetNillableStatus(v *upstreamsite.Status) *UpstreamSiteUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *UpstreamSiteUpdate) SetErrorMessage(v string) *UpstreamSiteUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *UpstreamSiteUpdate) SetNillableErrorMessage(v *string) *UpstreamSiteUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *UpstreamSiteUpdate) ClearErrorMessage() *UpstreamSiteUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetBalanceUsd sets the "balance_usd" field.
func (_u *UpstreamSiteUpdate) SetBalanceUsd(v float64) *UpstreamSiteUpdate {
	_u.mutation.ResetBalanceUsd()
	_u.mutation.SetBalanceUsd(v)
	return _u
}

// SetNillableBalanceUsd sets the "balance_usd" field if the given value is not nil.
func (_u *UpstreamSiteUpdate) SetNillableBalanceUsd(v *float64) *UpstreamSiteUpdate {
	if v != nil {
		_u.SetBalanceUsd(*v)
	}
	return _u
}

// AddBalanceUsd adds value to the "balance_usd" field.
func (_u *UpstreamSiteUpdate) AddBalanceUsd(v float64) *UpstreamSiteUpdate {
	_u.mutation.AddBalanceUsd(v)
	return _u
}

// ClearBalanceUsd clears the value of the "balance_usd" field.
func (_u *UpstreamSiteUpdate) ClearBalanceUsd() *UpstreamSiteUpdate {
	_u.mutation.ClearBalanceUsd()
	return _u
}

// SetTodayTokens sets the "today_tokens" field.
func (_u *UpstreamSiteUpdate) SetTodayTokens(v int64) *UpstreamSiteUpdate {
	_u.mutation.ResetTodayTokens()
	_u.mutation.SetTodayTokens(v)
	return _u
}

// SetNillableTodayTokens sets the "today_tokens" field if the given value is not nil.
func (_u *UpstreamSiteUpdate) SetNillableTodayTokens(v *int64) *UpstreamSiteUpdate {
	if v != nil {
		_u.SetTodayTokens(*v)
	}
	return _u
}

// AddTodayTokens adds value to the "today_tokens" field.
func (_u *UpstreamSiteUpdate) AddTodayTokens(v int64) *UpstreamSiteUpdate {
	_u.mutation.AddTodayTokens(v)
	return _u
}

// SetTodayCostUsd sets the "today_cost_usd" field.
func (_u *UpstreamSiteUpdate) SetTodayCostUsd(v float64) *UpstreamSiteUpdate {
	_u.mutation.ResetTodayCostUsd()
	_u.mutation.SetTodayCostUsd(v)
	return _u
}

// SetNillableTodayCostUsd sets the "today_cost_usd" field if the given value is not nil.
func (_u *UpstreamSiteUpdate) SetNillableTodayCostUsd(v *float64) *UpstreamSiteUpdate {
	if v != nil {
		_u.SetTodayCostUsd(*v)
	}
	return _u
}

// AddTodayCostUsd adds value to the "today_cost_usd" field.
func (_u *UpstreamSiteUpdate) AddTodayCostUsd(v float64) *UpstreamSiteUpdate {
	_u.mutation.AddTodayCostUsd(v)
	return _u
}

// SetTotalTokens sets the "total_tokens" field.
func (_u *UpstreamSiteUpdate) SetTotalTokens(v int64) *UpstreamSiteUpdate {
	_u.mutation.ResetTotalTokens()
	_u.mutation.SetTotalTokens(v)
	return _u
}

// SetNillableTotalTokens sets the "total_tokens" field if the given value is not nil.
func (_u *UpstreamSiteUpdate) SetNillableTotalTokens(v *int64) *UpstreamSiteUpdate {
	if v != nil {
		_u.SetTotalTokens(*v)
	}
	return _u
}

// AddTotalTokens adds value to the "total_tokens" field.
func (_u *UpstreamSiteUpdate) AddTotalTokens(v int64) *UpstreamSiteUpdate {
	_u.mutation.AddTotalTokens(v)
	return _u
}

// SetTotalCostUsd sets the "total_cost_usd" field.
func (_u *UpstreamSiteUpdate) SetTotalCostUsd(v float64) *UpstreamSiteUpdate {
	_u.mutation.ResetTotalCostUsd()
	_u.mutation.SetTotalCostUsd(v)
	return _u
}

// SetNillableTotalCostUsd sets the "total_cost_usd" field if the given value is not nil.
func (_u *UpstreamSiteUpdate) SetNillableTotalCostUsd(v *float64) *UpstreamSiteUpdate {
	if v != nil {
		_u.SetTotalCostUsd(*v)
	}
	return _u
}

// AddTotalCostUsd adds value to the "total_cost_usd" field.
func (_u *UpstreamSiteUpdate) AddTotalCostUsd(v float64) *UpstreamSiteUpdate {
	_u.mutation.AddTotalCostUsd(v)
	return _u
}

// SetTrackingStartedAt sets the "tracking_started_at" field.
func (_u *UpstreamSiteUpdate) SetTrackingStartedAt(v time.Time) *UpstreamSiteUpdate {
	_u.mutation.SetTrackingStartedAt(v)
	return _u
}

// SetNillableTrackingStartedAt sets the "tracking_started_at" field if the given value is not nil.
func (_u *UpstreamSiteUpdate) SetNillableTrackingStartedAt(v *time.Time) *UpstreamSiteUpdate {
	if v != nil {
		_u.SetTrackingStartedAt(*v)
	}
	return _u
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (_u *UpstreamSiteUpdate) SetLastSyncedAt(v time.Time) *UpstreamSiteUpdate {
	_u.mutation.SetLastSyncedAt(v)
	return _u
}

// SetNillableLastSyncedAt sets the "last_synced_at" field if the given value is not nil.
func (_u *UpstreamSiteUpdate) SetNillableLastSyncedAt(v *time.Time) *UpstreamSiteUpdate {
	if v != nil {
		_u.SetLastSyncedAt(*v)
	}
	return _u
}

// ClearLastSyncedAt clears the value of the "last_synced_at" field.
func (_u *UpstreamSiteUpdate) ClearLastSyncedAt() *UpstreamSiteUpdate {
	_u.mutation.ClearLastSyncedAt()
	return _u
}

// SetNextSyncAt sets the "next_sync_at" field.
func (_u *UpstreamSiteUpdate) SetNextSyncAt(v time.Time) *UpstreamSiteUpdate {
	_u.mutation.SetNextSyncAt(v)
	return _u
}

// SetNillableNextSyncAt sets the "next_sync_at" field if the given value is not nil.
func (_u *UpstreamSiteUpdate) SetNillableNextSyncAt(v *time.Time) *UpstreamSiteUpdate {
	if v != nil {
		_u.SetNextSyncAt(*v)
	}
	return _u
}

// ClearNextSyncAt clears the value of the "next_sync_at" field.
func (_u *UpstreamSiteUpdate) ClearNextSyncAt() *UpstreamSiteUpdate {
	_u.mutation.ClearNextSyncAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *UpstreamSiteUpdate) SetCreatedBy(v int64) *UpstreamSiteUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *UpstreamSiteUpdate) SetNillableCreatedBy(v *int64) *UpstreamSiteUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *UpstreamSiteUpdate) AddCreatedBy(v int64) *UpstreamSiteUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// AddGroupIDs adds the "groups" edge to the UpstreamGroup entity by IDs.
func (_u *UpstreamSiteUpdate) AddGroupIDs(ids ...int64) *UpstreamSiteUpdate {
	_u.mutation.AddGroupIDs(ids...)
	return _u
}

// AddGroups adds the "groups" edges to the UpstreamGroup entity.
func (_u *UpstreamSiteUpdate) AddGroups(v ...*UpstreamGroup) *UpstreamSiteUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGroupIDs(ids...)
}

// AddDailyStatIDs adds the "daily_stats" edge to the UpstreamDailyStat entity by IDs.
func (_u *UpstreamSiteUpdate) AddDailyStatIDs(ids ...int64) *UpstreamSiteUpdate {
	_u.mutation.AddDailyStatIDs(ids...)
	return _u
}

// AddDailyStats adds the "daily_stats" edges to the UpstreamDailyStat entity.
func (_u *UpstreamSiteUpdate) AddDailyStats(v ...*UpstreamDailyStat) *UpstreamSiteUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDailyStatIDs(ids...)
}

// AddGroupMultiplierHistoryIDs adds the "group_multiplier_history" edge to the UpstreamGroupMultiplierHistory entity by IDs.
func (_u *UpstreamSiteUpdate) AddGroupMultiplierHistoryIDs(ids ...int64) *UpstreamSiteUpdate {
	_u.mutation.AddGroupMultiplierHistoryIDs(ids...)
	return _u
}

// AddGroupMultiplierHistory adds the "group_multiplier_history" edges to the UpstreamGroupMultiplierHistory entity.
func (_u *UpstreamSiteUpdate) AddGroupMultiplierHistory(v ...*UpstreamGroupMultiplierHistory) *UpstreamSiteUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGroupMultiplierHistoryIDs(ids...)
}

// Mutation returns the UpstreamSiteMutation object of the builder.
func (_u *UpstreamSiteUpdate) Mutation() *UpstreamSiteMutation {
	return _u.mutation
}

// ClearGroups clears all "groups" edges to the UpstreamGroup entity.
func (_u *UpstreamSiteUpdate) ClearGroups() *UpstreamSiteUpdate {
	_u.mutation.ClearGroups()
	return _u
}

// RemoveGroupIDs removes the "groups" edge to UpstreamGroup entities by IDs.
func (_u *UpstreamSiteUpdate) RemoveGroupIDs(ids ...int64) *UpstreamSiteUpdate {
	_u.mutation.RemoveGroupIDs(ids...)
	return _u
}

// RemoveGroups removes "groups" edges to UpstreamGroup entities.
func (_u *UpstreamSiteUpdate) RemoveGroups(v ...*UpstreamGroup) *UpstreamSiteUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGroupIDs(ids...)
}

// ClearDailyStats clears all "daily_stats" edges to the UpstreamDailyStat entity.
func (_u *UpstreamSiteUpdate) ClearDailyStats() *UpstreamSiteUpdate {
	_u.mutation.ClearDailyStats()
	return _u
}

// RemoveDailyStatIDs removes the "daily_stats" edge to UpstreamDailyStat entities by IDs.
func (_u *UpstreamSiteUpdate) RemoveDailyStatIDs(ids ...int64) *UpstreamSiteUpdate {
	_u.mutation.RemoveDailyStatIDs(ids...)
	return _u
}

// RemoveDailyStats removes "daily_stats" edges to UpstreamDailyStat entities.
func (_u *UpstreamSiteUpdate) RemoveDailyStats(v ...*UpstreamDailyStat) *UpstreamSiteUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDailyStatIDs(ids...)
}

// ClearGroupMultiplierHistory clears all "group_multiplier_history" edges to the UpstreamGroupMultiplierHistory entity.
func (_u *UpstreamSiteUpdate) ClearGroupMultiplierHistory() *UpstreamSiteUpdate {
	_u.mutation.ClearGroupMultiplierHistory()
	return _u
}

// RemoveGroupMultiplierHistoryIDs removes the "group_multiplier_history" edge to UpstreamGroupMultiplierHistory entities by IDs.
func (_u *UpstreamSiteUpdate) RemoveGroupMultiplierHistoryIDs(ids ...int64) *UpstreamSiteUpdate {
	_u.mutation.RemoveGroupMultiplierHistoryIDs(ids...)
	return _u
}

// RemoveGroupMultiplierHistory removes "group_multiplier_history" edges to UpstreamGroupMultiplierHistory entities.
func (_u *UpstreamSiteUpdate) RemoveGroupMultiplierHistory(v ...*UpstreamGroupMultiplierHistory) *UpstreamSiteUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGroupMultiplierHistoryIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UpstreamSiteUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UpstreamSiteUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UpstreamSiteUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UpstreamSiteUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UpstreamSiteUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := upstreamsite.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UpstreamSiteUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := upstreamsite.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "UpstreamSite.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BaseURL(); ok {
		if err := upstreamsite.BaseURLValidator(v); err != nil {
			return &ValidationError{Name: "base_url", err: fmt.Errorf(`ent: validator failed for field "UpstreamSite.base_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := upstreamsite.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "UpstreamSite.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AuthMode(); ok {
		if err := upstreamsite.AuthModeValidator(v); err != nil {
			return &ValidationError{Name: "auth_mode", err: fmt.Errorf(`ent: validator failed for field "UpstreamSite.auth_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Account(); ok {
		if err := upstreamsite.AccountValidator(v); err != nil {
			return &ValidationError{Name: "account", err: fmt.Errorf(`ent: validator failed for field "UpstreamSite.account": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CredentialEncrypted(); ok {
		if err := upstreamsite.CredentialEncryptedValidator(v); err != nil {
			return &ValidationError{Name: "credential_encrypted", err: fmt.Errorf(`ent: validator failed for field "UpstreamSite.credential_encrypted": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := upstreamsite.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UpstreamSite.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorMessage(); ok {
		if err := upstreamsite.ErrorMessageValidator(v); err != nil {
			return &ValidationError{Name: "error_message", err: fmt.Errorf(`ent: validator failed for field "UpstreamSite.error_message": %w`, err)}
		}
	}
	return nil
}

func (_u *UpstreamSiteUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(upstreamsite.Table, upstreamsite.Columns, sqlgraph.NewFieldSpec(upstreamsite.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(upstreamsite.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(upstreamsite.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaseURL(); ok {
		_spec.SetField(upstreamsite.FieldBaseURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(upstreamsite.FieldPlatform, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AuthMode(); ok {
		_spec.SetField(upstreamsite.FieldAuthMode, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Account(); ok {
		_spec.SetField(upstreamsite.FieldAccount, field.TypeString, value)
	}
	if value, ok := _u.mutation.CredentialEncrypted(); ok {
		_spec.SetField(upstreamsite.FieldCredentialEncrypted, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(upstreamsite.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(upstreamsite.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(upstreamsite.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(upstreamsite.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(upstreamsite.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(upstreamsite.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.BalanceUsd(); ok {
		_spec.SetField(upstreamsite.FieldBalanceUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceUsd(); ok {
		_spec.AddField(upstreamsite.FieldBalanceUsd, field.TypeFloat64, value)
	}
	if _u.mutation.BalanceUsdCleared() {
		_spec.ClearField(upstreamsite.FieldBalanceUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.TodayTokens(); ok {
		_spec.SetField(upstreamsite.FieldTodayTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTodayTokens(); ok {
		_spec.AddField(upstreamsite.FieldTodayTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TodayCostUsd(); ok {
		_spec.SetField(upstreamsite.FieldTodayCostUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTodayCostUsd(); ok {
		_spec.AddField(upstreamsite.FieldTodayCostUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TotalTokens(); ok {
		_spec.SetField(upstreamsite.FieldTotalTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalTokens(); ok {
		_spec.AddField(upstreamsite.FieldTotalTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TotalCostUsd(); ok {
		_spec.SetField(upstreamsite.FieldTotalCostUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalCostUsd(); ok {
		_spec.AddField(upstreamsite.FieldTotalCostUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TrackingStartedAt(); ok {
		_spec.SetField(upstreamsite.FieldTrackingStartedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastSyncedAt(); ok {
		_spec.SetField(upstreamsite.FieldLastSyncedAt, field.TypeTime, value)
	}
	if _u.mutation.LastSyncedAtCleared() {
		_spec.ClearField(upstreamsite.FieldLastSyncedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.NextSyncAt(); ok {
		_spec.SetField(upstreamsite.FieldNextSyncAt, field.TypeTime, value)
	}
	if _u.mutation.NextSyncAtCleared() {
		_spec.ClearField(upstreamsite.FieldNextSyncAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(upstreamsite.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(upstreamsite.FieldCreatedBy, field.TypeInt64, value)
	}
	if _u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreamsite.GroupsTable,
			Columns: []string{upstreamsite.GroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamgroup.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGroupsIDs(); len(nodes) > 0 && !_u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreamsite.GroupsTable,
			Columns: []string{upstreamsite.GroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamgroup.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreamsite.GroupsTable,
			Columns: []string{upstreamsite.GroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamgroup.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DailyStatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreamsite.DailyStatsTable,
			Columns: []string{upstreamsite.DailyStatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamdailystat.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDailyStatsIDs(); len(nodes) > 0 && !_u.mutation.DailyStatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreamsite.DailyStatsTable,
			Columns: []string{upstreamsite.DailyStatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamdailystat.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DailyStatsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreamsite.DailyStatsTable,
			Columns: []string{upstreamsite.DailyStatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamdailystat.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupMultiplierHistoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreamsite.GroupMultiplierHistoryTable,
			Columns: []string{upstreamsite.GroupMultiplierHistoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamgroupmultiplierhistory.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGroupMultiplierHistoryIDs(); len(nodes) > 0 && !_u.mutation.GroupMultiplierHistoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreamsite.GroupMultiplierHistoryTable,
			Columns: []string{upstreamsite.GroupMultiplierHistoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamgroupmultiplierhistory.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupMultiplierHistoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreamsite.GroupMultiplierHistoryTable,
			Columns: []string{upstreamsite.GroupMultiplierHistoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamgroupmultiplierhistory.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upstreamsite.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UpstreamSiteUpdateOne is the builder for updating a single UpstreamSite entity.
type UpstreamSiteUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UpstreamSiteMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UpstreamSiteUpdateOne) SetUpdatedAt(v time.Time) *UpstreamSiteUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *UpstreamSiteUpdateOne) SetName(v string) *UpstreamSiteUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UpstreamSiteUpdateOne) SetNillableName(v *string) *UpstreamSiteUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetBaseURL sets the "base_url" field.
func (_u *UpstreamSiteUpdateOne) SetBaseURL(v string) *UpstreamSiteUpdateOne {
	_u.mutation.SetBaseURL(v)
	return _u
}

// SetNillableBaseURL sets the "base_url" field if the given value is not nil.
func (_u *UpstreamSiteUpdateOne) SetNillableBaseURL(v *string) *UpstreamSiteUpdateOne {
	if v != nil {
		_u.SetBaseURL(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *UpstreamSiteUpdateOne) SetPlatform(v upstreamsite.Platform) *UpstreamSiteUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *UpstreamSiteUpdateOne) SetNillablePlatform(v *upstreamsite.Platform) *UpstreamSiteUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetAuthMode sets the "auth_mode" field.
func (_u *UpstreamSiteUpdateOne) SetAuthMode(v upstreamsite.AuthMode) *UpstreamSiteUpdateOne {
	_u.mutation.SetAuthMode(v)
	return _u
}

// SetNillableAuthMode sets the "auth_mode" field if the given value is not nil.
func (_u *UpstreamSiteUpdateOne) SetNillableAuthMode(v *upstreamsite.AuthMode) *UpstreamSiteUpdateOne {
	if v != nil {
		_u.SetAuthMode(*v)
	}
	return _u
}

// SetAccount sets the "account" field.
func (_u *UpstreamSiteUpdateOne) SetAccount(v string) *UpstreamSiteUpdateOne {
	_u.mutation.SetAccount(v)
	return _u
}

// SetNillableAccount sets the "account" field if the given value is not nil.
func (_u *UpstreamSiteUpdateOne) SetNillableAccount(v *string) *UpstreamSiteUpdateOne {
	if v != nil {
		_u.SetAccount(*v)
	}
	return _u
}

// SetCredentialEncrypted sets the "credential_encrypted" field.
func (_u *UpstreamSiteUpdateOne) SetCredentialEncrypted(v string) *UpstreamSiteUpdateOne {
	_u.mutation.SetCredentialEncrypted(v)
	return _u
}

// SetNillableCredentialEncrypted sets the "credential_encrypted" field if the given value is not nil.
func (_u *UpstreamSiteUpdateOne) SetNillableCredentialEncrypted(v *string) *UpstreamSiteUpdateOne {
	if v != nil {
		_u.SetCredentialEncrypted(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *UpstreamSiteUpdateOne) SetSortOrder(v int) *UpstreamSiteUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *UpstreamSiteUpdateOne) SetNillableSortOrder(v *int) *UpstreamSiteUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *UpstreamSiteUpdateOne) AddSortOrder(v int) *UpstreamSiteUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *UpstreamSiteUpdateOne) SetEnabled(v bool) *UpstreamSiteUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *UpstreamSiteUpdateOne) SetNillableEnabled(v *bool) *UpstreamSiteUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *UpstreamSiteUpdateOne) SetStatus(v upstreamsite.Status) *UpstreamSiteUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UpstreamSiteUpdateOne) SetNillableStatus(v *upstreamsite.Status) *UpstreamSiteUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *UpstreamSiteUpdateOne) SetErrorMessage(v string) *UpstreamSiteUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *UpstreamSiteUpdateOne) SetNillableErrorMessage(v *string) *UpstreamSiteUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *UpstreamSiteUpdateOne) ClearErrorMessage() *UpstreamSiteUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetBalanceUsd sets the "balance_usd" field.
func (_u *UpstreamSiteUpdateOne) SetBalanceUsd(v float64) *UpstreamSiteUpdateOne {
	_u.mutation.ResetBalanceUsd()
	_u.mutation.SetBalanceUsd(v)
	return _u
}

// SetNillableBalanceUsd sets the "balance_usd" field if the given value is not nil.
func (_u *UpstreamSiteUpdateOne) SetNillableBalanceUsd(v *float64) *UpstreamSiteUpdateOne {
	if v != nil {
		_u.SetBalanceUsd(*v)
	}
	return _u
}

// AddBalanceUsd adds value to the "balance_usd" field.
func (_u *UpstreamSiteUpdateOne) AddBalanceUsd(v float64) *UpstreamSiteUpdateOne {
	_u.mutation.AddBalanceUsd(v)
	return _u
}

// ClearBalanceUsd clears the value of the "balance_usd" field.
func (_u *UpstreamSiteUpdateOne) ClearBalanceUsd() *UpstreamSiteUpdateOne {
	_u.mutation.ClearBalanceUsd()
	return _u
}

// SetTodayTokens sets the "today_tokens" field.
func (_u *UpstreamSiteUpdateOne) SetTodayTokens(v int64) *UpstreamSiteUpdateOne {
	_u.mutation.ResetTodayTokens()
	_u.mutation.SetTodayTokens(v)
	return _u
}

// SetNillableTodayTokens sets the "today_tokens" field if the given value is not nil.
func (_u *UpstreamSiteUpdateOne) SetNillableTodayTokens(v *int64) *UpstreamSiteUpdateOne {
	if v != nil {
		_u.SetTodayTokens(*v)
	}
	return _u
}

// AddTodayTokens adds value to the "today_tokens" field.
func (_u *UpstreamSiteUpdateOne) AddTodayTokens(v int64) *UpstreamSiteUpdateOne {
	_u.mutation.AddTodayTokens(v)
	return _u
}

// SetTodayCostUsd sets the "today_cost_usd" field.
func (_u *UpstreamSiteUpdateOne) SetTodayCostUsd(v float64) *UpstreamSiteUpdateOne {
	_u.mutation.ResetTodayCostUsd()
	_u.mutation.SetTodayCostUsd(v)
	return _u
}

// SetNillableTodayCostUsd sets the "today_cost_usd" field if the given value is not nil.
func (_u *UpstreamSiteUpdateOne) SetNillableTodayCostUsd(v *float64) *UpstreamSiteUpdateOne {
	if v != nil {
		_u.SetTodayCostUsd(*v)
	}
	return _u
}

// AddTodayCostUsd adds value to the "today_cost_usd" field.
func (_u *UpstreamSiteUpdateOne) AddTodayCostUsd(v float64) *UpstreamSiteUpdateOne {
	_u.mutation.AddTodayCostUsd(v)
	return _u
}

// SetTotalTokens sets the "total_tokens" field.
func (_u *UpstreamSiteUpdateOne) SetTotalTokens(v int64) *UpstreamSiteUpdateOne {
	_u.mutation.ResetTotalTokens()
	_u.mutation.SetTotalTokens(v)
	return _u
}

// SetNillableTotalTokens sets the "total_tokens" field if the given value is not nil.
func (_u *UpstreamSiteUpdateOne) SetNillableTotalTokens(v *int64) *UpstreamSiteUpdateOne {
	if v != nil {
		_u.SetTotalTokens(*v)
	}
	return _u
}

// AddTotalTokens adds value to the "total_tokens" field.
func (_u *UpstreamSiteUpdateOne) AddTotalTokens(v int64) *UpstreamSiteUpdateOne {
	_u.mutation.AddTotalTokens(v)
	return _u
}

// SetTotalCostUsd sets the "total_cost_usd" field.
func (_u *UpstreamSiteUpdateOne) SetTotalCostUsd(v float64) *UpstreamSiteUpdateOne {
	_u.mutation.ResetTotalCostUsd()
	_u.mutation.SetTotalCostUsd(v)
	return _u
}

// SetNillableTotalCostUsd sets the "total_cost_usd" field if the given value is not nil.
func (_u *UpstreamSiteUpdateOne) SetNillableTotalCostUsd(v *float64) *UpstreamSiteUpdateOne {
	if v != nil {
		_u.SetTotalCostUsd(*v)
	}
	return _u
}

// AddTotalCostUsd adds value to the "total_cost_usd" field.
func (_u *UpstreamSiteUpdateOne) AddTotalCostUsd(v float64) *UpstreamSiteUpdateOne {
	_u.mutation.AddTotalCostUsd(v)
	return _u
}

// SetTrackingStartedAt sets the "tracking_started_at" field.
func (_u *UpstreamSiteUpdateOne) SetTrackingStartedAt(v time.Time) *UpstreamSiteUpdateOne {
	_u.mutation.SetTrackingStartedAt(v)
	return _u
}

// SetNillableTrackingStartedAt sets the "tracking_started_at" field if the given value is not nil.
func (_u *UpstreamSiteUpdateOne) SetNillableTrackingStartedAt(v *time.Time) *UpstreamSiteUpdateOne {
	if v != nil {
		_u.SetTrackingStartedAt(*v)
	}
	return _u
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (_u *UpstreamSiteUpdateOne) SetLastSyncedAt(v time.Time) *UpstreamSiteUpdateOne {
	_u.mutation.SetLastSyncedAt(v)
	return _u
}

// SetNillableLastSyncedAt sets the "last_synced_at" field if the given value is not nil.
func (_u *UpstreamSiteUpdateOne) SetNillableLastSyncedAt(v *time.Time) *UpstreamSiteUpdateOne {
	if v != nil {
		_u.SetLastSyncedAt(*v)
	}
	return _u
}

// ClearLastSyncedAt clears the value of the "last_synced_at" field.
func (_u *UpstreamSiteUpdateOne) ClearLastSyncedAt() *UpstreamSiteUpdateOne {
	_u.mutation.ClearLastSyncedAt()
	return _u
}

// SetNextSyncAt sets the "next_sync_at" field.
func (_u *UpstreamSiteUpdateOne) SetNextSyncAt(v time.Time) *UpstreamSiteUpdateOne {
	_u.mutation.SetNextSyncAt(v)
	return _u
}

// SetNillableNextSyncAt sets the "next_sync_at" field if the given value is not nil.
func (_u *UpstreamSiteUpdateOne) SetNillableNextSyncAt(v *time.Time) *UpstreamSiteUpdateOne {
	if v != nil {
		_u.SetNextSyncAt(*v)
	}
	return _u
}

// ClearNextSyncAt clears the value of the "next_sync_at" field.
func (_u *UpstreamSiteUpdateOne) ClearNextSyncAt() *UpstreamSiteUpdateOne {
	_u.mutation.ClearNextSyncAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *UpstreamSiteUpdateOne) SetCreatedBy(v int64) *UpstreamSiteUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *UpstreamSiteUpdateOne) SetNillableCreatedBy(v *int64) *UpstreamSiteUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *UpstreamSiteUpdateOne) AddCreatedBy(v int64) *UpstreamSiteUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// AddGroupIDs adds the "groups" edge to the UpstreamGroup entity by IDs.
func (_u *UpstreamSiteUpdateOne) AddGroupIDs(ids ...int64) *UpstreamSiteUpdateOne {
	_u.mutation.AddGroupIDs(ids...)
	return _u
}

// AddGroups adds the "groups" edges to the UpstreamGroup entity.
func (_u *UpstreamSiteUpdateOne) AddGroups(v ...*UpstreamGroup) *UpstreamSiteUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGroupIDs(ids...)
}

// AddDailyStatIDs adds the "daily_stats" edge to the UpstreamDailyStat entity by IDs.
func (_u *UpstreamSiteUpdateOne) AddDailyStatIDs(ids ...int64) *UpstreamSiteUpdateOne {
	_u.mutation.AddDailyStatIDs(ids...)
	return _u
}

// AddDailyStats adds the "daily_stats" edges to the UpstreamDailyStat entity.
func (_u *UpstreamSiteUpdateOne) AddDailyStats(v ...*UpstreamDailyStat) *UpstreamSiteUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDailyStatIDs(ids...)
}

// AddGroupMultiplierHistoryIDs adds the "group_multiplier_history" edge to the UpstreamGroupMultiplierHistory entity by IDs.
func (_u *UpstreamSiteUpdateOne) AddGroupMultiplierHistoryIDs(ids ...int64) *UpstreamSiteUpdateOne {
	_u.mutation.AddGroupMultiplierHistoryIDs(ids...)
	return _u
}

// AddGroupMultiplierHistory adds the "group_multiplier_history" edges to the UpstreamGroupMultiplierHistory entity.
func (_u *UpstreamSiteUpdateOne) AddGroupMultiplierHistory(v ...*UpstreamGroupMultiplierHistory) *UpstreamSiteUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGroupMultiplierHistoryIDs(ids...)
}

// Mutation returns the UpstreamSiteMutation object of the builder.
func (_u *UpstreamSiteUpdateOne) Mutation() *UpstreamSiteMutation {
	return _u.mutation
}

// ClearGroups clears all "groups" edges to the UpstreamGroup entity.
func (_u *UpstreamSiteUpdateOne) ClearGroups() *UpstreamSiteUpdateOne {
	_u.mutation.ClearGroups()
	return _u
}

// RemoveGroupIDs removes the "groups" edge to UpstreamGroup entities by IDs.
func (_u *UpstreamSiteUpdateOne) RemoveGroupIDs(ids ...int64) *UpstreamSiteUpdateOne {
	_u.mutation.RemoveGroupIDs(ids...)
	return _u
}

// RemoveGroups removes "groups" edges to UpstreamGroup entities.
func (_u *UpstreamSiteUpdateOne) RemoveGroups(v ...*UpstreamGroup) *UpstreamSiteUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGroupIDs(ids...)
}

// ClearDailyStats clears all "daily_stats" edges to the UpstreamDailyStat entity.
func (_u *UpstreamSiteUpdateOne) ClearDailyStats() *UpstreamSiteUpdateOne {
	_u.mutation.ClearDailyStats()
	return _u
}

// RemoveDailyStatIDs removes the "daily_stats" edge to UpstreamDailyStat entities by IDs.
func (_u *UpstreamSiteUpdateOne) RemoveDailyStatIDs(ids ...int64) *UpstreamSiteUpdateOne {
	_u.mutation.RemoveDailyStatIDs(ids...)
	return _u
}

// RemoveDailyStats removes "daily_stats" edges to UpstreamDailyStat entities.
func (_u *UpstreamSiteUpdateOne) RemoveDailyStats(v ...*UpstreamDailyStat) *UpstreamSiteUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDailyStatIDs(ids...)
}

// ClearGroupMultiplierHistory clears all "group_multiplier_history" edges to the UpstreamGroupMultiplierHistory entity.
func (_u *UpstreamSiteUpdateOne) ClearGroupMultiplierHistory() *UpstreamSiteUpdateOne {
	_u.mutation.ClearGroupMultiplierHistory()
	return _u
}

// RemoveGroupMultiplierHistoryIDs removes the "group_multiplier_history" edge to UpstreamGroupMultiplierHistory entities by IDs.
func (_u *UpstreamSiteUpdateOne) RemoveGroupMultiplierHistoryIDs(ids ...int64) *UpstreamSiteUpdateOne {
	_u.mutation.RemoveGroupMultiplierHistoryIDs(ids...)
	return _u
}

// RemoveGroupMultiplierHistory removes "group_multiplier_history" edges to UpstreamGroupMultiplierHistory entities.
func (_u *UpstreamSiteUpdateOne) RemoveGroupMultiplierHistory(v ...*UpstreamGroupMultiplierHistory) *UpstreamSiteUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGroupMultiplierHistoryIDs(ids...)
}

// Where appends a list predicates to the UpstreamSiteUpdate builder.
func (_u *UpstreamSiteUpdateOne) Where(ps ...predicate.UpstreamSite) *UpstreamSiteUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UpstreamSiteUpdateOne) Select(field string, fields ...string) *UpstreamSiteUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UpstreamSite entity.
func (_u *UpstreamSiteUpdateOne) Save(ctx context.Context) (*UpstreamSite, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UpstreamSiteUpdateOne) SaveX(ctx context.Context) *UpstreamSite {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UpstreamSiteUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UpstreamSiteUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UpstreamSiteUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := upstreamsite.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UpstreamSiteUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := upstreamsite.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "UpstreamSite.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BaseURL(); ok {
		if err := upstreamsite.BaseURLValidator(v); err != nil {
			return &ValidationError{Name: "base_url", err: fmt.Errorf(`ent: validator failed for field "UpstreamSite.base_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := upstreamsite.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "UpstreamSite.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AuthMode(); ok {
		if err := upstreamsite.AuthModeValidator(v); err != nil {
			return &ValidationError{Name: "auth_mode", err: fmt.Errorf(`ent: validator failed for field "UpstreamSite.auth_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Account(); ok {
		if err := upstreamsite.AccountValidator(v); err != nil {
			return &ValidationError{Name: "account", err: fmt.Errorf(`ent: validator failed for field "UpstreamSite.account": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CredentialEncrypted(); ok {
		if err := upstreamsite.CredentialEncryptedValidator(v); err != nil {
			return &ValidationError{Name: "credential_encrypted", err: fmt.Errorf(`ent: validator failed for field "UpstreamSite.credential_encrypted": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := upstreamsite.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UpstreamSite.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorMessage(); ok {
		if err := upstreamsite.ErrorMessageValidator(v); err != nil {
			return &ValidationError{Name: "error_message", err: fmt.Errorf(`ent: validator failed for field "UpstreamSite.error_message": %w`, err)}
		}
	}
	return nil
}

func (_u *UpstreamSiteUpdateOne) sqlSave(ctx context.Context) (_node *UpstreamSite, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(upstreamsite.Table, upstreamsite.Columns, sqlgraph.NewFieldSpec(upstreamsite.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UpstreamSite.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, upstreamsite.FieldID)
		for _, f := range fields {
			if !upstreamsite.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != upstreamsite.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(upstreamsite.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(upstreamsite.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaseURL(); ok {
		_spec.SetField(upstreamsite.FieldBaseURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(upstreamsite.FieldPlatform, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AuthMode(); ok {
		_spec.SetField(upstreamsite.FieldAuthMode, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Account(); ok {
		_spec.SetField(upstreamsite.FieldAccount, field.TypeString, value)
	}
	if value, ok := _u.mutation.CredentialEncrypted(); ok {
		_spec.SetField(upstreamsite.FieldCredentialEncrypted, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(upstreamsite.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(upstreamsite.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(upstreamsite.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(upstreamsite.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(upstreamsite.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(upstreamsite.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.BalanceUsd(); ok {
		_spec.SetField(upstreamsite.FieldBalanceUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceUsd(); ok {
		_spec.AddField(upstreamsite.FieldBalanceUsd, field.TypeFloat64, value)
	}
	if _u.mutation.BalanceUsdCleared() {
		_spec.ClearField(upstreamsite.FieldBalanceUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.TodayTokens(); ok {
		_spec.SetField(upstreamsite.FieldTodayTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTodayTokens(); ok {
		_spec.AddField(upstreamsite.FieldTodayTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TodayCostUsd(); ok {
		_spec.SetField(upstreamsite.FieldTodayCostUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTodayCostUsd(); ok {
		_spec.AddField(upstreamsite.FieldTodayCostUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TotalTokens(); ok {
		_spec.SetField(upstreamsite.FieldTotalTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalTokens(); ok {
		_spec.AddField(upstreamsite.FieldTotalTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TotalCostUsd(); ok {
		_spec.SetField(upstreamsite.FieldTotalCostUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalCostUsd(); ok {
		_spec.AddField(upstreamsite.FieldTotalCostUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TrackingStartedAt(); ok {
		_spec.SetField(upstreamsite.FieldTrackingStartedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastSyncedAt(); ok {
		_spec.SetField(upstreamsite.FieldLastSyncedAt, field.TypeTime, value)
	}
	if _u.mutation.LastSyncedAtCleared() {
		_spec.ClearField(upstreamsite.FieldLastSyncedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.NextSyncAt(); ok {
		_spec.SetField(upstreamsite.FieldNextSyncAt, field.TypeTime, value)
	}
	if _u.mutation.NextSyncAtCleared() {
		_spec.ClearField(upstreamsite.FieldNextSyncAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(upstreamsite.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(upstreamsite.FieldCreatedBy, field.TypeInt64, value)
	}
	if _u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreamsite.GroupsTable,
			Columns: []string{upstreamsite.GroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamgroup.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGroupsIDs(); len(nodes) > 0 && !_u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreamsite.GroupsTable,
			Columns: []string{upstreamsite.GroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamgroup.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreamsite.GroupsTable,
			Columns: []string{upstreamsite.GroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamgroup.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DailyStatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreamsite.DailyStatsTable,
			Columns: []string{upstreamsite.DailyStatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamdailystat.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDailyStatsIDs(); len(nodes) > 0 && !_u.mutation.DailyStatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreamsite.DailyStatsTable,
			Columns: []string{upstreamsite.DailyStatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamdailystat.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DailyStatsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreamsite.DailyStatsTable,
			Columns: []string{upstreamsite.DailyStatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamdailystat.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupMultiplierHistoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreamsite.GroupMultiplierHistoryTable,
			Columns: []string{upstreamsite.GroupMultiplierHistoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamgroupmultiplierhistory.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGroupMultiplierHistoryIDs(); len(nodes) > 0 && !_u.mutation.GroupMultiplierHistoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreamsite.GroupMultiplierHistoryTable,
			Columns: []string{upstreamsite.GroupMultiplierHistoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamgroupmultiplierhistory.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupMultiplierHistoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreamsite.GroupMultiplierHistoryTable,
			Columns: []string{upstreamsite.GroupMultiplierHistoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamgroupmultiplierhistory.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UpstreamSite{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upstreamsite.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
