// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/upstreamgroup"
	"github.com/Wei-Shaw/sub2api/ent/upstreamgroupaccountbinding"
)

// UpstreamGroupAccountBindingQuery is the builder for querying UpstreamGroupAccountBinding entities.
type UpstreamGroupAccountBindingQuery struct {
	config
	ctx               *QueryContext
	order             []upstreamgroupaccountbinding.OrderOption
	inters            []Interceptor
	predicates        []predicate.UpstreamGroupAccountBinding
	withUpstreamGroup *UpstreamGroupQuery
	withLocalGroup    *GroupQuery
	withAccount       *AccountQuery
	modifiers         []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UpstreamGroupAccountBindingQuery builder.
func (_q *UpstreamGroupAccountBindingQuery) Where(ps ...predicate.UpstreamGroupAccountBinding) *UpstreamGroupAccountBindingQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *UpstreamGroupAccountBindingQuery) Limit(limit int) *UpstreamGroupAccountBindingQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *UpstreamGroupAccountBindingQuery) Offset(offset int) *UpstreamGroupAccountBindingQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *UpstreamGroupAccountBindingQuery) Unique(unique bool) *UpstreamGroupAccountBindingQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *UpstreamGroupAccountBindingQuery) Order(o ...upstreamgroupaccountbinding.OrderOption) *UpstreamGroupAccountBindingQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryUpstreamGroup chains the current query on the "upstream_group" edge.
func (_q *UpstreamGroupAccountBindingQuery) QueryUpstreamGroup() *UpstreamGroupQuery {
	query := (&UpstreamGroupClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(upstreamgroupaccountbinding.Table, upstreamgroupaccountbinding.FieldID, selector),
			sqlgraph.To(upstreamgroup.Table, upstreamgroup.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, upstreamgroupaccountbinding.UpstreamGroupTable, upstreamgroupaccountbinding.UpstreamGroupColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryLocalGroup chains the current query on the "local_group" edge.
func (_q *UpstreamGroupAccountBindingQuery) QueryLocalGroup() *GroupQuery {
	query := (&GroupClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(upstreamgroupaccountbinding.Table, upstreamgroupaccountbinding.FieldID, selector),
			sqlgraph.To(group.Table, group.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, upstreamgroupaccountbinding.LocalGroupTable, upstreamgroupaccountbinding.LocalGroupColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAccount chains the current query on the "account" edge.
func (_q *UpstreamGroupAccountBindingQuery) QueryAccount() *AccountQuery {
	query := (&AccountClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(upstreamgroupaccountbinding.Table, upstreamgroupaccountbinding.FieldID, selector),
			sqlgraph.To(account.Table, account.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, upstreamgroupaccountbinding.AccountTable, upstreamgroupaccountbinding.AccountColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first UpstreamGroupAccountBinding entity from the query.
// Returns a *NotFoundError when no UpstreamGroupAccountBinding was found.
func (_q *UpstreamGroupAccountBindingQuery) First(ctx context.Context) (*UpstreamGroupAccountBinding, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{upstreamgroupaccountbinding.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *UpstreamGroupAccountBindingQuery) FirstX(ctx context.Context) *UpstreamGroupAccountBinding {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UpstreamGroupAccountBinding ID from the query.
// Returns a *NotFoundError when no UpstreamGroupAccountBinding ID was found.
func (_q *UpstreamGroupAccountBindingQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{upstreamgroupaccountbinding.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *UpstreamGroupAccountBindingQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UpstreamGroupAccountBinding entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UpstreamGroupAccountBinding entity is found.
// Returns a *NotFoundError when no UpstreamGroupAccountBinding entities are found.
func (_q *UpstreamGroupAccountBindingQuery) Only(ctx context.Context) (*UpstreamGroupAccountBinding, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{upstreamgroupaccountbinding.Label}
	default:
		return nil, &NotSingularError{upstreamgroupaccountbinding.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *UpstreamGroupAccountBindingQuery) OnlyX(ctx context.Context) *UpstreamGroupAccountBinding {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UpstreamGroupAccountBinding ID in the query.
// Returns a *NotSingularError when more than one UpstreamGroupAccountBinding ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *UpstreamGroupAccountBindingQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{upstreamgroupaccountbinding.Label}
	default:
		err = &NotSingularError{upstreamgroupaccountbinding.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *UpstreamGroupAccountBindingQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UpstreamGroupAccountBindings.
func (_q *UpstreamGroupAccountBindingQuery) All(ctx context.Context) ([]*UpstreamGroupAccountBinding, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UpstreamGroupAccountBinding, *UpstreamGroupAccountBindingQuery]()
	return withInterceptors[[]*UpstreamGroupAccountBinding](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *UpstreamGroupAccountBindingQuery) AllX(ctx context.Context) []*UpstreamGroupAccountBinding {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UpstreamGroupAccountBinding IDs.
func (_q *UpstreamGroupAccountBindingQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(upstreamgroupaccountbinding.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *UpstreamGroupAccountBindingQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *UpstreamGroupAccountBindingQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*UpstreamGroupAccountBindingQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *UpstreamGroupAccountBindingQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *UpstreamGroupAccountBindingQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *UpstreamGroupAccountBindingQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UpstreamGroupAccountBindingQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *UpstreamGroupAccountBindingQuery) Clone() *UpstreamGroupAccountBindingQuery {
	if _q == nil {
		return nil
	}
	return &UpstreamGroupAccountBindingQuery{
		config:            _q.config,
		ctx:               _q.ctx.Clone(),
		order:             append([]upstreamgroupaccountbinding.OrderOption{}, _q.order...),
		inters:            append([]Interceptor{}, _q.inters...),
		predicates:        append([]predicate.UpstreamGroupAccountBinding{}, _q.predicates...),
		withUpstreamGroup: _q.withUpstreamGroup.Clone(),
		withLocalGroup:    _q.withLocalGroup.Clone(),
		withAccount:       _q.withAccount.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithUpstreamGroup tells the query-builder to eager-load the nodes that are connected to
// the "upstream_group" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *UpstreamGroupAccountBindingQuery) WithUpstreamGroup(opts ...func(*UpstreamGroupQuery)) *UpstreamGroupAccountBindingQuery {
	query := (&UpstreamGroupClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUpstreamGroup = query
	return _q
}

// WithLocalGroup tells the query-builder to eager-load the nodes that are connected to
// the "local_group" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *UpstreamGroupAccountBindingQuery) WithLocalGroup(opts ...func(*GroupQuery)) *UpstreamGroupAccountBindingQuery {
	query := (&GroupClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withLocalGroup = query
	return _q
}

// WithAccount tells the query-builder to eager-load the nodes that are connected to
// the "account" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *UpstreamGroupAccountBindingQuery) WithAccount(opts ...func(*AccountQuery)) *UpstreamGroupAccountBindingQuery {
	query := (&AccountClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAccount = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UpstreamGroupID int64 `json:"upstream_group_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UpstreamGroupAccountBinding.Query().
//		GroupBy(upstreamgroupaccountbinding.FieldUpstreamGroupID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *UpstreamGroupAccountBindingQuery) GroupBy(field string, fields ...string) *UpstreamGroupAccountBindingGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UpstreamGroupAccountBindingGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = upstreamgroupaccountbinding.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UpstreamGroupID int64 `json:"upstream_group_id,omitempty"`
//	}
//
//	client.UpstreamGroupAccountBinding.Query().
//		Select(upstreamgroupaccountbinding.FieldUpstreamGroupID).
//		Scan(ctx, &v)
func (_q *UpstreamGroupAccountBindingQuery) Select(fields ...string) *UpstreamGroupAccountBindingSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &UpstreamGroupAccountBindingSelect{UpstreamGroupAccountBindingQuery: _q}
	sbuild.label = upstreamgroupaccountbinding.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UpstreamGroupAccountBindingSelect configured with the given aggregations.
func (_q *UpstreamGroupAccountBindingQuery) Aggregate(fns ...AggregateFunc) *UpstreamGroupAccountBindingSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *UpstreamGroupAccountBindingQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !upstreamgroupaccountbinding.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *UpstreamGroupAccountBindingQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UpstreamGroupAccountBinding, error) {
	var (
		nodes       = []*UpstreamGroupAccountBinding{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withUpstreamGroup != nil,
			_q.withLocalGroup != nil,
			_q.withAccount != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UpstreamGroupAccountBinding).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UpstreamGroupAccountBinding{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withUpstreamGroup; query != nil {
		if err := _q.loadUpstreamGroup(ctx, query, nodes, nil,
			func(n *UpstreamGroupAccountBinding, e *UpstreamGroup) { n.Edges.UpstreamGroup = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withLocalGroup; query != nil {
		if err := _q.loadLocalGroup(ctx, query, nodes, nil,
			func(n *UpstreamGroupAccountBinding, e *Group) { n.Edges.LocalGroup = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withAccount; query != nil {
		if err := _q.loadAccount(ctx, query, nodes, nil,
			func(n *UpstreamGroupAccountBinding, e *Account) { n.Edges.Account = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *UpstreamGroupAccountBindingQuery) loadUpstreamGroup(ctx context.Context, query *UpstreamGroupQuery, nodes []*UpstreamGroupAccountBinding, init func(*UpstreamGroupAccountBinding), assign func(*UpstreamGroupAccountBinding, *UpstreamGroup)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*UpstreamGroupAccountBinding)
	for i := range nodes {
		fk := nodes[i].UpstreamGroupID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(upstreamgroup.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "upstream_group_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *UpstreamGroupAccountBindingQuery) loadLocalGroup(ctx context.Context, query *GroupQuery, nodes []*UpstreamGroupAccountBinding, init func(*UpstreamGroupAccountBinding), assign func(*UpstreamGroupAccountBinding, *Group)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*UpstreamGroupAccountBinding)
	for i := range nodes {
		fk := nodes[i].LocalGroupID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(group.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "local_group_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *UpstreamGroupAccountBindingQuery) loadAccount(ctx context.Context, query *AccountQuery, nodes []*UpstreamGroupAccountBinding, init func(*UpstreamGroupAccountBinding), assign func(*UpstreamGroupAccountBinding, *Account)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*UpstreamGroupAccountBinding)
	for i := range nodes {
		fk := nodes[i].AccountID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(account.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "account_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *UpstreamGroupAccountBindingQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *UpstreamGroupAccountBindingQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(upstreamgroupaccountbinding.Table, upstreamgroupaccountbinding.Columns, sqlgraph.NewFieldSpec(upstreamgroupaccountbinding.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, upstreamgroupaccountbinding.FieldID)
		for i := range fields {
			if fields[i] != upstreamgroupaccountbinding.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withUpstreamGroup != nil {
			_spec.Node.AddColumnOnce(upstreamgroupaccountbinding.FieldUpstreamGroupID)
		}
		if _q.withLocalGroup != nil {
			_spec.Node.AddColumnOnce(upstreamgroupaccountbinding.FieldLocalGroupID)
		}
		if _q.withAccount != nil {
			_spec.Node.AddColumnOnce(upstreamgroupaccountbinding.FieldAccountID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *UpstreamGroupAccountBindingQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(upstreamgroupaccountbinding.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = upstreamgroupaccountbinding.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *UpstreamGroupAccountBindingQuery) ForUpdate(opts ...sql.LockOption) *UpstreamGroupAccountBindingQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *UpstreamGroupAccountBindingQuery) ForShare(opts ...sql.LockOption) *UpstreamGroupAccountBindingQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// UpstreamGroupAccountBindingGroupBy is the group-by builder for UpstreamGroupAccountBinding entities.
type UpstreamGroupAccountBindingGroupBy struct {
	selector
	build *UpstreamGroupAccountBindingQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *UpstreamGroupAccountBindingGroupBy) Aggregate(fns ...AggregateFunc) *UpstreamGroupAccountBindingGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *UpstreamGroupAccountBindingGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UpstreamGroupAccountBindingQuery, *UpstreamGroupAccountBindingGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *UpstreamGroupAccountBindingGroupBy) sqlScan(ctx context.Context, root *UpstreamGroupAccountBindingQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UpstreamGroupAccountBindingSelect is the builder for selecting fields of UpstreamGroupAccountBinding entities.
type UpstreamGroupAccountBindingSelect struct {
	*UpstreamGroupAccountBindingQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *UpstreamGroupAccountBindingSelect) Aggregate(fns ...AggregateFunc) *UpstreamGroupAccountBindingSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *UpstreamGroupAccountBindingSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UpstreamGroupAccountBindingQuery, *UpstreamGroupAccountBindingSelect](ctx, _s.UpstreamGroupAccountBindingQuery, _s, _s.inters, v)
}

func (_s *UpstreamGroupAccountBindingSelect) sqlScan(ctx context.Context, root *UpstreamGroupAccountBindingQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
