// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/upstreamdailystat"
	"github.com/Wei-Shaw/sub2api/ent/upstreamsite"
)

// UpstreamDailyStatUpdate is the builder for updating UpstreamDailyStat entities.
type UpstreamDailyStatUpdate struct {
	config
	hooks    []Hook
	mutation *UpstreamDailyStatMutation
}

// Where appends a list predicates to the UpstreamDailyStatUpdate builder.
func (_u *UpstreamDailyStatUpdate) Where(ps ...predicate.UpstreamDailyStat) *UpstreamDailyStatUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSiteID sets the "site_id" field.
func (_u *UpstreamDailyStatUpdate) SetSiteID(v int64) *UpstreamDailyStatUpdate {
	_u.mutation.SetSiteID(v)
	return _u
}

// SetNillableSiteID sets the "site_id" field if the given value is not nil.
func (_u *UpstreamDailyStatUpdate) SetNillableSiteID(v *int64) *UpstreamDailyStatUpdate {
	if v != nil {
		_u.SetSiteID(*v)
	}
	return _u
}

// SetUsageDate sets the "usage_date" field.
func (_u *UpstreamDailyStatUpdate) SetUsageDate(v time.Time) *UpstreamDailyStatUpdate {
	_u.mutation.SetUsageDate(v)
	return _u
}

// SetNillableUsageDate sets the "usage_date" field if the given value is not nil.
func (_u *UpstreamDailyStatUpdate) SetNillableUsageDate(v *time.Time) *UpstreamDailyStatUpdate {
	if v != nil {
		_u.SetUsageDate(*v)
	}
	return _u
}

// SetBalanceUsd sets the "balance_usd" field.
func (_u *UpstreamDailyStatUpdate) SetBalanceUsd(v float64) *UpstreamDailyStatUpdate {
	_u.mutation.ResetBalanceUsd()
	_u.mutation.SetBalanceUsd(v)
	return _u
}

// SetNillableBalanceUsd sets the "balance_usd" field if the given value is not nil.
func (_u *UpstreamDailyStatUpdate) SetNillableBalanceUsd(v *float64) *UpstreamDailyStatUpdate {
	if v != nil {
		_u.SetBalanceUsd(*v)
	}
	return _u
}

// AddBalanceUsd adds value to the "balance_usd" field.
func (_u *UpstreamDailyStatUpdate) AddBalanceUsd(v float64) *UpstreamDailyStatUpdate {
	_u.mutation.AddBalanceUsd(v)
	return _u
}

// ClearBalanceUsd clears the value of the "balance_usd" field.
func (_u *UpstreamDailyStatUpdate) ClearBalanceUsd() *UpstreamDailyStatUpdate {
	_u.mutation.ClearBalanceUsd()
	return _u
}

// SetTokens sets the "tokens" field.
func (_u *UpstreamDailyStatUpdate) SetTokens(v int64) *UpstreamDailyStatUpdate {
	_u.mutation.ResetTokens()
	_u.mutation.SetTokens(v)
	return _u
}

// SetNillableTokens sets the "tokens" field if the given value is not nil.
func (_u *UpstreamDailyStatUpdate) SetNillableTokens(v *int64) *UpstreamDailyStatUpdate {
	if v != nil {
		_u.SetTokens(*v)
	}
	return _u
}

// AddTokens adds value to the "tokens" field.
func (_u *UpstreamDailyStatUpdate) AddTokens(v int64) *UpstreamDailyStatUpdate {
	_u.mutation.AddTokens(v)
	return _u
}

// SetCostUsd sets the "cost_usd" field.
func (_u *UpstreamDailyStatUpdate) SetCostUsd(v float64) *UpstreamDailyStatUpdate {
	_u.mutation.ResetCostUsd()
	_u.mutation.SetCostUsd(v)
	return _u
}

// SetNillableCostUsd sets the "cost_usd" field if the given value is not nil.
func (_u *UpstreamDailyStatUpdate) SetNillableCostUsd(v *float64) *UpstreamDailyStatUpdate {
	if v != nil {
		_u.SetCostUsd(*v)
	}
	return _u
}

// AddCostUsd adds value to the "cost_usd" field.
func (_u *UpstreamDailyStatUpdate) AddCostUsd(v float64) *UpstreamDailyStatUpdate {
	_u.mutation.AddCostUsd(v)
	return _u
}

// SetCostBasisVersion sets the "cost_basis_version" field.
func (_u *UpstreamDailyStatUpdate) SetCostBasisVersion(v int) *UpstreamDailyStatUpdate {
	_u.mutation.ResetCostBasisVersion()
	_u.mutation.SetCostBasisVersion(v)
	return _u
}

// SetNillableCostBasisVersion sets the "cost_basis_version" field if the given value is not nil.
func (_u *UpstreamDailyStatUpdate) SetNillableCostBasisVersion(v *int) *UpstreamDailyStatUpdate {
	if v != nil {
		_u.SetCostBasisVersion(*v)
	}
	return _u
}

// AddCostBasisVersion adds value to the "cost_basis_version" field.
func (_u *UpstreamDailyStatUpdate) AddCostBasisVersion(v int) *UpstreamDailyStatUpdate {
	_u.mutation.AddCostBasisVersion(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *UpstreamDailyStatUpdate) SetCreatedAt(v time.Time) *UpstreamDailyStatUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *UpstreamDailyStatUpdate) SetNillableCreatedAt(v *time.Time) *UpstreamDailyStatUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UpstreamDailyStatUpdate) SetUpdatedAt(v time.Time) *UpstreamDailyStatUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSite sets the "site" edge to the UpstreamSite entity.
func (_u *UpstreamDailyStatUpdate) SetSite(v *UpstreamSite) *UpstreamDailyStatUpdate {
	return _u.SetSiteID(v.ID)
}

// Mutation returns the UpstreamDailyStatMutation object of the builder.
func (_u *UpstreamDailyStatUpdate) Mutation() *UpstreamDailyStatMutation {
	return _u.mutation
}

// ClearSite clears the "site" edge to the UpstreamSite entity.
func (_u *UpstreamDailyStatUpdate) ClearSite() *UpstreamDailyStatUpdate {
	_u.mutation.ClearSite()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UpstreamDailyStatUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UpstreamDailyStatUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UpstreamDailyStatUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UpstreamDailyStatUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UpstreamDailyStatUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := upstreamdailystat.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UpstreamDailyStatUpdate) check() error {
	if _u.mutation.SiteCleared() && len(_u.mutation.SiteIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UpstreamDailyStat.site"`)
	}
	return nil
}

func (_u *UpstreamDailyStatUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(upstreamdailystat.Table, upstreamdailystat.Columns, sqlgraph.NewFieldSpec(upstreamdailystat.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UsageDate(); ok {
		_spec.SetField(upstreamdailystat.FieldUsageDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.BalanceUsd(); ok {
		_spec.SetField(upstreamdailystat.FieldBalanceUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceUsd(); ok {
		_spec.AddField(upstreamdailystat.FieldBalanceUsd, field.TypeFloat64, value)
	}
	if _u.mutation.BalanceUsdCleared() {
		_spec.ClearField(upstreamdailystat.FieldBalanceUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Tokens(); ok {
		_spec.SetField(upstreamdailystat.FieldTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTokens(); ok {
		_spec.AddField(upstreamdailystat.FieldTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CostUsd(); ok {
		_spec.SetField(upstreamdailystat.FieldCostUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCostUsd(); ok {
		_spec.AddField(upstreamdailystat.FieldCostUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CostBasisVersion(); ok {
		_spec.SetField(upstreamdailystat.FieldCostBasisVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCostBasisVersion(); ok {
		_spec.AddField(upstreamdailystat.FieldCostBasisVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(upstreamdailystat.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(upstreamdailystat.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.SiteCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   upstreamdailystat.SiteTable,
			Columns: []string{upstreamdailystat.SiteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamsite.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SiteIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   upstreamdailystat.SiteTable,
			Columns: []string{upstreamdailystat.SiteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamsite.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upstreamdailystat.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UpstreamDailyStatUpdateOne is the builder for updating a single UpstreamDailyStat entity.
type UpstreamDailyStatUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UpstreamDailyStatMutation
}

// SetSiteID sets the "site_id" field.
func (_u *UpstreamDailyStatUpdateOne) SetSiteID(v int64) *UpstreamDailyStatUpdateOne {
	_u.mutation.SetSiteID(v)
	return _u
}

// SetNillableSiteID sets the "site_id" field if the given value is not nil.
func (_u *UpstreamDailyStatUpdateOne) SetNillableSiteID(v *int64) *UpstreamDailyStatUpdateOne {
	if v != nil {
		_u.SetSiteID(*v)
	}
	return _u
}

// SetUsageDate sets the "usage_date" field.
func (_u *UpstreamDailyStatUpdateOne) SetUsageDate(v time.Time) *UpstreamDailyStatUpdateOne {
	_u.mutation.SetUsageDate(v)
	return _u
}

// SetNillableUsageDate sets the "usage_date" field if the given value is not nil.
func (_u *UpstreamDailyStatUpdateOne) SetNillableUsageDate(v *time.Time) *UpstreamDailyStatUpdateOne {
	if v != nil {
		_u.SetUsageDate(*v)
	}
	return _u
}

// SetBalanceUsd sets the "balance_usd" field.
func (_u *UpstreamDailyStatUpdateOne) SetBalanceUsd(v float64) *UpstreamDailyStatUpdateOne {
	_u.mutation.ResetBalanceUsd()
	_u.mutation.SetBalanceUsd(v)
	return _u
}

// SetNillableBalanceUsd sets the "balance_usd" field if the given value is not nil.
func (_u *UpstreamDailyStatUpdateOne) SetNillableBalanceUsd(v *float64) *UpstreamDailyStatUpdateOne {
	if v != nil {
		_u.SetBalanceUsd(*v)
	}
	return _u
}

// AddBalanceUsd adds value to the "balance_usd" field.
func (_u *UpstreamDailyStatUpdateOne) AddBalanceUsd(v float64) *UpstreamDailyStatUpdateOne {
	_u.mutation.AddBalanceUsd(v)
	return _u
}

// ClearBalanceUsd clears the value of the "balance_usd" field.
func (_u *UpstreamDailyStatUpdateOne) ClearBalanceUsd() *UpstreamDailyStatUpdateOne {
	_u.mutation.ClearBalanceUsd()
	return _u
}

// SetTokens sets the "tokens" field.
func (_u *UpstreamDailyStatUpdateOne) SetTokens(v int64) *UpstreamDailyStatUpdateOne {
	_u.mutation.ResetTokens()
	_u.mutation.SetTokens(v)
	return _u
}

// SetNillableTokens sets the "tokens" field if the given value is not nil.
func (_u *UpstreamDailyStatUpdateOne) SetNillableTokens(v *int64) *UpstreamDailyStatUpdateOne {
	if v != nil {
		_u.SetTokens(*v)
	}
	return _u
}

// AddTokens adds value to the "tokens" field.
func (_u *UpstreamDailyStatUpdateOne) AddTokens(v int64) *UpstreamDailyStatUpdateOne {
	_u.mutation.AddTokens(v)
	return _u
}

// SetCostUsd sets the "cost_usd" field.
func (_u *UpstreamDailyStatUpdateOne) SetCostUsd(v float64) *UpstreamDailyStatUpdateOne {
	_u.mutation.ResetCostUsd()
	_u.mutation.SetCostUsd(v)
	return _u
}

// SetNillableCostUsd sets the "cost_usd" field if the given value is not nil.
func (_u *UpstreamDailyStatUpdateOne) SetNillableCostUsd(v *float64) *UpstreamDailyStatUpdateOne {
	if v != nil {
		_u.SetCostUsd(*v)
	}
	return _u
}

// AddCostUsd adds value to the "cost_usd" field.
func (_u *UpstreamDailyStatUpdateOne) AddCostUsd(v float64) *UpstreamDailyStatUpdateOne {
	_u.mutation.AddCostUsd(v)
	return _u
}

// SetCostBasisVersion sets the "cost_basis_version" field.
func (_u *UpstreamDailyStatUpdateOne) SetCostBasisVersion(v int) *UpstreamDailyStatUpdateOne {
	_u.mutation.ResetCostBasisVersion()
	_u.mutation.SetCostBasisVersion(v)
	return _u
}

// SetNillableCostBasisVersion sets the "cost_basis_version" field if the given value is not nil.
func (_u *UpstreamDailyStatUpdateOne) SetNillableCostBasisVersion(v *int) *UpstreamDailyStatUpdateOne {
	if v != nil {
		_u.SetCostBasisVersion(*v)
	}
	return _u
}

// AddCostBasisVersion adds value to the "cost_basis_version" field.
func (_u *UpstreamDailyStatUpdateOne) AddCostBasisVersion(v int) *UpstreamDailyStatUpdateOne {
	_u.mutation.AddCostBasisVersion(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *UpstreamDailyStatUpdateOne) SetCreatedAt(v time.Time) *UpstreamDailyStatUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *UpstreamDailyStatUpdateOne) SetNillableCreatedAt(v *time.Time) *UpstreamDailyStatUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UpstreamDailyStatUpdateOne) SetUpdatedAt(v time.Time) *UpstreamDailyStatUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSite sets the "site" edge to the UpstreamSite entity.
func (_u *UpstreamDailyStatUpdateOne) SetSite(v *UpstreamSite) *UpstreamDailyStatUpdateOne {
	return _u.SetSiteID(v.ID)
}

// Mutation returns the UpstreamDailyStatMutation object of the builder.
func (_u *UpstreamDailyStatUpdateOne) Mutation() *UpstreamDailyStatMutation {
	return _u.mutation
}

// ClearSite clears the "site" edge to the UpstreamSite entity.
func (_u *UpstreamDailyStatUpdateOne) ClearSite() *UpstreamDailyStatUpdateOne {
	_u.mutation.ClearSite()
	return _u
}

// Where appends a list predicates to the UpstreamDailyStatUpdate builder.
func (_u *UpstreamDailyStatUpdateOne) Where(ps ...predicate.UpstreamDailyStat) *UpstreamDailyStatUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UpstreamDailyStatUpdateOne) Select(field string, fields ...string) *UpstreamDailyStatUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UpstreamDailyStat entity.
func (_u *UpstreamDailyStatUpdateOne) Save(ctx context.Context) (*UpstreamDailyStat, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UpstreamDailyStatUpdateOne) SaveX(ctx context.Context) *UpstreamDailyStat {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UpstreamDailyStatUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UpstreamDailyStatUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UpstreamDailyStatUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := upstreamdailystat.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UpstreamDailyStatUpdateOne) check() error {
	if _u.mutation.SiteCleared() && len(_u.mutation.SiteIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UpstreamDailyStat.site"`)
	}
	return nil
}

func (_u *UpstreamDailyStatUpdateOne) sqlSave(ctx context.Context) (_node *UpstreamDailyStat, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(upstreamdailystat.Table, upstreamdailystat.Columns, sqlgraph.NewFieldSpec(upstreamdailystat.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UpstreamDailyStat.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, upstreamdailystat.FieldID)
		for _, f := range fields {
			if !upstreamdailystat.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != upstreamdailystat.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UsageDate(); ok {
		_spec.SetField(upstreamdailystat.FieldUsageDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.BalanceUsd(); ok {
		_spec.SetField(upstreamdailystat.FieldBalanceUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceUsd(); ok {
		_spec.AddField(upstreamdailystat.FieldBalanceUsd, field.TypeFloat64, value)
	}
	if _u.mutation.BalanceUsdCleared() {
		_spec.ClearField(upstreamdailystat.FieldBalanceUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Tokens(); ok {
		_spec.SetField(upstreamdailystat.FieldTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTokens(); ok {
		_spec.AddField(upstreamdailystat.FieldTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CostUsd(); ok {
		_spec.SetField(upstreamdailystat.FieldCostUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCostUsd(); ok {
		_spec.AddField(upstreamdailystat.FieldCostUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CostBasisVersion(); ok {
		_spec.SetField(upstreamdailystat.FieldCostBasisVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCostBasisVersion(); ok {
		_spec.AddField(upstreamdailystat.FieldCostBasisVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(upstreamdailystat.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(upstreamdailystat.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.SiteCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   upstreamdailystat.SiteTable,
			Columns: []string{upstreamdailystat.SiteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamsite.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SiteIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   upstreamdailystat.SiteTable,
			Columns: []string{upstreamdailystat.SiteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamsite.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UpstreamDailyStat{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upstreamdailystat.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
