// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/upstreamdailystat"
	"github.com/Wei-Shaw/sub2api/ent/upstreamsite"
)

// UpstreamDailyStat is the model entity for the UpstreamDailyStat schema.
type UpstreamDailyStat struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// SiteID holds the value of the "site_id" field.
	SiteID int64 `json:"site_id,omitempty"`
	// UsageDate holds the value of the "usage_date" field.
	UsageDate time.Time `json:"usage_date,omitempty"`
	// BalanceUsd holds the value of the "balance_usd" field.
	BalanceUsd *float64 `json:"balance_usd,omitempty"`
	// Tokens holds the value of the "tokens" field.
	Tokens int64 `json:"tokens,omitempty"`
	// CostUsd holds the value of the "cost_usd" field.
	CostUsd float64 `json:"cost_usd,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UpstreamDailyStatQuery when eager-loading is set.
	Edges        UpstreamDailyStatEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UpstreamDailyStatEdges holds the relations/edges for other nodes in the graph.
type UpstreamDailyStatEdges struct {
	// Site holds the value of the site edge.
	Site *UpstreamSite `json:"site,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SiteOrErr returns the Site value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UpstreamDailyStatEdges) SiteOrErr() (*UpstreamSite, error) {
	if e.Site != nil {
		return e.Site, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: upstreamsite.Label}
	}
	return nil, &NotLoadedError{edge: "site"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UpstreamDailyStat) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case upstreamdailystat.FieldBalanceUsd, upstreamdailystat.FieldCostUsd:
			values[i] = new(sql.NullFloat64)
		case upstreamdailystat.FieldID, upstreamdailystat.FieldSiteID, upstreamdailystat.FieldTokens:
			values[i] = new(sql.NullInt64)
		case upstreamdailystat.FieldUsageDate, upstreamdailystat.FieldCreatedAt, upstreamdailystat.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UpstreamDailyStat fields.
func (_m *UpstreamDailyStat) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case upstreamdailystat.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case upstreamdailystat.FieldSiteID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field site_id", values[i])
			} else if value.Valid {
				_m.SiteID = value.Int64
			}
		case upstreamdailystat.FieldUsageDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field usage_date", values[i])
			} else if value.Valid {
				_m.UsageDate = value.Time
			}
		case upstreamdailystat.FieldBalanceUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field balance_usd", values[i])
			} else if value.Valid {
				_m.BalanceUsd = new(float64)
				*_m.BalanceUsd = value.Float64
			}
		case upstreamdailystat.FieldTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tokens", values[i])
			} else if value.Valid {
				_m.Tokens = value.Int64
			}
		case upstreamdailystat.FieldCostUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cost_usd", values[i])
			} else if value.Valid {
				_m.CostUsd = value.Float64
			}
		case upstreamdailystat.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case upstreamdailystat.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UpstreamDailyStat.
// This includes values selected through modifiers, order, etc.
func (_m *UpstreamDailyStat) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySite queries the "site" edge of the UpstreamDailyStat entity.
func (_m *UpstreamDailyStat) QuerySite() *UpstreamSiteQuery {
	return NewUpstreamDailyStatClient(_m.config).QuerySite(_m)
}

// Update returns a builder for updating this UpstreamDailyStat.
// Note that you need to call UpstreamDailyStat.Unwrap() before calling this method if this UpstreamDailyStat
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UpstreamDailyStat) Update() *UpstreamDailyStatUpdateOne {
	return NewUpstreamDailyStatClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UpstreamDailyStat entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UpstreamDailyStat) Unwrap() *UpstreamDailyStat {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UpstreamDailyStat is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UpstreamDailyStat) String() string {
	var builder strings.Builder
	builder.WriteString("UpstreamDailyStat(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("site_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SiteID))
	builder.WriteString(", ")
	builder.WriteString("usage_date=")
	builder.WriteString(_m.UsageDate.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.BalanceUsd; v != nil {
		builder.WriteString("balance_usd=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.Tokens))
	builder.WriteString(", ")
	builder.WriteString("cost_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.CostUsd))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UpstreamDailyStats is a parsable slice of UpstreamDailyStat.
type UpstreamDailyStats []*UpstreamDailyStat
