// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/upstreamgroupmultiplierhistory"
	"github.com/Wei-Shaw/sub2api/ent/upstreamsite"
)

// UpstreamGroupMultiplierHistory is the model entity for the UpstreamGroupMultiplierHistory schema.
type UpstreamGroupMultiplierHistory struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// SiteID holds the value of the "site_id" field.
	SiteID int64 `json:"site_id,omitempty"`
	// RemoteID holds the value of the "remote_id" field.
	RemoteID string `json:"remote_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Platform holds the value of the "platform" field.
	Platform string `json:"platform,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Multiplier holds the value of the "multiplier" field.
	Multiplier *float64 `json:"multiplier,omitempty"`
	// RecordedAt holds the value of the "recorded_at" field.
	RecordedAt time.Time `json:"recorded_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UpstreamGroupMultiplierHistoryQuery when eager-loading is set.
	Edges        UpstreamGroupMultiplierHistoryEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UpstreamGroupMultiplierHistoryEdges holds the relations/edges for other nodes in the graph.
type UpstreamGroupMultiplierHistoryEdges struct {
	// Site holds the value of the site edge.
	Site *UpstreamSite `json:"site,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SiteOrErr returns the Site value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UpstreamGroupMultiplierHistoryEdges) SiteOrErr() (*UpstreamSite, error) {
	if e.Site != nil {
		return e.Site, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: upstreamsite.Label}
	}
	return nil, &NotLoadedError{edge: "site"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UpstreamGroupMultiplierHistory) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case upstreamgroupmultiplierhistory.FieldMultiplier:
			values[i] = new(sql.NullFloat64)
		case upstreamgroupmultiplierhistory.FieldID, upstreamgroupmultiplierhistory.FieldSiteID:
			values[i] = new(sql.NullInt64)
		case upstreamgroupmultiplierhistory.FieldRemoteID, upstreamgroupmultiplierhistory.FieldName, upstreamgroupmultiplierhistory.FieldPlatform, upstreamgroupmultiplierhistory.FieldDescription:
			values[i] = new(sql.NullString)
		case upstreamgroupmultiplierhistory.FieldRecordedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UpstreamGroupMultiplierHistory fields.
func (_m *UpstreamGroupMultiplierHistory) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case upstreamgroupmultiplierhistory.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case upstreamgroupmultiplierhistory.FieldSiteID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field site_id", values[i])
			} else if value.Valid {
				_m.SiteID = value.Int64
			}
		case upstreamgroupmultiplierhistory.FieldRemoteID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field remote_id", values[i])
			} else if value.Valid {
				_m.RemoteID = value.String
			}
		case upstreamgroupmultiplierhistory.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case upstreamgroupmultiplierhistory.FieldPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform", values[i])
			} else if value.Valid {
				_m.Platform = value.String
			}
		case upstreamgroupmultiplierhistory.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case upstreamgroupmultiplierhistory.FieldMultiplier:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field multiplier", values[i])
			} else if value.Valid {
				_m.Multiplier = new(float64)
				*_m.Multiplier = value.Float64
			}
		case upstreamgroupmultiplierhistory.FieldRecordedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field recorded_at", values[i])
			} else if value.Valid {
				_m.RecordedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UpstreamGroupMultiplierHistory.
// This includes values selected through modifiers, order, etc.
func (_m *UpstreamGroupMultiplierHistory) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySite queries the "site" edge of the UpstreamGroupMultiplierHistory entity.
func (_m *UpstreamGroupMultiplierHistory) QuerySite() *UpstreamSiteQuery {
	return NewUpstreamGroupMultiplierHistoryClient(_m.config).QuerySite(_m)
}

// Update returns a builder for updating this UpstreamGroupMultiplierHistory.
// Note that you need to call UpstreamGroupMultiplierHistory.Unwrap() before calling this method if this UpstreamGroupMultiplierHistory
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UpstreamGroupMultiplierHistory) Update() *UpstreamGroupMultiplierHistoryUpdateOne {
	return NewUpstreamGroupMultiplierHistoryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UpstreamGroupMultiplierHistory entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UpstreamGroupMultiplierHistory) Unwrap() *UpstreamGroupMultiplierHistory {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UpstreamGroupMultiplierHistory is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UpstreamGroupMultiplierHistory) String() string {
	var builder strings.Builder
	builder.WriteString("UpstreamGroupMultiplierHistory(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("site_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SiteID))
	builder.WriteString(", ")
	builder.WriteString("remote_id=")
	builder.WriteString(_m.RemoteID)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("platform=")
	builder.WriteString(_m.Platform)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	if v := _m.Multiplier; v != nil {
		builder.WriteString("multiplier=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("recorded_at=")
	builder.WriteString(_m.RecordedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UpstreamGroupMultiplierHistories is a parsable slice of UpstreamGroupMultiplierHistory.
type UpstreamGroupMultiplierHistories []*UpstreamGroupMultiplierHistory
