// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/upstreamgroupaccountbinding"
)

// UpstreamGroupAccountBindingDelete is the builder for deleting a UpstreamGroupAccountBinding entity.
type UpstreamGroupAccountBindingDelete struct {
	config
	hooks    []Hook
	mutation *UpstreamGroupAccountBindingMutation
}

// Where appends a list predicates to the UpstreamGroupAccountBindingDelete builder.
func (_d *UpstreamGroupAccountBindingDelete) Where(ps ...predicate.UpstreamGroupAccountBinding) *UpstreamGroupAccountBindingDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *UpstreamGroupAccountBindingDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UpstreamGroupAccountBindingDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *UpstreamGroupAccountBindingDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(upstreamgroupaccountbinding.Table, sqlgraph.NewFieldSpec(upstreamgroupaccountbinding.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// UpstreamGroupAccountBindingDeleteOne is the builder for deleting a single UpstreamGroupAccountBinding entity.
type UpstreamGroupAccountBindingDeleteOne struct {
	_d *UpstreamGroupAccountBindingDelete
}

// Where appends a list predicates to the UpstreamGroupAccountBindingDelete builder.
func (_d *UpstreamGroupAccountBindingDeleteOne) Where(ps ...predicate.UpstreamGroupAccountBinding) *UpstreamGroupAccountBindingDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *UpstreamGroupAccountBindingDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{upstreamgroupaccountbinding.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UpstreamGroupAccountBindingDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
