// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/upstreamgroupmultiplierhistory"
	"github.com/Wei-Shaw/sub2api/ent/upstreamsite"
)

// UpstreamGroupMultiplierHistoryUpdate is the builder for updating UpstreamGroupMultiplierHistory entities.
type UpstreamGroupMultiplierHistoryUpdate struct {
	config
	hooks    []Hook
	mutation *UpstreamGroupMultiplierHistoryMutation
}

// Where appends a list predicates to the UpstreamGroupMultiplierHistoryUpdate builder.
func (_u *UpstreamGroupMultiplierHistoryUpdate) Where(ps ...predicate.UpstreamGroupMultiplierHistory) *UpstreamGroupMultiplierHistoryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSiteID sets the "site_id" field.
func (_u *UpstreamGroupMultiplierHistoryUpdate) SetSiteID(v int64) *UpstreamGroupMultiplierHistoryUpdate {
	_u.mutation.SetSiteID(v)
	return _u
}

// SetNillableSiteID sets the "site_id" field if the given value is not nil.
func (_u *UpstreamGroupMultiplierHistoryUpdate) SetNillableSiteID(v *int64) *UpstreamGroupMultiplierHistoryUpdate {
	if v != nil {
		_u.SetSiteID(*v)
	}
	return _u
}

// SetRemoteID sets the "remote_id" field.
func (_u *UpstreamGroupMultiplierHistoryUpdate) SetRemoteID(v string) *UpstreamGroupMultiplierHistoryUpdate {
	_u.mutation.SetRemoteID(v)
	return _u
}

// SetNillableRemoteID sets the "remote_id" field if the given value is not nil.
func (_u *UpstreamGroupMultiplierHistoryUpdate) SetNillableRemoteID(v *string) *UpstreamGroupMultiplierHistoryUpdate {
	if v != nil {
		_u.SetRemoteID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *UpstreamGroupMultiplierHistoryUpdate) SetName(v string) *UpstreamGroupMultiplierHistoryUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UpstreamGroupMultiplierHistoryUpdate) SetNillableName(v *string) *UpstreamGroupMultiplierHistoryUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *UpstreamGroupMultiplierHistoryUpdate) SetPlatform(v string) *UpstreamGroupMultiplierHistoryUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *UpstreamGroupMultiplierHistoryUpdate) SetNillablePlatform(v *string) *UpstreamGroupMultiplierHistoryUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *UpstreamGroupMultiplierHistoryUpdate) SetDescription(v string) *UpstreamGroupMultiplierHistoryUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *UpstreamGroupMultiplierHistoryUpdate) SetNillableDescription(v *string) *UpstreamGroupMultiplierHistoryUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetMultiplier sets the "multiplier" field.
func (_u *UpstreamGroupMultiplierHistoryUpdate) SetMultiplier(v float64) *UpstreamGroupMultiplierHistoryUpdate {
	_u.mutation.ResetMultiplier()
	_u.mutation.SetMultiplier(v)
	return _u
}

// SetNillableMultiplier sets the "multiplier" field if the given value is not nil.
func (_u *UpstreamGroupMultiplierHistoryUpdate) SetNillableMultiplier(v *float64) *UpstreamGroupMultiplierHistoryUpdate {
	if v != nil {
		_u.SetMultiplier(*v)
	}
	return _u
}

// AddMultiplier adds value to the "multiplier" field.
func (_u *UpstreamGroupMultiplierHistoryUpdate) AddMultiplier(v float64) *UpstreamGroupMultiplierHistoryUpdate {
	_u.mutation.AddMultiplier(v)
	return _u
}

// ClearMultiplier clears the value of the "multiplier" field.
func (_u *UpstreamGroupMultiplierHistoryUpdate) ClearMultiplier() *UpstreamGroupMultiplierHistoryUpdate {
	_u.mutation.ClearMultiplier()
	return _u
}

// SetRecordedAt sets the "recorded_at" field.
func (_u *UpstreamGroupMultiplierHistoryUpdate) SetRecordedAt(v time.Time) *UpstreamGroupMultiplierHistoryUpdate {
	_u.mutation.SetRecordedAt(v)
	return _u
}

// SetNillableRecordedAt sets the "recorded_at" field if the given value is not nil.
func (_u *UpstreamGroupMultiplierHistoryUpdate) SetNillableRecordedAt(v *time.Time) *UpstreamGroupMultiplierHistoryUpdate {
	if v != nil {
		_u.SetRecordedAt(*v)
	}
	return _u
}

// SetSite sets the "site" edge to the UpstreamSite entity.
func (_u *UpstreamGroupMultiplierHistoryUpdate) SetSite(v *UpstreamSite) *UpstreamGroupMultiplierHistoryUpdate {
	return _u.SetSiteID(v.ID)
}

// Mutation returns the UpstreamGroupMultiplierHistoryMutation object of the builder.
func (_u *UpstreamGroupMultiplierHistoryUpdate) Mutation() *UpstreamGroupMultiplierHistoryMutation {
	return _u.mutation
}

// ClearSite clears the "site" edge to the UpstreamSite entity.
func (_u *UpstreamGroupMultiplierHistoryUpdate) ClearSite() *UpstreamGroupMultiplierHistoryUpdate {
	_u.mutation.ClearSite()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UpstreamGroupMultiplierHistoryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UpstreamGroupMultiplierHistoryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UpstreamGroupMultiplierHistoryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UpstreamGroupMultiplierHistoryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UpstreamGroupMultiplierHistoryUpdate) check() error {
	if v, ok := _u.mutation.RemoteID(); ok {
		if err := upstreamgroupmultiplierhistory.RemoteIDValidator(v); err != nil {
			return &ValidationError{Name: "remote_id", err: fmt.Errorf(`ent: validator failed for field "UpstreamGroupMultiplierHistory.remote_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := upstreamgroupmultiplierhistory.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "UpstreamGroupMultiplierHistory.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := upstreamgroupmultiplierhistory.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "UpstreamGroupMultiplierHistory.platform": %w`, err)}
		}
	}
	if _u.mutation.SiteCleared() && len(_u.mutation.SiteIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UpstreamGroupMultiplierHistory.site"`)
	}
	return nil
}

func (_u *UpstreamGroupMultiplierHistoryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(upstreamgroupmultiplierhistory.Table, upstreamgroupmultiplierhistory.Columns, sqlgraph.NewFieldSpec(upstreamgroupmultiplierhistory.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RemoteID(); ok {
		_spec.SetField(upstreamgroupmultiplierhistory.FieldRemoteID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(upstreamgroupmultiplierhistory.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(upstreamgroupmultiplierhistory.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(upstreamgroupmultiplierhistory.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Multiplier(); ok {
		_spec.SetField(upstreamgroupmultiplierhistory.FieldMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMultiplier(); ok {
		_spec.AddField(upstreamgroupmultiplierhistory.FieldMultiplier, field.TypeFloat64, value)
	}
	if _u.mutation.MultiplierCleared() {
		_spec.ClearField(upstreamgroupmultiplierhistory.FieldMultiplier, field.TypeFloat64)
	}
	if value, ok := _u.mutation.RecordedAt(); ok {
		_spec.SetField(upstreamgroupmultiplierhistory.FieldRecordedAt, field.TypeTime, value)
	}
	if _u.mutation.SiteCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   upstreamgroupmultiplierhistory.SiteTable,
			Columns: []string{upstreamgroupmultiplierhistory.SiteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamsite.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SiteIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   upstreamgroupmultiplierhistory.SiteTable,
			Columns: []string{upstreamgroupmultiplierhistory.SiteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamsite.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upstreamgroupmultiplierhistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UpstreamGroupMultiplierHistoryUpdateOne is the builder for updating a single UpstreamGroupMultiplierHistory entity.
type UpstreamGroupMultiplierHistoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UpstreamGroupMultiplierHistoryMutation
}

// SetSiteID sets the "site_id" field.
func (_u *UpstreamGroupMultiplierHistoryUpdateOne) SetSiteID(v int64) *UpstreamGroupMultiplierHistoryUpdateOne {
	_u.mutation.SetSiteID(v)
	return _u
}

// SetNillableSiteID sets the "site_id" field if the given value is not nil.
func (_u *UpstreamGroupMultiplierHistoryUpdateOne) SetNillableSiteID(v *int64) *UpstreamGroupMultiplierHistoryUpdateOne {
	if v != nil {
		_u.SetSiteID(*v)
	}
	return _u
}

// SetRemoteID sets the "remote_id" field.
func (_u *UpstreamGroupMultiplierHistoryUpdateOne) SetRemoteID(v string) *UpstreamGroupMultiplierHistoryUpdateOne {
	_u.mutation.SetRemoteID(v)
	return _u
}

// SetNillableRemoteID sets the "remote_id" field if the given value is not nil.
func (_u *UpstreamGroupMultiplierHistoryUpdateOne) SetNillableRemoteID(v *string) *UpstreamGroupMultiplierHistoryUpdateOne {
	if v != nil {
		_u.SetRemoteID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *UpstreamGroupMultiplierHistoryUpdateOne) SetName(v string) *UpstreamGroupMultiplierHistoryUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UpstreamGroupMultiplierHistoryUpdateOne) SetNillableName(v *string) *UpstreamGroupMultiplierHistoryUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *UpstreamGroupMultiplierHistoryUpdateOne) SetPlatform(v string) *UpstreamGroupMultiplierHistoryUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *UpstreamGroupMultiplierHistoryUpdateOne) SetNillablePlatform(v *string) *UpstreamGroupMultiplierHistoryUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *UpstreamGroupMultiplierHistoryUpdateOne) SetDescription(v string) *UpstreamGroupMultiplierHistoryUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *UpstreamGroupMultiplierHistoryUpdateOne) SetNillableDescription(v *string) *UpstreamGroupMultiplierHistoryUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetMultiplier sets the "multiplier" field.
func (_u *UpstreamGroupMultiplierHistoryUpdateOne) SetMultiplier(v float64) *UpstreamGroupMultiplierHistoryUpdateOne {
	_u.mutation.ResetMultiplier()
	_u.mutation.SetMultiplier(v)
	return _u
}

// SetNillableMultiplier sets the "multiplier" field if the given value is not nil.
func (_u *UpstreamGroupMultiplierHistoryUpdateOne) SetNillableMultiplier(v *float64) *UpstreamGroupMultiplierHistoryUpdateOne {
	if v != nil {
		_u.SetMultiplier(*v)
	}
	return _u
}

// AddMultiplier adds value to the "multiplier" field.
func (_u *UpstreamGroupMultiplierHistoryUpdateOne) AddMultiplier(v float64) *UpstreamGroupMultiplierHistoryUpdateOne {
	_u.mutation.AddMultiplier(v)
	return _u
}

// ClearMultiplier clears the value of the "multiplier" field.
func (_u *UpstreamGroupMultiplierHistoryUpdateOne) ClearMultiplier() *UpstreamGroupMultiplierHistoryUpdateOne {
	_u.mutation.ClearMultiplier()
	return _u
}

// SetRecordedAt sets the "recorded_at" field.
func (_u *UpstreamGroupMultiplierHistoryUpdateOne) SetRecordedAt(v time.Time) *UpstreamGroupMultiplierHistoryUpdateOne {
	_u.mutation.SetRecordedAt(v)
	return _u
}

// SetNillableRecordedAt sets the "recorded_at" field if the given value is not nil.
func (_u *UpstreamGroupMultiplierHistoryUpdateOne) SetNillableRecordedAt(v *time.Time) *UpstreamGroupMultiplierHistoryUpdateOne {
	if v != nil {
		_u.SetRecordedAt(*v)
	}
	return _u
}

// SetSite sets the "site" edge to the UpstreamSite entity.
func (_u *UpstreamGroupMultiplierHistoryUpdateOne) SetSite(v *UpstreamSite) *UpstreamGroupMultiplierHistoryUpdateOne {
	return _u.SetSiteID(v.ID)
}

// Mutation returns the UpstreamGroupMultiplierHistoryMutation object of the builder.
func (_u *UpstreamGroupMultiplierHistoryUpdateOne) Mutation() *UpstreamGroupMultiplierHistoryMutation {
	return _u.mutation
}

// ClearSite clears the "site" edge to the UpstreamSite entity.
func (_u *UpstreamGroupMultiplierHistoryUpdateOne) ClearSite() *UpstreamGroupMultiplierHistoryUpdateOne {
	_u.mutation.ClearSite()
	return _u
}

// Where appends a list predicates to the UpstreamGroupMultiplierHistoryUpdate builder.
func (_u *UpstreamGroupMultiplierHistoryUpdateOne) Where(ps ...predicate.UpstreamGroupMultiplierHistory) *UpstreamGroupMultiplierHistoryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UpstreamGroupMultiplierHistoryUpdateOne) Select(field string, fields ...string) *UpstreamGroupMultiplierHistoryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UpstreamGroupMultiplierHistory entity.
func (_u *UpstreamGroupMultiplierHistoryUpdateOne) Save(ctx context.Context) (*UpstreamGroupMultiplierHistory, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UpstreamGroupMultiplierHistoryUpdateOne) SaveX(ctx context.Context) *UpstreamGroupMultiplierHistory {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UpstreamGroupMultiplierHistoryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UpstreamGroupMultiplierHistoryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UpstreamGroupMultiplierHistoryUpdateOne) check() error {
	if v, ok := _u.mutation.RemoteID(); ok {
		if err := upstreamgroupmultiplierhistory.RemoteIDValidator(v); err != nil {
			return &ValidationError{Name: "remote_id", err: fmt.Errorf(`ent: validator failed for field "UpstreamGroupMultiplierHistory.remote_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := upstreamgroupmultiplierhistory.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "UpstreamGroupMultiplierHistory.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := upstreamgroupmultiplierhistory.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "UpstreamGroupMultiplierHistory.platform": %w`, err)}
		}
	}
	if _u.mutation.SiteCleared() && len(_u.mutation.SiteIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UpstreamGroupMultiplierHistory.site"`)
	}
	return nil
}

func (_u *UpstreamGroupMultiplierHistoryUpdateOne) sqlSave(ctx context.Context) (_node *UpstreamGroupMultiplierHistory, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(upstreamgroupmultiplierhistory.Table, upstreamgroupmultiplierhistory.Columns, sqlgraph.NewFieldSpec(upstreamgroupmultiplierhistory.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UpstreamGroupMultiplierHistory.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, upstreamgroupmultiplierhistory.FieldID)
		for _, f := range fields {
			if !upstreamgroupmultiplierhistory.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != upstreamgroupmultiplierhistory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RemoteID(); ok {
		_spec.SetField(upstreamgroupmultiplierhistory.FieldRemoteID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(upstreamgroupmultiplierhistory.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(upstreamgroupmultiplierhistory.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(upstreamgroupmultiplierhistory.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Multiplier(); ok {
		_spec.SetField(upstreamgroupmultiplierhistory.FieldMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMultiplier(); ok {
		_spec.AddField(upstreamgroupmultiplierhistory.FieldMultiplier, field.TypeFloat64, value)
	}
	if _u.mutation.MultiplierCleared() {
		_spec.ClearField(upstreamgroupmultiplierhistory.FieldMultiplier, field.TypeFloat64)
	}
	if value, ok := _u.mutation.RecordedAt(); ok {
		_spec.SetField(upstreamgroupmultiplierhistory.FieldRecordedAt, field.TypeTime, value)
	}
	if _u.mutation.SiteCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   upstreamgroupmultiplierhistory.SiteTable,
			Columns: []string{upstreamgroupmultiplierhistory.SiteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamsite.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SiteIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   upstreamgroupmultiplierhistory.SiteTable,
			Columns: []string{upstreamgroupmultiplierhistory.SiteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamsite.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UpstreamGroupMultiplierHistory{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upstreamgroupmultiplierhistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
