// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/upstreamsite"
)

// UpstreamSite is the model entity for the UpstreamSite schema.
type UpstreamSite struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// BaseURL holds the value of the "base_url" field.
	BaseURL string `json:"base_url,omitempty"`
	// Platform holds the value of the "platform" field.
	Platform upstreamsite.Platform `json:"platform,omitempty"`
	// AuthMode holds the value of the "auth_mode" field.
	AuthMode upstreamsite.AuthMode `json:"auth_mode,omitempty"`
	// Account holds the value of the "account" field.
	Account string `json:"account,omitempty"`
	// CredentialEncrypted holds the value of the "credential_encrypted" field.
	CredentialEncrypted string `json:"-"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// Status holds the value of the "status" field.
	Status upstreamsite.Status `json:"status,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage *string `json:"error_message,omitempty"`
	// BalanceUsd holds the value of the "balance_usd" field.
	BalanceUsd *float64 `json:"balance_usd,omitempty"`
	// TodayTokens holds the value of the "today_tokens" field.
	TodayTokens int64 `json:"today_tokens,omitempty"`
	// TodayCostUsd holds the value of the "today_cost_usd" field.
	TodayCostUsd float64 `json:"today_cost_usd,omitempty"`
	// TotalTokens holds the value of the "total_tokens" field.
	TotalTokens int64 `json:"total_tokens,omitempty"`
	// TotalCostUsd holds the value of the "total_cost_usd" field.
	TotalCostUsd float64 `json:"total_cost_usd,omitempty"`
	// TrackingStartedAt holds the value of the "tracking_started_at" field.
	TrackingStartedAt time.Time `json:"tracking_started_at,omitempty"`
	// LastSyncedAt holds the value of the "last_synced_at" field.
	LastSyncedAt *time.Time `json:"last_synced_at,omitempty"`
	// NextSyncAt holds the value of the "next_sync_at" field.
	NextSyncAt *time.Time `json:"next_sync_at,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy int64 `json:"created_by,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UpstreamSiteQuery when eager-loading is set.
	Edges        UpstreamSiteEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UpstreamSiteEdges holds the relations/edges for other nodes in the graph.
type UpstreamSiteEdges struct {
	// Groups holds the value of the groups edge.
	Groups []*UpstreamGroup `json:"groups,omitempty"`
	// DailyStats holds the value of the daily_stats edge.
	DailyStats []*UpstreamDailyStat `json:"daily_stats,omitempty"`
	// GroupMultiplierHistory holds the value of the group_multiplier_history edge.
	GroupMultiplierHistory []*UpstreamGroupMultiplierHistory `json:"group_multiplier_history,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// GroupsOrErr returns the Groups value or an error if the edge
// was not loaded in eager-loading.
func (e UpstreamSiteEdges) GroupsOrErr() ([]*UpstreamGroup, error) {
	if e.loadedTypes[0] {
		return e.Groups, nil
	}
	return nil, &NotLoadedError{edge: "groups"}
}

// DailyStatsOrErr returns the DailyStats value or an error if the edge
// was not loaded in eager-loading.
func (e UpstreamSiteEdges) DailyStatsOrErr() ([]*UpstreamDailyStat, error) {
	if e.loadedTypes[1] {
		return e.DailyStats, nil
	}
	return nil, &NotLoadedError{edge: "daily_stats"}
}

// GroupMultiplierHistoryOrErr returns the GroupMultiplierHistory value or an error if the edge
// was not loaded in eager-loading.
func (e UpstreamSiteEdges) GroupMultiplierHistoryOrErr() ([]*UpstreamGroupMultiplierHistory, error) {
	if e.loadedTypes[2] {
		return e.GroupMultiplierHistory, nil
	}
	return nil, &NotLoadedError{edge: "group_multiplier_history"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UpstreamSite) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case upstreamsite.FieldEnabled:
			values[i] = new(sql.NullBool)
		case upstreamsite.FieldBalanceUsd, upstreamsite.FieldTodayCostUsd, upstreamsite.FieldTotalCostUsd:
			values[i] = new(sql.NullFloat64)
		case upstreamsite.FieldID, upstreamsite.FieldTodayTokens, upstreamsite.FieldTotalTokens, upstreamsite.FieldCreatedBy:
			values[i] = new(sql.NullInt64)
		case upstreamsite.FieldName, upstreamsite.FieldBaseURL, upstreamsite.FieldPlatform, upstreamsite.FieldAuthMode, upstreamsite.FieldAccount, upstreamsite.FieldCredentialEncrypted, upstreamsite.FieldStatus, upstreamsite.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case upstreamsite.FieldCreatedAt, upstreamsite.FieldUpdatedAt, upstreamsite.FieldTrackingStartedAt, upstreamsite.FieldLastSyncedAt, upstreamsite.FieldNextSyncAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UpstreamSite fields.
func (_m *UpstreamSite) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case upstreamsite.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case upstreamsite.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case upstreamsite.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case upstreamsite.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case upstreamsite.FieldBaseURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field base_url", values[i])
			} else if value.Valid {
				_m.BaseURL = value.String
			}
		case upstreamsite.FieldPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform", values[i])
			} else if value.Valid {
				_m.Platform = upstreamsite.Platform(value.String)
			}
		case upstreamsite.FieldAuthMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field auth_mode", values[i])
			} else if value.Valid {
				_m.AuthMode = upstreamsite.AuthMode(value.String)
			}
		case upstreamsite.FieldAccount:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field account", values[i])
			} else if value.Valid {
				_m.Account = value.String
			}
		case upstreamsite.FieldCredentialEncrypted:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field credential_encrypted", values[i])
			} else if value.Valid {
				_m.CredentialEncrypted = value.String
			}
		case upstreamsite.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case upstreamsite.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = upstreamsite.Status(value.String)
			}
		case upstreamsite.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = new(string)
				*_m.ErrorMessage = value.String
			}
		case upstreamsite.FieldBalanceUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field balance_usd", values[i])
			} else if value.Valid {
				_m.BalanceUsd = new(float64)
				*_m.BalanceUsd = value.Float64
			}
		case upstreamsite.FieldTodayTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field today_tokens", values[i])
			} else if value.Valid {
				_m.TodayTokens = value.Int64
			}
		case upstreamsite.FieldTodayCostUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field today_cost_usd", values[i])
			} else if value.Valid {
				_m.TodayCostUsd = value.Float64
			}
		case upstreamsite.FieldTotalTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_tokens", values[i])
			} else if value.Valid {
				_m.TotalTokens = value.Int64
			}
		case upstreamsite.FieldTotalCostUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field total_cost_usd", values[i])
			} else if value.Valid {
				_m.TotalCostUsd = value.Float64
			}
		case upstreamsite.FieldTrackingStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field tracking_started_at", values[i])
			} else if value.Valid {
				_m.TrackingStartedAt = value.Time
			}
		case upstreamsite.FieldLastSyncedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_synced_at", values[i])
			} else if value.Valid {
				_m.LastSyncedAt = new(time.Time)
				*_m.LastSyncedAt = value.Time
			}
		case upstreamsite.FieldNextSyncAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field next_sync_at", values[i])
			} else if value.Valid {
				_m.NextSyncAt = new(time.Time)
				*_m.NextSyncAt = value.Time
			}
		case upstreamsite.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UpstreamSite.
// This includes values selected through modifiers, order, etc.
func (_m *UpstreamSite) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGroups queries the "groups" edge of the UpstreamSite entity.
func (_m *UpstreamSite) QueryGroups() *UpstreamGroupQuery {
	return NewUpstreamSiteClient(_m.config).QueryGroups(_m)
}

// QueryDailyStats queries the "daily_stats" edge of the UpstreamSite entity.
func (_m *UpstreamSite) QueryDailyStats() *UpstreamDailyStatQuery {
	return NewUpstreamSiteClient(_m.config).QueryDailyStats(_m)
}

// QueryGroupMultiplierHistory queries the "group_multiplier_history" edge of the UpstreamSite entity.
func (_m *UpstreamSite) QueryGroupMultiplierHistory() *UpstreamGroupMultiplierHistoryQuery {
	return NewUpstreamSiteClient(_m.config).QueryGroupMultiplierHistory(_m)
}

// Update returns a builder for updating this UpstreamSite.
// Note that you need to call UpstreamSite.Unwrap() before calling this method if this UpstreamSite
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UpstreamSite) Update() *UpstreamSiteUpdateOne {
	return NewUpstreamSiteClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UpstreamSite entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UpstreamSite) Unwrap() *UpstreamSite {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UpstreamSite is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UpstreamSite) String() string {
	var builder strings.Builder
	builder.WriteString("UpstreamSite(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("base_url=")
	builder.WriteString(_m.BaseURL)
	builder.WriteString(", ")
	builder.WriteString("platform=")
	builder.WriteString(fmt.Sprintf("%v", _m.Platform))
	builder.WriteString(", ")
	builder.WriteString("auth_mode=")
	builder.WriteString(fmt.Sprintf("%v", _m.AuthMode))
	builder.WriteString(", ")
	builder.WriteString("account=")
	builder.WriteString(_m.Account)
	builder.WriteString(", ")
	builder.WriteString("credential_encrypted=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	if v := _m.ErrorMessage; v != nil {
		builder.WriteString("error_message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.BalanceUsd; v != nil {
		builder.WriteString("balance_usd=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("today_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.TodayTokens))
	builder.WriteString(", ")
	builder.WriteString("today_cost_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.TodayCostUsd))
	builder.WriteString(", ")
	builder.WriteString("total_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalTokens))
	builder.WriteString(", ")
	builder.WriteString("total_cost_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalCostUsd))
	builder.WriteString(", ")
	builder.WriteString("tracking_started_at=")
	builder.WriteString(_m.TrackingStartedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.LastSyncedAt; v != nil {
		builder.WriteString("last_synced_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.NextSyncAt; v != nil {
		builder.WriteString("next_sync_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedBy))
	builder.WriteByte(')')
	return builder.String()
}

// UpstreamSites is a parsable slice of UpstreamSite.
type UpstreamSites []*UpstreamSite
