// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/upstreamdailystat"
	"github.com/Wei-Shaw/sub2api/ent/upstreamgroup"
	"github.com/Wei-Shaw/sub2api/ent/upstreamsite"
)

// UpstreamSiteCreate is the builder for creating a UpstreamSite entity.
type UpstreamSiteCreate struct {
	config
	mutation *UpstreamSiteMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *UpstreamSiteCreate) SetCreatedAt(v time.Time) *UpstreamSiteCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UpstreamSiteCreate) SetNillableCreatedAt(v *time.Time) *UpstreamSiteCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UpstreamSiteCreate) SetUpdatedAt(v time.Time) *UpstreamSiteCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UpstreamSiteCreate) SetNillableUpdatedAt(v *time.Time) *UpstreamSiteCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *UpstreamSiteCreate) SetName(v string) *UpstreamSiteCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetBaseURL sets the "base_url" field.
func (_c *UpstreamSiteCreate) SetBaseURL(v string) *UpstreamSiteCreate {
	_c.mutation.SetBaseURL(v)
	return _c
}

// SetPlatform sets the "platform" field.
func (_c *UpstreamSiteCreate) SetPlatform(v upstreamsite.Platform) *UpstreamSiteCreate {
	_c.mutation.SetPlatform(v)
	return _c
}

// SetAuthMode sets the "auth_mode" field.
func (_c *UpstreamSiteCreate) SetAuthMode(v upstreamsite.AuthMode) *UpstreamSiteCreate {
	_c.mutation.SetAuthMode(v)
	return _c
}

// SetAccount sets the "account" field.
func (_c *UpstreamSiteCreate) SetAccount(v string) *UpstreamSiteCreate {
	_c.mutation.SetAccount(v)
	return _c
}

// SetNillableAccount sets the "account" field if the given value is not nil.
func (_c *UpstreamSiteCreate) SetNillableAccount(v *string) *UpstreamSiteCreate {
	if v != nil {
		_c.SetAccount(*v)
	}
	return _c
}

// SetCredentialEncrypted sets the "credential_encrypted" field.
func (_c *UpstreamSiteCreate) SetCredentialEncrypted(v string) *UpstreamSiteCreate {
	_c.mutation.SetCredentialEncrypted(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *UpstreamSiteCreate) SetEnabled(v bool) *UpstreamSiteCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *UpstreamSiteCreate) SetNillableEnabled(v *bool) *UpstreamSiteCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *UpstreamSiteCreate) SetStatus(v upstreamsite.Status) *UpstreamSiteCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *UpstreamSiteCreate) SetNillableStatus(v *upstreamsite.Status) *UpstreamSiteCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *UpstreamSiteCreate) SetErrorMessage(v string) *UpstreamSiteCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *UpstreamSiteCreate) SetNillableErrorMessage(v *string) *UpstreamSiteCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetBalanceUsd sets the "balance_usd" field.
func (_c *UpstreamSiteCreate) SetBalanceUsd(v float64) *UpstreamSiteCreate {
	_c.mutation.SetBalanceUsd(v)
	return _c
}

// SetNillableBalanceUsd sets the "balance_usd" field if the given value is not nil.
func (_c *UpstreamSiteCreate) SetNillableBalanceUsd(v *float64) *UpstreamSiteCreate {
	if v != nil {
		_c.SetBalanceUsd(*v)
	}
	return _c
}

// SetTodayTokens sets the "today_tokens" field.
func (_c *UpstreamSiteCreate) SetTodayTokens(v int64) *UpstreamSiteCreate {
	_c.mutation.SetTodayTokens(v)
	return _c
}

// SetNillableTodayTokens sets the "today_tokens" field if the given value is not nil.
func (_c *UpstreamSiteCreate) SetNillableTodayTokens(v *int64) *UpstreamSiteCreate {
	if v != nil {
		_c.SetTodayTokens(*v)
	}
	return _c
}

// SetTodayCostUsd sets the "today_cost_usd" field.
func (_c *UpstreamSiteCreate) SetTodayCostUsd(v float64) *UpstreamSiteCreate {
	_c.mutation.SetTodayCostUsd(v)
	return _c
}

// SetNillableTodayCostUsd sets the "today_cost_usd" field if the given value is not nil.
func (_c *UpstreamSiteCreate) SetNillableTodayCostUsd(v *float64) *UpstreamSiteCreate {
	if v != nil {
		_c.SetTodayCostUsd(*v)
	}
	return _c
}

// SetTotalTokens sets the "total_tokens" field.
func (_c *UpstreamSiteCreate) SetTotalTokens(v int64) *UpstreamSiteCreate {
	_c.mutation.SetTotalTokens(v)
	return _c
}

// SetNillableTotalTokens sets the "total_tokens" field if the given value is not nil.
func (_c *UpstreamSiteCreate) SetNillableTotalTokens(v *int64) *UpstreamSiteCreate {
	if v != nil {
		_c.SetTotalTokens(*v)
	}
	return _c
}

// SetTotalCostUsd sets the "total_cost_usd" field.
func (_c *UpstreamSiteCreate) SetTotalCostUsd(v float64) *UpstreamSiteCreate {
	_c.mutation.SetTotalCostUsd(v)
	return _c
}

// SetNillableTotalCostUsd sets the "total_cost_usd" field if the given value is not nil.
func (_c *UpstreamSiteCreate) SetNillableTotalCostUsd(v *float64) *UpstreamSiteCreate {
	if v != nil {
		_c.SetTotalCostUsd(*v)
	}
	return _c
}

// SetTrackingStartedAt sets the "tracking_started_at" field.
func (_c *UpstreamSiteCreate) SetTrackingStartedAt(v time.Time) *UpstreamSiteCreate {
	_c.mutation.SetTrackingStartedAt(v)
	return _c
}

// SetNillableTrackingStartedAt sets the "tracking_started_at" field if the given value is not nil.
func (_c *UpstreamSiteCreate) SetNillableTrackingStartedAt(v *time.Time) *UpstreamSiteCreate {
	if v != nil {
		_c.SetTrackingStartedAt(*v)
	}
	return _c
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (_c *UpstreamSiteCreate) SetLastSyncedAt(v time.Time) *UpstreamSiteCreate {
	_c.mutation.SetLastSyncedAt(v)
	return _c
}

// SetNillableLastSyncedAt sets the "last_synced_at" field if the given value is not nil.
func (_c *UpstreamSiteCreate) SetNillableLastSyncedAt(v *time.Time) *UpstreamSiteCreate {
	if v != nil {
		_c.SetLastSyncedAt(*v)
	}
	return _c
}

// SetNextSyncAt sets the "next_sync_at" field.
func (_c *UpstreamSiteCreate) SetNextSyncAt(v time.Time) *UpstreamSiteCreate {
	_c.mutation.SetNextSyncAt(v)
	return _c
}

// SetNillableNextSyncAt sets the "next_sync_at" field if the given value is not nil.
func (_c *UpstreamSiteCreate) SetNillableNextSyncAt(v *time.Time) *UpstreamSiteCreate {
	if v != nil {
		_c.SetNextSyncAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *UpstreamSiteCreate) SetCreatedBy(v int64) *UpstreamSiteCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// AddGroupIDs adds the "groups" edge to the UpstreamGroup entity by IDs.
func (_c *UpstreamSiteCreate) AddGroupIDs(ids ...int64) *UpstreamSiteCreate {
	_c.mutation.AddGroupIDs(ids...)
	return _c
}

// AddGroups adds the "groups" edges to the UpstreamGroup entity.
func (_c *UpstreamSiteCreate) AddGroups(v ...*UpstreamGroup) *UpstreamSiteCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddGroupIDs(ids...)
}

// AddDailyStatIDs adds the "daily_stats" edge to the UpstreamDailyStat entity by IDs.
func (_c *UpstreamSiteCreate) AddDailyStatIDs(ids ...int64) *UpstreamSiteCreate {
	_c.mutation.AddDailyStatIDs(ids...)
	return _c
}

// AddDailyStats adds the "daily_stats" edges to the UpstreamDailyStat entity.
func (_c *UpstreamSiteCreate) AddDailyStats(v ...*UpstreamDailyStat) *UpstreamSiteCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddDailyStatIDs(ids...)
}

// Mutation returns the UpstreamSiteMutation object of the builder.
func (_c *UpstreamSiteCreate) Mutation() *UpstreamSiteMutation {
	return _c.mutation
}

// Save creates the UpstreamSite in the database.
func (_c *UpstreamSiteCreate) Save(ctx context.Context) (*UpstreamSite, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UpstreamSiteCreate) SaveX(ctx context.Context) *UpstreamSite {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UpstreamSiteCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UpstreamSiteCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UpstreamSiteCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := upstreamsite.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := upstreamsite.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Account(); !ok {
		v := upstreamsite.DefaultAccount
		_c.mutation.SetAccount(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := upstreamsite.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := upstreamsite.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.TodayTokens(); !ok {
		v := upstreamsite.DefaultTodayTokens
		_c.mutation.SetTodayTokens(v)
	}
	if _, ok := _c.mutation.TodayCostUsd(); !ok {
		v := upstreamsite.DefaultTodayCostUsd
		_c.mutation.SetTodayCostUsd(v)
	}
	if _, ok := _c.mutation.TotalTokens(); !ok {
		v := upstreamsite.DefaultTotalTokens
		_c.mutation.SetTotalTokens(v)
	}
	if _, ok := _c.mutation.TotalCostUsd(); !ok {
		v := upstreamsite.DefaultTotalCostUsd
		_c.mutation.SetTotalCostUsd(v)
	}
	if _, ok := _c.mutation.TrackingStartedAt(); !ok {
		v := upstreamsite.DefaultTrackingStartedAt()
		_c.mutation.SetTrackingStartedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UpstreamSiteCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UpstreamSite.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UpstreamSite.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "UpstreamSite.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := upstreamsite.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "UpstreamSite.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BaseURL(); !ok {
		return &ValidationError{Name: "base_url", err: errors.New(`ent: missing required field "UpstreamSite.base_url"`)}
	}
	if v, ok := _c.mutation.BaseURL(); ok {
		if err := upstreamsite.BaseURLValidator(v); err != nil {
			return &ValidationError{Name: "base_url", err: fmt.Errorf(`ent: validator failed for field "UpstreamSite.base_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "UpstreamSite.platform"`)}
	}
	if v, ok := _c.mutation.Platform(); ok {
		if err := upstreamsite.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "UpstreamSite.platform": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AuthMode(); !ok {
		return &ValidationError{Name: "auth_mode", err: errors.New(`ent: missing required field "UpstreamSite.auth_mode"`)}
	}
	if v, ok := _c.mutation.AuthMode(); ok {
		if err := upstreamsite.AuthModeValidator(v); err != nil {
			return &ValidationError{Name: "auth_mode", err: fmt.Errorf(`ent: validator failed for field "UpstreamSite.auth_mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Account(); !ok {
		return &ValidationError{Name: "account", err: errors.New(`ent: missing required field "UpstreamSite.account"`)}
	}
	if v, ok := _c.mutation.Account(); ok {
		if err := upstreamsite.AccountValidator(v); err != nil {
			return &ValidationError{Name: "account", err: fmt.Errorf(`ent: validator failed for field "UpstreamSite.account": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CredentialEncrypted(); !ok {
		return &ValidationError{Name: "credential_encrypted", err: errors.New(`ent: missing required field "UpstreamSite.credential_encrypted"`)}
	}
	if v, ok := _c.mutation.CredentialEncrypted(); ok {
		if err := upstreamsite.CredentialEncryptedValidator(v); err != nil {
			return &ValidationError{Name: "credential_encrypted", err: fmt.Errorf(`ent: validator failed for field "UpstreamSite.credential_encrypted": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "UpstreamSite.enabled"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "UpstreamSite.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := upstreamsite.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UpstreamSite.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ErrorMessage(); ok {
		if err := upstreamsite.ErrorMessageValidator(v); err != nil {
			return &ValidationError{Name: "error_message", err: fmt.Errorf(`ent: validator failed for field "UpstreamSite.error_message": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TodayTokens(); !ok {
		return &ValidationError{Name: "today_tokens", err: errors.New(`ent: missing required field "UpstreamSite.today_tokens"`)}
	}
	if _, ok := _c.mutation.TodayCostUsd(); !ok {
		return &ValidationError{Name: "today_cost_usd", err: errors.New(`ent: missing required field "UpstreamSite.today_cost_usd"`)}
	}
	if _, ok := _c.mutation.TotalTokens(); !ok {
		return &ValidationError{Name: "total_tokens", err: errors.New(`ent: missing required field "UpstreamSite.total_tokens"`)}
	}
	if _, ok := _c.mutation.TotalCostUsd(); !ok {
		return &ValidationError{Name: "total_cost_usd", err: errors.New(`ent: missing required field "UpstreamSite.total_cost_usd"`)}
	}
	if _, ok := _c.mutation.TrackingStartedAt(); !ok {
		return &ValidationError{Name: "tracking_started_at", err: errors.New(`ent: missing required field "UpstreamSite.tracking_started_at"`)}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "UpstreamSite.created_by"`)}
	}
	return nil
}

func (_c *UpstreamSiteCreate) sqlSave(ctx context.Context) (*UpstreamSite, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UpstreamSiteCreate) createSpec() (*UpstreamSite, *sqlgraph.CreateSpec) {
	var (
		_node = &UpstreamSite{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(upstreamsite.Table, sqlgraph.NewFieldSpec(upstreamsite.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(upstreamsite.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(upstreamsite.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(upstreamsite.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.BaseURL(); ok {
		_spec.SetField(upstreamsite.FieldBaseURL, field.TypeString, value)
		_node.BaseURL = value
	}
	if value, ok := _c.mutation.Platform(); ok {
		_spec.SetField(upstreamsite.FieldPlatform, field.TypeEnum, value)
		_node.Platform = value
	}
	if value, ok := _c.mutation.AuthMode(); ok {
		_spec.SetField(upstreamsite.FieldAuthMode, field.TypeEnum, value)
		_node.AuthMode = value
	}
	if value, ok := _c.mutation.Account(); ok {
		_spec.SetField(upstreamsite.FieldAccount, field.TypeString, value)
		_node.Account = value
	}
	if value, ok := _c.mutation.CredentialEncrypted(); ok {
		_spec.SetField(upstreamsite.FieldCredentialEncrypted, field.TypeString, value)
		_node.CredentialEncrypted = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(upstreamsite.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(upstreamsite.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(upstreamsite.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = &value
	}
	if value, ok := _c.mutation.BalanceUsd(); ok {
		_spec.SetField(upstreamsite.FieldBalanceUsd, field.TypeFloat64, value)
		_node.BalanceUsd = &value
	}
	if value, ok := _c.mutation.TodayTokens(); ok {
		_spec.SetField(upstreamsite.FieldTodayTokens, field.TypeInt64, value)
		_node.TodayTokens = value
	}
	if value, ok := _c.mutation.TodayCostUsd(); ok {
		_spec.SetField(upstreamsite.FieldTodayCostUsd, field.TypeFloat64, value)
		_node.TodayCostUsd = value
	}
	if value, ok := _c.mutation.TotalTokens(); ok {
		_spec.SetField(upstreamsite.FieldTotalTokens, field.TypeInt64, value)
		_node.TotalTokens = value
	}
	if value, ok := _c.mutation.TotalCostUsd(); ok {
		_spec.SetField(upstreamsite.FieldTotalCostUsd, field.TypeFloat64, value)
		_node.TotalCostUsd = value
	}
	if value, ok := _c.mutation.TrackingStartedAt(); ok {
		_spec.SetField(upstreamsite.FieldTrackingStartedAt, field.TypeTime, value)
		_node.TrackingStartedAt = value
	}
	if value, ok := _c.mutation.LastSyncedAt(); ok {
		_spec.SetField(upstreamsite.FieldLastSyncedAt, field.TypeTime, value)
		_node.LastSyncedAt = &value
	}
	if value, ok := _c.mutation.NextSyncAt(); ok {
		_spec.SetField(upstreamsite.FieldNextSyncAt, field.TypeTime, value)
		_node.NextSyncAt = &value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(upstreamsite.FieldCreatedBy, field.TypeInt64, value)
		_node.CreatedBy = value
	}
	if nodes := _c.mutation.GroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreamsite.GroupsTable,
			Columns: []string{upstreamsite.GroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamgroup.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DailyStatsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreamsite.DailyStatsTable,
			Columns: []string{upstreamsite.DailyStatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamdailystat.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UpstreamSite.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UpstreamSiteUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UpstreamSiteCreate) OnConflict(opts ...sql.ConflictOption) *UpstreamSiteUpsertOne {
	_c.conflict = opts
	return &UpstreamSiteUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UpstreamSite.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UpstreamSiteCreate) OnConflictColumns(columns ...string) *UpstreamSiteUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UpstreamSiteUpsertOne{
		create: _c,
	}
}

type (
	// UpstreamSiteUpsertOne is the builder for "upsert"-ing
	//  one UpstreamSite node.
	UpstreamSiteUpsertOne struct {
		create *UpstreamSiteCreate
	}

	// UpstreamSiteUpsert is the "OnConflict" setter.
	UpstreamSiteUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *UpstreamSiteUpsert) SetUpdatedAt(v time.Time) *UpstreamSiteUpsert {
	u.Set(upstreamsite.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UpstreamSiteUpsert) UpdateUpdatedAt() *UpstreamSiteUpsert {
	u.SetExcluded(upstreamsite.FieldUpdatedAt)
	return u
}

// SetName sets the "name" field.
func (u *UpstreamSiteUpsert) SetName(v string) *UpstreamSiteUpsert {
	u.Set(upstreamsite.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UpstreamSiteUpsert) UpdateName() *UpstreamSiteUpsert {
	u.SetExcluded(upstreamsite.FieldName)
	return u
}

// SetBaseURL sets the "base_url" field.
func (u *UpstreamSiteUpsert) SetBaseURL(v string) *UpstreamSiteUpsert {
	u.Set(upstreamsite.FieldBaseURL, v)
	return u
}

// UpdateBaseURL sets the "base_url" field to the value that was provided on create.
func (u *UpstreamSiteUpsert) UpdateBaseURL() *UpstreamSiteUpsert {
	u.SetExcluded(upstreamsite.FieldBaseURL)
	return u
}

// SetPlatform sets the "platform" field.
func (u *UpstreamSiteUpsert) SetPlatform(v upstreamsite.Platform) *UpstreamSiteUpsert {
	u.Set(upstreamsite.FieldPlatform, v)
	return u
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *UpstreamSiteUpsert) UpdatePlatform() *UpstreamSiteUpsert {
	u.SetExcluded(upstreamsite.FieldPlatform)
	return u
}

// SetAuthMode sets the "auth_mode" field.
func (u *UpstreamSiteUpsert) SetAuthMode(v upstreamsite.AuthMode) *UpstreamSiteUpsert {
	u.Set(upstreamsite.FieldAuthMode, v)
	return u
}

// UpdateAuthMode sets the "auth_mode" field to the value that was provided on create.
func (u *UpstreamSiteUpsert) UpdateAuthMode() *UpstreamSiteUpsert {
	u.SetExcluded(upstreamsite.FieldAuthMode)
	return u
}

// SetAccount sets the "account" field.
func (u *UpstreamSiteUpsert) SetAccount(v string) *UpstreamSiteUpsert {
	u.Set(upstreamsite.FieldAccount, v)
	return u
}

// UpdateAccount sets the "account" field to the value that was provided on create.
func (u *UpstreamSiteUpsert) UpdateAccount() *UpstreamSiteUpsert {
	u.SetExcluded(upstreamsite.FieldAccount)
	return u
}

// SetCredentialEncrypted sets the "credential_encrypted" field.
func (u *UpstreamSiteUpsert) SetCredentialEncrypted(v string) *UpstreamSiteUpsert {
	u.Set(upstreamsite.FieldCredentialEncrypted, v)
	return u
}

// UpdateCredentialEncrypted sets the "credential_encrypted" field to the value that was provided on create.
func (u *UpstreamSiteUpsert) UpdateCredentialEncrypted() *UpstreamSiteUpsert {
	u.SetExcluded(upstreamsite.FieldCredentialEncrypted)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *UpstreamSiteUpsert) SetEnabled(v bool) *UpstreamSiteUpsert {
	u.Set(upstreamsite.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *UpstreamSiteUpsert) UpdateEnabled() *UpstreamSiteUpsert {
	u.SetExcluded(upstreamsite.FieldEnabled)
	return u
}

// SetStatus sets the "status" field.
func (u *UpstreamSiteUpsert) SetStatus(v upstreamsite.Status) *UpstreamSiteUpsert {
	u.Set(upstreamsite.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UpstreamSiteUpsert) UpdateStatus() *UpstreamSiteUpsert {
	u.SetExcluded(upstreamsite.FieldStatus)
	return u
}

// SetErrorMessage sets the "error_message" field.
func (u *UpstreamSiteUpsert) SetErrorMessage(v string) *UpstreamSiteUpsert {
	u.Set(upstreamsite.FieldErrorMessage, v)
	return u
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *UpstreamSiteUpsert) UpdateErrorMessage() *UpstreamSiteUpsert {
	u.SetExcluded(upstreamsite.FieldErrorMessage)
	return u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *UpstreamSiteUpsert) ClearErrorMessage() *UpstreamSiteUpsert {
	u.SetNull(upstreamsite.FieldErrorMessage)
	return u
}

// SetBalanceUsd sets the "balance_usd" field.
func (u *UpstreamSiteUpsert) SetBalanceUsd(v float64) *UpstreamSiteUpsert {
	u.Set(upstreamsite.FieldBalanceUsd, v)
	return u
}

// UpdateBalanceUsd sets the "balance_usd" field to the value that was provided on create.
func (u *UpstreamSiteUpsert) UpdateBalanceUsd() *UpstreamSiteUpsert {
	u.SetExcluded(upstreamsite.FieldBalanceUsd)
	return u
}

// AddBalanceUsd adds v to the "balance_usd" field.
func (u *UpstreamSiteUpsert) AddBalanceUsd(v float64) *UpstreamSiteUpsert {
	u.Add(upstreamsite.FieldBalanceUsd, v)
	return u
}

// ClearBalanceUsd clears the value of the "balance_usd" field.
func (u *UpstreamSiteUpsert) ClearBalanceUsd() *UpstreamSiteUpsert {
	u.SetNull(upstreamsite.FieldBalanceUsd)
	return u
}

// SetTodayTokens sets the "today_tokens" field.
func (u *UpstreamSiteUpsert) SetTodayTokens(v int64) *UpstreamSiteUpsert {
	u.Set(upstreamsite.FieldTodayTokens, v)
	return u
}

// UpdateTodayTokens sets the "today_tokens" field to the value that was provided on create.
func (u *UpstreamSiteUpsert) UpdateTodayTokens() *UpstreamSiteUpsert {
	u.SetExcluded(upstreamsite.FieldTodayTokens)
	return u
}

// AddTodayTokens adds v to the "today_tokens" field.
func (u *UpstreamSiteUpsert) AddTodayTokens(v int64) *UpstreamSiteUpsert {
	u.Add(upstreamsite.FieldTodayTokens, v)
	return u
}

// SetTodayCostUsd sets the "today_cost_usd" field.
func (u *UpstreamSiteUpsert) SetTodayCostUsd(v float64) *UpstreamSiteUpsert {
	u.Set(upstreamsite.FieldTodayCostUsd, v)
	return u
}

// UpdateTodayCostUsd sets the "today_cost_usd" field to the value that was provided on create.
func (u *UpstreamSiteUpsert) UpdateTodayCostUsd() *UpstreamSiteUpsert {
	u.SetExcluded(upstreamsite.FieldTodayCostUsd)
	return u
}

// AddTodayCostUsd adds v to the "today_cost_usd" field.
func (u *UpstreamSiteUpsert) AddTodayCostUsd(v float64) *UpstreamSiteUpsert {
	u.Add(upstreamsite.FieldTodayCostUsd, v)
	return u
}

// SetTotalTokens sets the "total_tokens" field.
func (u *UpstreamSiteUpsert) SetTotalTokens(v int64) *UpstreamSiteUpsert {
	u.Set(upstreamsite.FieldTotalTokens, v)
	return u
}

// UpdateTotalTokens sets the "total_tokens" field to the value that was provided on create.
func (u *UpstreamSiteUpsert) UpdateTotalTokens() *UpstreamSiteUpsert {
	u.SetExcluded(upstreamsite.FieldTotalTokens)
	return u
}

// AddTotalTokens adds v to the "total_tokens" field.
func (u *UpstreamSiteUpsert) AddTotalTokens(v int64) *UpstreamSiteUpsert {
	u.Add(upstreamsite.FieldTotalTokens, v)
	return u
}

// SetTotalCostUsd sets the "total_cost_usd" field.
func (u *UpstreamSiteUpsert) SetTotalCostUsd(v float64) *UpstreamSiteUpsert {
	u.Set(upstreamsite.FieldTotalCostUsd, v)
	return u
}

// UpdateTotalCostUsd sets the "total_cost_usd" field to the value that was provided on create.
func (u *UpstreamSiteUpsert) UpdateTotalCostUsd() *UpstreamSiteUpsert {
	u.SetExcluded(upstreamsite.FieldTotalCostUsd)
	return u
}

// AddTotalCostUsd adds v to the "total_cost_usd" field.
func (u *UpstreamSiteUpsert) AddTotalCostUsd(v float64) *UpstreamSiteUpsert {
	u.Add(upstreamsite.FieldTotalCostUsd, v)
	return u
}

// SetTrackingStartedAt sets the "tracking_started_at" field.
func (u *UpstreamSiteUpsert) SetTrackingStartedAt(v time.Time) *UpstreamSiteUpsert {
	u.Set(upstreamsite.FieldTrackingStartedAt, v)
	return u
}

// UpdateTrackingStartedAt sets the "tracking_started_at" field to the value that was provided on create.
func (u *UpstreamSiteUpsert) UpdateTrackingStartedAt() *UpstreamSiteUpsert {
	u.SetExcluded(upstreamsite.FieldTrackingStartedAt)
	return u
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (u *UpstreamSiteUpsert) SetLastSyncedAt(v time.Time) *UpstreamSiteUpsert {
	u.Set(upstreamsite.FieldLastSyncedAt, v)
	return u
}

// UpdateLastSyncedAt sets the "last_synced_at" field to the value that was provided on create.
func (u *UpstreamSiteUpsert) UpdateLastSyncedAt() *UpstreamSiteUpsert {
	u.SetExcluded(upstreamsite.FieldLastSyncedAt)
	return u
}

// ClearLastSyncedAt clears the value of the "last_synced_at" field.
func (u *UpstreamSiteUpsert) ClearLastSyncedAt() *UpstreamSiteUpsert {
	u.SetNull(upstreamsite.FieldLastSyncedAt)
	return u
}

// SetNextSyncAt sets the "next_sync_at" field.
func (u *UpstreamSiteUpsert) SetNextSyncAt(v time.Time) *UpstreamSiteUpsert {
	u.Set(upstreamsite.FieldNextSyncAt, v)
	return u
}

// UpdateNextSyncAt sets the "next_sync_at" field to the value that was provided on create.
func (u *UpstreamSiteUpsert) UpdateNextSyncAt() *UpstreamSiteUpsert {
	u.SetExcluded(upstreamsite.FieldNextSyncAt)
	return u
}

// ClearNextSyncAt clears the value of the "next_sync_at" field.
func (u *UpstreamSiteUpsert) ClearNextSyncAt() *UpstreamSiteUpsert {
	u.SetNull(upstreamsite.FieldNextSyncAt)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *UpstreamSiteUpsert) SetCreatedBy(v int64) *UpstreamSiteUpsert {
	u.Set(upstreamsite.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *UpstreamSiteUpsert) UpdateCreatedBy() *UpstreamSiteUpsert {
	u.SetExcluded(upstreamsite.FieldCreatedBy)
	return u
}

// AddCreatedBy adds v to the "created_by" field.
func (u *UpstreamSiteUpsert) AddCreatedBy(v int64) *UpstreamSiteUpsert {
	u.Add(upstreamsite.FieldCreatedBy, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UpstreamSite.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UpstreamSiteUpsertOne) UpdateNewValues() *UpstreamSiteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(upstreamsite.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UpstreamSite.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UpstreamSiteUpsertOne) Ignore() *UpstreamSiteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UpstreamSiteUpsertOne) DoNothing() *UpstreamSiteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UpstreamSiteCreate.OnConflict
// documentation for more info.
func (u *UpstreamSiteUpsertOne) Update(set func(*UpstreamSiteUpsert)) *UpstreamSiteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UpstreamSiteUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UpstreamSiteUpsertOne) SetUpdatedAt(v time.Time) *UpstreamSiteUpsertOne {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UpstreamSiteUpsertOne) UpdateUpdatedAt() *UpstreamSiteUpsertOne {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *UpstreamSiteUpsertOne) SetName(v string) *UpstreamSiteUpsertOne {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UpstreamSiteUpsertOne) UpdateName() *UpstreamSiteUpsertOne {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.UpdateName()
	})
}

// SetBaseURL sets the "base_url" field.
func (u *UpstreamSiteUpsertOne) SetBaseURL(v string) *UpstreamSiteUpsertOne {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.SetBaseURL(v)
	})
}

// UpdateBaseURL sets the "base_url" field to the value that was provided on create.
func (u *UpstreamSiteUpsertOne) UpdateBaseURL() *UpstreamSiteUpsertOne {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.UpdateBaseURL()
	})
}

// SetPlatform sets the "platform" field.
func (u *UpstreamSiteUpsertOne) SetPlatform(v upstreamsite.Platform) *UpstreamSiteUpsertOne {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *UpstreamSiteUpsertOne) UpdatePlatform() *UpstreamSiteUpsertOne {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.UpdatePlatform()
	})
}

// SetAuthMode sets the "auth_mode" field.
func (u *UpstreamSiteUpsertOne) SetAuthMode(v upstreamsite.AuthMode) *UpstreamSiteUpsertOne {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.SetAuthMode(v)
	})
}

// UpdateAuthMode sets the "auth_mode" field to the value that was provided on create.
func (u *UpstreamSiteUpsertOne) UpdateAuthMode() *UpstreamSiteUpsertOne {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.UpdateAuthMode()
	})
}

// SetAccount sets the "account" field.
func (u *UpstreamSiteUpsertOne) SetAccount(v string) *UpstreamSiteUpsertOne {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.SetAccount(v)
	})
}

// UpdateAccount sets the "account" field to the value that was provided on create.
func (u *UpstreamSiteUpsertOne) UpdateAccount() *UpstreamSiteUpsertOne {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.UpdateAccount()
	})
}

// SetCredentialEncrypted sets the "credential_encrypted" field.
func (u *UpstreamSiteUpsertOne) SetCredentialEncrypted(v string) *UpstreamSiteUpsertOne {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.SetCredentialEncrypted(v)
	})
}

// UpdateCredentialEncrypted sets the "credential_encrypted" field to the value that was provided on create.
func (u *UpstreamSiteUpsertOne) UpdateCredentialEncrypted() *UpstreamSiteUpsertOne {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.UpdateCredentialEncrypted()
	})
}

// SetEnabled sets the "enabled" field.
func (u *UpstreamSiteUpsertOne) SetEnabled(v bool) *UpstreamSiteUpsertOne {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *UpstreamSiteUpsertOne) UpdateEnabled() *UpstreamSiteUpsertOne {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.UpdateEnabled()
	})
}

// SetStatus sets the "status" field.
func (u *UpstreamSiteUpsertOne) SetStatus(v upstreamsite.Status) *UpstreamSiteUpsertOne {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UpstreamSiteUpsertOne) UpdateStatus() *UpstreamSiteUpsertOne {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.UpdateStatus()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *UpstreamSiteUpsertOne) SetErrorMessage(v string) *UpstreamSiteUpsertOne {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *UpstreamSiteUpsertOne) UpdateErrorMessage() *UpstreamSiteUpsertOne {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *UpstreamSiteUpsertOne) ClearErrorMessage() *UpstreamSiteUpsertOne {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.ClearErrorMessage()
	})
}

// SetBalanceUsd sets the "balance_usd" field.
func (u *UpstreamSiteUpsertOne) SetBalanceUsd(v float64) *UpstreamSiteUpsertOne {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.SetBalanceUsd(v)
	})
}

// AddBalanceUsd adds v to the "balance_usd" field.
func (u *UpstreamSiteUpsertOne) AddBalanceUsd(v float64) *UpstreamSiteUpsertOne {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.AddBalanceUsd(v)
	})
}

// UpdateBalanceUsd sets the "balance_usd" field to the value that was provided on create.
func (u *UpstreamSiteUpsertOne) UpdateBalanceUsd() *UpstreamSiteUpsertOne {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.UpdateBalanceUsd()
	})
}

// ClearBalanceUsd clears the value of the "balance_usd" field.
func (u *UpstreamSiteUpsertOne) ClearBalanceUsd() *UpstreamSiteUpsertOne {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.ClearBalanceUsd()
	})
}

// SetTodayTokens sets the "today_tokens" field.
func (u *UpstreamSiteUpsertOne) SetTodayTokens(v int64) *UpstreamSiteUpsertOne {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.SetTodayTokens(v)
	})
}

// AddTodayTokens adds v to the "today_tokens" field.
func (u *UpstreamSiteUpsertOne) AddTodayTokens(v int64) *UpstreamSiteUpsertOne {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.AddTodayTokens(v)
	})
}

// UpdateTodayTokens sets the "today_tokens" field to the value that was provided on create.
func (u *UpstreamSiteUpsertOne) UpdateTodayTokens() *UpstreamSiteUpsertOne {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.UpdateTodayTokens()
	})
}

// SetTodayCostUsd sets the "today_cost_usd" field.
func (u *UpstreamSiteUpsertOne) SetTodayCostUsd(v float64) *UpstreamSiteUpsertOne {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.SetTodayCostUsd(v)
	})
}

// AddTodayCostUsd adds v to the "today_cost_usd" field.
func (u *UpstreamSiteUpsertOne) AddTodayCostUsd(v float64) *UpstreamSiteUpsertOne {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.AddTodayCostUsd(v)
	})
}

// UpdateTodayCostUsd sets the "today_cost_usd" field to the value that was provided on create.
func (u *UpstreamSiteUpsertOne) UpdateTodayCostUsd() *UpstreamSiteUpsertOne {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.UpdateTodayCostUsd()
	})
}

// SetTotalTokens sets the "total_tokens" field.
func (u *UpstreamSiteUpsertOne) SetTotalTokens(v int64) *UpstreamSiteUpsertOne {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.SetTotalTokens(v)
	})
}

// AddTotalTokens adds v to the "total_tokens" field.
func (u *UpstreamSiteUpsertOne) AddTotalTokens(v int64) *UpstreamSiteUpsertOne {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.AddTotalTokens(v)
	})
}

// UpdateTotalTokens sets the "total_tokens" field to the value that was provided on create.
func (u *UpstreamSiteUpsertOne) UpdateTotalTokens() *UpstreamSiteUpsertOne {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.UpdateTotalTokens()
	})
}

// SetTotalCostUsd sets the "total_cost_usd" field.
func (u *UpstreamSiteUpsertOne) SetTotalCostUsd(v float64) *UpstreamSiteUpsertOne {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.SetTotalCostUsd(v)
	})
}

// AddTotalCostUsd adds v to the "total_cost_usd" field.
func (u *UpstreamSiteUpsertOne) AddTotalCostUsd(v float64) *UpstreamSiteUpsertOne {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.AddTotalCostUsd(v)
	})
}

// UpdateTotalCostUsd sets the "total_cost_usd" field to the value that was provided on create.
func (u *UpstreamSiteUpsertOne) UpdateTotalCostUsd() *UpstreamSiteUpsertOne {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.UpdateTotalCostUsd()
	})
}

// SetTrackingStartedAt sets the "tracking_started_at" field.
func (u *UpstreamSiteUpsertOne) SetTrackingStartedAt(v time.Time) *UpstreamSiteUpsertOne {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.SetTrackingStartedAt(v)
	})
}

// UpdateTrackingStartedAt sets the "tracking_started_at" field to the value that was provided on create.
func (u *UpstreamSiteUpsertOne) UpdateTrackingStartedAt() *UpstreamSiteUpsertOne {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.UpdateTrackingStartedAt()
	})
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (u *UpstreamSiteUpsertOne) SetLastSyncedAt(v time.Time) *UpstreamSiteUpsertOne {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.SetLastSyncedAt(v)
	})
}

// UpdateLastSyncedAt sets the "last_synced_at" field to the value that was provided on create.
func (u *UpstreamSiteUpsertOne) UpdateLastSyncedAt() *UpstreamSiteUpsertOne {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.UpdateLastSyncedAt()
	})
}

// ClearLastSyncedAt clears the value of the "last_synced_at" field.
func (u *UpstreamSiteUpsertOne) ClearLastSyncedAt() *UpstreamSiteUpsertOne {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.ClearLastSyncedAt()
	})
}

// SetNextSyncAt sets the "next_sync_at" field.
func (u *UpstreamSiteUpsertOne) SetNextSyncAt(v time.Time) *UpstreamSiteUpsertOne {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.SetNextSyncAt(v)
	})
}

// UpdateNextSyncAt sets the "next_sync_at" field to the value that was provided on create.
func (u *UpstreamSiteUpsertOne) UpdateNextSyncAt() *UpstreamSiteUpsertOne {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.UpdateNextSyncAt()
	})
}

// ClearNextSyncAt clears the value of the "next_sync_at" field.
func (u *UpstreamSiteUpsertOne) ClearNextSyncAt() *UpstreamSiteUpsertOne {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.ClearNextSyncAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *UpstreamSiteUpsertOne) SetCreatedBy(v int64) *UpstreamSiteUpsertOne {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *UpstreamSiteUpsertOne) AddCreatedBy(v int64) *UpstreamSiteUpsertOne {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *UpstreamSiteUpsertOne) UpdateCreatedBy() *UpstreamSiteUpsertOne {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.UpdateCreatedBy()
	})
}

// Exec executes the query.
func (u *UpstreamSiteUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UpstreamSiteCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UpstreamSiteUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UpstreamSiteUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UpstreamSiteUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UpstreamSiteCreateBulk is the builder for creating many UpstreamSite entities in bulk.
type UpstreamSiteCreateBulk struct {
	config
	err      error
	builders []*UpstreamSiteCreate
	conflict []sql.ConflictOption
}

// Save creates the UpstreamSite entities in the database.
func (_c *UpstreamSiteCreateBulk) Save(ctx context.Context) ([]*UpstreamSite, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UpstreamSite, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UpstreamSiteMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UpstreamSiteCreateBulk) SaveX(ctx context.Context) []*UpstreamSite {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UpstreamSiteCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UpstreamSiteCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UpstreamSite.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UpstreamSiteUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UpstreamSiteCreateBulk) OnConflict(opts ...sql.ConflictOption) *UpstreamSiteUpsertBulk {
	_c.conflict = opts
	return &UpstreamSiteUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UpstreamSite.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UpstreamSiteCreateBulk) OnConflictColumns(columns ...string) *UpstreamSiteUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UpstreamSiteUpsertBulk{
		create: _c,
	}
}

// UpstreamSiteUpsertBulk is the builder for "upsert"-ing
// a bulk of UpstreamSite nodes.
type UpstreamSiteUpsertBulk struct {
	create *UpstreamSiteCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UpstreamSite.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UpstreamSiteUpsertBulk) UpdateNewValues() *UpstreamSiteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(upstreamsite.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UpstreamSite.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UpstreamSiteUpsertBulk) Ignore() *UpstreamSiteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UpstreamSiteUpsertBulk) DoNothing() *UpstreamSiteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UpstreamSiteCreateBulk.OnConflict
// documentation for more info.
func (u *UpstreamSiteUpsertBulk) Update(set func(*UpstreamSiteUpsert)) *UpstreamSiteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UpstreamSiteUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UpstreamSiteUpsertBulk) SetUpdatedAt(v time.Time) *UpstreamSiteUpsertBulk {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UpstreamSiteUpsertBulk) UpdateUpdatedAt() *UpstreamSiteUpsertBulk {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *UpstreamSiteUpsertBulk) SetName(v string) *UpstreamSiteUpsertBulk {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UpstreamSiteUpsertBulk) UpdateName() *UpstreamSiteUpsertBulk {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.UpdateName()
	})
}

// SetBaseURL sets the "base_url" field.
func (u *UpstreamSiteUpsertBulk) SetBaseURL(v string) *UpstreamSiteUpsertBulk {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.SetBaseURL(v)
	})
}

// UpdateBaseURL sets the "base_url" field to the value that was provided on create.
func (u *UpstreamSiteUpsertBulk) UpdateBaseURL() *UpstreamSiteUpsertBulk {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.UpdateBaseURL()
	})
}

// SetPlatform sets the "platform" field.
func (u *UpstreamSiteUpsertBulk) SetPlatform(v upstreamsite.Platform) *UpstreamSiteUpsertBulk {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *UpstreamSiteUpsertBulk) UpdatePlatform() *UpstreamSiteUpsertBulk {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.UpdatePlatform()
	})
}

// SetAuthMode sets the "auth_mode" field.
func (u *UpstreamSiteUpsertBulk) SetAuthMode(v upstreamsite.AuthMode) *UpstreamSiteUpsertBulk {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.SetAuthMode(v)
	})
}

// UpdateAuthMode sets the "auth_mode" field to the value that was provided on create.
func (u *UpstreamSiteUpsertBulk) UpdateAuthMode() *UpstreamSiteUpsertBulk {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.UpdateAuthMode()
	})
}

// SetAccount sets the "account" field.
func (u *UpstreamSiteUpsertBulk) SetAccount(v string) *UpstreamSiteUpsertBulk {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.SetAccount(v)
	})
}

// UpdateAccount sets the "account" field to the value that was provided on create.
func (u *UpstreamSiteUpsertBulk) UpdateAccount() *UpstreamSiteUpsertBulk {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.UpdateAccount()
	})
}

// SetCredentialEncrypted sets the "credential_encrypted" field.
func (u *UpstreamSiteUpsertBulk) SetCredentialEncrypted(v string) *UpstreamSiteUpsertBulk {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.SetCredentialEncrypted(v)
	})
}

// UpdateCredentialEncrypted sets the "credential_encrypted" field to the value that was provided on create.
func (u *UpstreamSiteUpsertBulk) UpdateCredentialEncrypted() *UpstreamSiteUpsertBulk {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.UpdateCredentialEncrypted()
	})
}

// SetEnabled sets the "enabled" field.
func (u *UpstreamSiteUpsertBulk) SetEnabled(v bool) *UpstreamSiteUpsertBulk {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *UpstreamSiteUpsertBulk) UpdateEnabled() *UpstreamSiteUpsertBulk {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.UpdateEnabled()
	})
}

// SetStatus sets the "status" field.
func (u *UpstreamSiteUpsertBulk) SetStatus(v upstreamsite.Status) *UpstreamSiteUpsertBulk {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UpstreamSiteUpsertBulk) UpdateStatus() *UpstreamSiteUpsertBulk {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.UpdateStatus()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *UpstreamSiteUpsertBulk) SetErrorMessage(v string) *UpstreamSiteUpsertBulk {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *UpstreamSiteUpsertBulk) UpdateErrorMessage() *UpstreamSiteUpsertBulk {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *UpstreamSiteUpsertBulk) ClearErrorMessage() *UpstreamSiteUpsertBulk {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.ClearErrorMessage()
	})
}

// SetBalanceUsd sets the "balance_usd" field.
func (u *UpstreamSiteUpsertBulk) SetBalanceUsd(v float64) *UpstreamSiteUpsertBulk {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.SetBalanceUsd(v)
	})
}

// AddBalanceUsd adds v to the "balance_usd" field.
func (u *UpstreamSiteUpsertBulk) AddBalanceUsd(v float64) *UpstreamSiteUpsertBulk {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.AddBalanceUsd(v)
	})
}

// UpdateBalanceUsd sets the "balance_usd" field to the value that was provided on create.
func (u *UpstreamSiteUpsertBulk) UpdateBalanceUsd() *UpstreamSiteUpsertBulk {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.UpdateBalanceUsd()
	})
}

// ClearBalanceUsd clears the value of the "balance_usd" field.
func (u *UpstreamSiteUpsertBulk) ClearBalanceUsd() *UpstreamSiteUpsertBulk {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.ClearBalanceUsd()
	})
}

// SetTodayTokens sets the "today_tokens" field.
func (u *UpstreamSiteUpsertBulk) SetTodayTokens(v int64) *UpstreamSiteUpsertBulk {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.SetTodayTokens(v)
	})
}

// AddTodayTokens adds v to the "today_tokens" field.
func (u *UpstreamSiteUpsertBulk) AddTodayTokens(v int64) *UpstreamSiteUpsertBulk {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.AddTodayTokens(v)
	})
}

// UpdateTodayTokens sets the "today_tokens" field to the value that was provided on create.
func (u *UpstreamSiteUpsertBulk) UpdateTodayTokens() *UpstreamSiteUpsertBulk {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.UpdateTodayTokens()
	})
}

// SetTodayCostUsd sets the "today_cost_usd" field.
func (u *UpstreamSiteUpsertBulk) SetTodayCostUsd(v float64) *UpstreamSiteUpsertBulk {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.SetTodayCostUsd(v)
	})
}

// AddTodayCostUsd adds v to the "today_cost_usd" field.
func (u *UpstreamSiteUpsertBulk) AddTodayCostUsd(v float64) *UpstreamSiteUpsertBulk {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.AddTodayCostUsd(v)
	})
}

// UpdateTodayCostUsd sets the "today_cost_usd" field to the value that was provided on create.
func (u *UpstreamSiteUpsertBulk) UpdateTodayCostUsd() *UpstreamSiteUpsertBulk {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.UpdateTodayCostUsd()
	})
}

// SetTotalTokens sets the "total_tokens" field.
func (u *UpstreamSiteUpsertBulk) SetTotalTokens(v int64) *UpstreamSiteUpsertBulk {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.SetTotalTokens(v)
	})
}

// AddTotalTokens adds v to the "total_tokens" field.
func (u *UpstreamSiteUpsertBulk) AddTotalTokens(v int64) *UpstreamSiteUpsertBulk {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.AddTotalTokens(v)
	})
}

// UpdateTotalTokens sets the "total_tokens" field to the value that was provided on create.
func (u *UpstreamSiteUpsertBulk) UpdateTotalTokens() *UpstreamSiteUpsertBulk {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.UpdateTotalTokens()
	})
}

// SetTotalCostUsd sets the "total_cost_usd" field.
func (u *UpstreamSiteUpsertBulk) SetTotalCostUsd(v float64) *UpstreamSiteUpsertBulk {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.SetTotalCostUsd(v)
	})
}

// AddTotalCostUsd adds v to the "total_cost_usd" field.
func (u *UpstreamSiteUpsertBulk) AddTotalCostUsd(v float64) *UpstreamSiteUpsertBulk {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.AddTotalCostUsd(v)
	})
}

// UpdateTotalCostUsd sets the "total_cost_usd" field to the value that was provided on create.
func (u *UpstreamSiteUpsertBulk) UpdateTotalCostUsd() *UpstreamSiteUpsertBulk {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.UpdateTotalCostUsd()
	})
}

// SetTrackingStartedAt sets the "tracking_started_at" field.
func (u *UpstreamSiteUpsertBulk) SetTrackingStartedAt(v time.Time) *UpstreamSiteUpsertBulk {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.SetTrackingStartedAt(v)
	})
}

// UpdateTrackingStartedAt sets the "tracking_started_at" field to the value that was provided on create.
func (u *UpstreamSiteUpsertBulk) UpdateTrackingStartedAt() *UpstreamSiteUpsertBulk {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.UpdateTrackingStartedAt()
	})
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (u *UpstreamSiteUpsertBulk) SetLastSyncedAt(v time.Time) *UpstreamSiteUpsertBulk {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.SetLastSyncedAt(v)
	})
}

// UpdateLastSyncedAt sets the "last_synced_at" field to the value that was provided on create.
func (u *UpstreamSiteUpsertBulk) UpdateLastSyncedAt() *UpstreamSiteUpsertBulk {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.UpdateLastSyncedAt()
	})
}

// ClearLastSyncedAt clears the value of the "last_synced_at" field.
func (u *UpstreamSiteUpsertBulk) ClearLastSyncedAt() *UpstreamSiteUpsertBulk {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.ClearLastSyncedAt()
	})
}

// SetNextSyncAt sets the "next_sync_at" field.
func (u *UpstreamSiteUpsertBulk) SetNextSyncAt(v time.Time) *UpstreamSiteUpsertBulk {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.SetNextSyncAt(v)
	})
}

// UpdateNextSyncAt sets the "next_sync_at" field to the value that was provided on create.
func (u *UpstreamSiteUpsertBulk) UpdateNextSyncAt() *UpstreamSiteUpsertBulk {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.UpdateNextSyncAt()
	})
}

// ClearNextSyncAt clears the value of the "next_sync_at" field.
func (u *UpstreamSiteUpsertBulk) ClearNextSyncAt() *UpstreamSiteUpsertBulk {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.ClearNextSyncAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *UpstreamSiteUpsertBulk) SetCreatedBy(v int64) *UpstreamSiteUpsertBulk {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *UpstreamSiteUpsertBulk) AddCreatedBy(v int64) *UpstreamSiteUpsertBulk {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *UpstreamSiteUpsertBulk) UpdateCreatedBy() *UpstreamSiteUpsertBulk {
	return u.Update(func(s *UpstreamSiteUpsert) {
		s.UpdateCreatedBy()
	})
}

// Exec executes the query.
func (u *UpstreamSiteUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UpstreamSiteCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UpstreamSiteCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UpstreamSiteUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
