// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/upstreamgroup"
	"github.com/Wei-Shaw/sub2api/ent/upstreamgroupaccountbinding"
)

// UpstreamGroupAccountBindingUpdate is the builder for updating UpstreamGroupAccountBinding entities.
type UpstreamGroupAccountBindingUpdate struct {
	config
	hooks    []Hook
	mutation *UpstreamGroupAccountBindingMutation
}

// Where appends a list predicates to the UpstreamGroupAccountBindingUpdate builder.
func (_u *UpstreamGroupAccountBindingUpdate) Where(ps ...predicate.UpstreamGroupAccountBinding) *UpstreamGroupAccountBindingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpstreamGroupID sets the "upstream_group_id" field.
func (_u *UpstreamGroupAccountBindingUpdate) SetUpstreamGroupID(v int64) *UpstreamGroupAccountBindingUpdate {
	_u.mutation.SetUpstreamGroupID(v)
	return _u
}

// SetNillableUpstreamGroupID sets the "upstream_group_id" field if the given value is not nil.
func (_u *UpstreamGroupAccountBindingUpdate) SetNillableUpstreamGroupID(v *int64) *UpstreamGroupAccountBindingUpdate {
	if v != nil {
		_u.SetUpstreamGroupID(*v)
	}
	return _u
}

// SetLocalGroupID sets the "local_group_id" field.
func (_u *UpstreamGroupAccountBindingUpdate) SetLocalGroupID(v int64) *UpstreamGroupAccountBindingUpdate {
	_u.mutation.SetLocalGroupID(v)
	return _u
}

// SetNillableLocalGroupID sets the "local_group_id" field if the given value is not nil.
func (_u *UpstreamGroupAccountBindingUpdate) SetNillableLocalGroupID(v *int64) *UpstreamGroupAccountBindingUpdate {
	if v != nil {
		_u.SetLocalGroupID(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *UpstreamGroupAccountBindingUpdate) SetAccountID(v int64) *UpstreamGroupAccountBindingUpdate {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *UpstreamGroupAccountBindingUpdate) SetNillableAccountID(v *int64) *UpstreamGroupAccountBindingUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetUpstreamGroup sets the "upstream_group" edge to the UpstreamGroup entity.
func (_u *UpstreamGroupAccountBindingUpdate) SetUpstreamGroup(v *UpstreamGroup) *UpstreamGroupAccountBindingUpdate {
	return _u.SetUpstreamGroupID(v.ID)
}

// SetLocalGroup sets the "local_group" edge to the Group entity.
func (_u *UpstreamGroupAccountBindingUpdate) SetLocalGroup(v *Group) *UpstreamGroupAccountBindingUpdate {
	return _u.SetLocalGroupID(v.ID)
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *UpstreamGroupAccountBindingUpdate) SetAccount(v *Account) *UpstreamGroupAccountBindingUpdate {
	return _u.SetAccountID(v.ID)
}

// Mutation returns the UpstreamGroupAccountBindingMutation object of the builder.
func (_u *UpstreamGroupAccountBindingUpdate) Mutation() *UpstreamGroupAccountBindingMutation {
	return _u.mutation
}

// ClearUpstreamGroup clears the "upstream_group" edge to the UpstreamGroup entity.
func (_u *UpstreamGroupAccountBindingUpdate) ClearUpstreamGroup() *UpstreamGroupAccountBindingUpdate {
	_u.mutation.ClearUpstreamGroup()
	return _u
}

// ClearLocalGroup clears the "local_group" edge to the Group entity.
func (_u *UpstreamGroupAccountBindingUpdate) ClearLocalGroup() *UpstreamGroupAccountBindingUpdate {
	_u.mutation.ClearLocalGroup()
	return _u
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *UpstreamGroupAccountBindingUpdate) ClearAccount() *UpstreamGroupAccountBindingUpdate {
	_u.mutation.ClearAccount()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UpstreamGroupAccountBindingUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UpstreamGroupAccountBindingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UpstreamGroupAccountBindingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UpstreamGroupAccountBindingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UpstreamGroupAccountBindingUpdate) check() error {
	if _u.mutation.UpstreamGroupCleared() && len(_u.mutation.UpstreamGroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UpstreamGroupAccountBinding.upstream_group"`)
	}
	if _u.mutation.LocalGroupCleared() && len(_u.mutation.LocalGroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UpstreamGroupAccountBinding.local_group"`)
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UpstreamGroupAccountBinding.account"`)
	}
	return nil
}

func (_u *UpstreamGroupAccountBindingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(upstreamgroupaccountbinding.Table, upstreamgroupaccountbinding.Columns, sqlgraph.NewFieldSpec(upstreamgroupaccountbinding.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.UpstreamGroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   upstreamgroupaccountbinding.UpstreamGroupTable,
			Columns: []string{upstreamgroupaccountbinding.UpstreamGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamgroup.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UpstreamGroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   upstreamgroupaccountbinding.UpstreamGroupTable,
			Columns: []string{upstreamgroupaccountbinding.UpstreamGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamgroup.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LocalGroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   upstreamgroupaccountbinding.LocalGroupTable,
			Columns: []string{upstreamgroupaccountbinding.LocalGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LocalGroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   upstreamgroupaccountbinding.LocalGroupTable,
			Columns: []string{upstreamgroupaccountbinding.LocalGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   upstreamgroupaccountbinding.AccountTable,
			Columns: []string{upstreamgroupaccountbinding.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   upstreamgroupaccountbinding.AccountTable,
			Columns: []string{upstreamgroupaccountbinding.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upstreamgroupaccountbinding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UpstreamGroupAccountBindingUpdateOne is the builder for updating a single UpstreamGroupAccountBinding entity.
type UpstreamGroupAccountBindingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UpstreamGroupAccountBindingMutation
}

// SetUpstreamGroupID sets the "upstream_group_id" field.
func (_u *UpstreamGroupAccountBindingUpdateOne) SetUpstreamGroupID(v int64) *UpstreamGroupAccountBindingUpdateOne {
	_u.mutation.SetUpstreamGroupID(v)
	return _u
}

// SetNillableUpstreamGroupID sets the "upstream_group_id" field if the given value is not nil.
func (_u *UpstreamGroupAccountBindingUpdateOne) SetNillableUpstreamGroupID(v *int64) *UpstreamGroupAccountBindingUpdateOne {
	if v != nil {
		_u.SetUpstreamGroupID(*v)
	}
	return _u
}

// SetLocalGroupID sets the "local_group_id" field.
func (_u *UpstreamGroupAccountBindingUpdateOne) SetLocalGroupID(v int64) *UpstreamGroupAccountBindingUpdateOne {
	_u.mutation.SetLocalGroupID(v)
	return _u
}

// SetNillableLocalGroupID sets the "local_group_id" field if the given value is not nil.
func (_u *UpstreamGroupAccountBindingUpdateOne) SetNillableLocalGroupID(v *int64) *UpstreamGroupAccountBindingUpdateOne {
	if v != nil {
		_u.SetLocalGroupID(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *UpstreamGroupAccountBindingUpdateOne) SetAccountID(v int64) *UpstreamGroupAccountBindingUpdateOne {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *UpstreamGroupAccountBindingUpdateOne) SetNillableAccountID(v *int64) *UpstreamGroupAccountBindingUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetUpstreamGroup sets the "upstream_group" edge to the UpstreamGroup entity.
func (_u *UpstreamGroupAccountBindingUpdateOne) SetUpstreamGroup(v *UpstreamGroup) *UpstreamGroupAccountBindingUpdateOne {
	return _u.SetUpstreamGroupID(v.ID)
}

// SetLocalGroup sets the "local_group" edge to the Group entity.
func (_u *UpstreamGroupAccountBindingUpdateOne) SetLocalGroup(v *Group) *UpstreamGroupAccountBindingUpdateOne {
	return _u.SetLocalGroupID(v.ID)
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *UpstreamGroupAccountBindingUpdateOne) SetAccount(v *Account) *UpstreamGroupAccountBindingUpdateOne {
	return _u.SetAccountID(v.ID)
}

// Mutation returns the UpstreamGroupAccountBindingMutation object of the builder.
func (_u *UpstreamGroupAccountBindingUpdateOne) Mutation() *UpstreamGroupAccountBindingMutation {
	return _u.mutation
}

// ClearUpstreamGroup clears the "upstream_group" edge to the UpstreamGroup entity.
func (_u *UpstreamGroupAccountBindingUpdateOne) ClearUpstreamGroup() *UpstreamGroupAccountBindingUpdateOne {
	_u.mutation.ClearUpstreamGroup()
	return _u
}

// ClearLocalGroup clears the "local_group" edge to the Group entity.
func (_u *UpstreamGroupAccountBindingUpdateOne) ClearLocalGroup() *UpstreamGroupAccountBindingUpdateOne {
	_u.mutation.ClearLocalGroup()
	return _u
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *UpstreamGroupAccountBindingUpdateOne) ClearAccount() *UpstreamGroupAccountBindingUpdateOne {
	_u.mutation.ClearAccount()
	return _u
}

// Where appends a list predicates to the UpstreamGroupAccountBindingUpdate builder.
func (_u *UpstreamGroupAccountBindingUpdateOne) Where(ps ...predicate.UpstreamGroupAccountBinding) *UpstreamGroupAccountBindingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UpstreamGroupAccountBindingUpdateOne) Select(field string, fields ...string) *UpstreamGroupAccountBindingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UpstreamGroupAccountBinding entity.
func (_u *UpstreamGroupAccountBindingUpdateOne) Save(ctx context.Context) (*UpstreamGroupAccountBinding, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UpstreamGroupAccountBindingUpdateOne) SaveX(ctx context.Context) *UpstreamGroupAccountBinding {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UpstreamGroupAccountBindingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UpstreamGroupAccountBindingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UpstreamGroupAccountBindingUpdateOne) check() error {
	if _u.mutation.UpstreamGroupCleared() && len(_u.mutation.UpstreamGroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UpstreamGroupAccountBinding.upstream_group"`)
	}
	if _u.mutation.LocalGroupCleared() && len(_u.mutation.LocalGroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UpstreamGroupAccountBinding.local_group"`)
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UpstreamGroupAccountBinding.account"`)
	}
	return nil
}

func (_u *UpstreamGroupAccountBindingUpdateOne) sqlSave(ctx context.Context) (_node *UpstreamGroupAccountBinding, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(upstreamgroupaccountbinding.Table, upstreamgroupaccountbinding.Columns, sqlgraph.NewFieldSpec(upstreamgroupaccountbinding.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UpstreamGroupAccountBinding.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, upstreamgroupaccountbinding.FieldID)
		for _, f := range fields {
			if !upstreamgroupaccountbinding.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != upstreamgroupaccountbinding.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.UpstreamGroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   upstreamgroupaccountbinding.UpstreamGroupTable,
			Columns: []string{upstreamgroupaccountbinding.UpstreamGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamgroup.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UpstreamGroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   upstreamgroupaccountbinding.UpstreamGroupTable,
			Columns: []string{upstreamgroupaccountbinding.UpstreamGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamgroup.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LocalGroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   upstreamgroupaccountbinding.LocalGroupTable,
			Columns: []string{upstreamgroupaccountbinding.LocalGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LocalGroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   upstreamgroupaccountbinding.LocalGroupTable,
			Columns: []string{upstreamgroupaccountbinding.LocalGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   upstreamgroupaccountbinding.AccountTable,
			Columns: []string{upstreamgroupaccountbinding.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   upstreamgroupaccountbinding.AccountTable,
			Columns: []string{upstreamgroupaccountbinding.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UpstreamGroupAccountBinding{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upstreamgroupaccountbinding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
