// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/upstreamgroup"
	"github.com/Wei-Shaw/sub2api/ent/upstreamsite"
)

// UpstreamGroupCreate is the builder for creating a UpstreamGroup entity.
type UpstreamGroupCreate struct {
	config
	mutation *UpstreamGroupMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *UpstreamGroupCreate) SetCreatedAt(v time.Time) *UpstreamGroupCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UpstreamGroupCreate) SetNillableCreatedAt(v *time.Time) *UpstreamGroupCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UpstreamGroupCreate) SetUpdatedAt(v time.Time) *UpstreamGroupCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UpstreamGroupCreate) SetNillableUpdatedAt(v *time.Time) *UpstreamGroupCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetSiteID sets the "site_id" field.
func (_c *UpstreamGroupCreate) SetSiteID(v int64) *UpstreamGroupCreate {
	_c.mutation.SetSiteID(v)
	return _c
}

// SetRemoteID sets the "remote_id" field.
func (_c *UpstreamGroupCreate) SetRemoteID(v string) *UpstreamGroupCreate {
	_c.mutation.SetRemoteID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *UpstreamGroupCreate) SetName(v string) *UpstreamGroupCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetPlatform sets the "platform" field.
func (_c *UpstreamGroupCreate) SetPlatform(v string) *UpstreamGroupCreate {
	_c.mutation.SetPlatform(v)
	return _c
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_c *UpstreamGroupCreate) SetNillablePlatform(v *string) *UpstreamGroupCreate {
	if v != nil {
		_c.SetPlatform(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *UpstreamGroupCreate) SetDescription(v string) *UpstreamGroupCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *UpstreamGroupCreate) SetNillableDescription(v *string) *UpstreamGroupCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetMultiplier sets the "multiplier" field.
func (_c *UpstreamGroupCreate) SetMultiplier(v float64) *UpstreamGroupCreate {
	_c.mutation.SetMultiplier(v)
	return _c
}

// SetNillableMultiplier sets the "multiplier" field if the given value is not nil.
func (_c *UpstreamGroupCreate) SetNillableMultiplier(v *float64) *UpstreamGroupCreate {
	if v != nil {
		_c.SetMultiplier(*v)
	}
	return _c
}

// SetTodayTokens sets the "today_tokens" field.
func (_c *UpstreamGroupCreate) SetTodayTokens(v int64) *UpstreamGroupCreate {
	_c.mutation.SetTodayTokens(v)
	return _c
}

// SetNillableTodayTokens sets the "today_tokens" field if the given value is not nil.
func (_c *UpstreamGroupCreate) SetNillableTodayTokens(v *int64) *UpstreamGroupCreate {
	if v != nil {
		_c.SetTodayTokens(*v)
	}
	return _c
}

// SetTodayCostUsd sets the "today_cost_usd" field.
func (_c *UpstreamGroupCreate) SetTodayCostUsd(v float64) *UpstreamGroupCreate {
	_c.mutation.SetTodayCostUsd(v)
	return _c
}

// SetNillableTodayCostUsd sets the "today_cost_usd" field if the given value is not nil.
func (_c *UpstreamGroupCreate) SetNillableTodayCostUsd(v *float64) *UpstreamGroupCreate {
	if v != nil {
		_c.SetTodayCostUsd(*v)
	}
	return _c
}

// SetDisplayed sets the "displayed" field.
func (_c *UpstreamGroupCreate) SetDisplayed(v bool) *UpstreamGroupCreate {
	_c.mutation.SetDisplayed(v)
	return _c
}

// SetNillableDisplayed sets the "displayed" field if the given value is not nil.
func (_c *UpstreamGroupCreate) SetNillableDisplayed(v *bool) *UpstreamGroupCreate {
	if v != nil {
		_c.SetDisplayed(*v)
	}
	return _c
}

// SetAvailable sets the "available" field.
func (_c *UpstreamGroupCreate) SetAvailable(v bool) *UpstreamGroupCreate {
	_c.mutation.SetAvailable(v)
	return _c
}

// SetNillableAvailable sets the "available" field if the given value is not nil.
func (_c *UpstreamGroupCreate) SetNillableAvailable(v *bool) *UpstreamGroupCreate {
	if v != nil {
		_c.SetAvailable(*v)
	}
	return _c
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (_c *UpstreamGroupCreate) SetLastSyncedAt(v time.Time) *UpstreamGroupCreate {
	_c.mutation.SetLastSyncedAt(v)
	return _c
}

// SetNillableLastSyncedAt sets the "last_synced_at" field if the given value is not nil.
func (_c *UpstreamGroupCreate) SetNillableLastSyncedAt(v *time.Time) *UpstreamGroupCreate {
	if v != nil {
		_c.SetLastSyncedAt(*v)
	}
	return _c
}

// SetSite sets the "site" edge to the UpstreamSite entity.
func (_c *UpstreamGroupCreate) SetSite(v *UpstreamSite) *UpstreamGroupCreate {
	return _c.SetSiteID(v.ID)
}

// Mutation returns the UpstreamGroupMutation object of the builder.
func (_c *UpstreamGroupCreate) Mutation() *UpstreamGroupMutation {
	return _c.mutation
}

// Save creates the UpstreamGroup in the database.
func (_c *UpstreamGroupCreate) Save(ctx context.Context) (*UpstreamGroup, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UpstreamGroupCreate) SaveX(ctx context.Context) *UpstreamGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UpstreamGroupCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UpstreamGroupCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UpstreamGroupCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := upstreamgroup.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := upstreamgroup.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Platform(); !ok {
		v := upstreamgroup.DefaultPlatform
		_c.mutation.SetPlatform(v)
	}
	if _, ok := _c.mutation.Description(); !ok {
		v := upstreamgroup.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.TodayTokens(); !ok {
		v := upstreamgroup.DefaultTodayTokens
		_c.mutation.SetTodayTokens(v)
	}
	if _, ok := _c.mutation.TodayCostUsd(); !ok {
		v := upstreamgroup.DefaultTodayCostUsd
		_c.mutation.SetTodayCostUsd(v)
	}
	if _, ok := _c.mutation.Displayed(); !ok {
		v := upstreamgroup.DefaultDisplayed
		_c.mutation.SetDisplayed(v)
	}
	if _, ok := _c.mutation.Available(); !ok {
		v := upstreamgroup.DefaultAvailable
		_c.mutation.SetAvailable(v)
	}
	if _, ok := _c.mutation.LastSyncedAt(); !ok {
		v := upstreamgroup.DefaultLastSyncedAt()
		_c.mutation.SetLastSyncedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UpstreamGroupCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UpstreamGroup.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UpstreamGroup.updated_at"`)}
	}
	if _, ok := _c.mutation.SiteID(); !ok {
		return &ValidationError{Name: "site_id", err: errors.New(`ent: missing required field "UpstreamGroup.site_id"`)}
	}
	if _, ok := _c.mutation.RemoteID(); !ok {
		return &ValidationError{Name: "remote_id", err: errors.New(`ent: missing required field "UpstreamGroup.remote_id"`)}
	}
	if v, ok := _c.mutation.RemoteID(); ok {
		if err := upstreamgroup.RemoteIDValidator(v); err != nil {
			return &ValidationError{Name: "remote_id", err: fmt.Errorf(`ent: validator failed for field "UpstreamGroup.remote_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "UpstreamGroup.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := upstreamgroup.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "UpstreamGroup.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "UpstreamGroup.platform"`)}
	}
	if v, ok := _c.mutation.Platform(); ok {
		if err := upstreamgroup.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "UpstreamGroup.platform": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "UpstreamGroup.description"`)}
	}
	if _, ok := _c.mutation.TodayTokens(); !ok {
		return &ValidationError{Name: "today_tokens", err: errors.New(`ent: missing required field "UpstreamGroup.today_tokens"`)}
	}
	if _, ok := _c.mutation.TodayCostUsd(); !ok {
		return &ValidationError{Name: "today_cost_usd", err: errors.New(`ent: missing required field "UpstreamGroup.today_cost_usd"`)}
	}
	if _, ok := _c.mutation.Displayed(); !ok {
		return &ValidationError{Name: "displayed", err: errors.New(`ent: missing required field "UpstreamGroup.displayed"`)}
	}
	if _, ok := _c.mutation.Available(); !ok {
		return &ValidationError{Name: "available", err: errors.New(`ent: missing required field "UpstreamGroup.available"`)}
	}
	if _, ok := _c.mutation.LastSyncedAt(); !ok {
		return &ValidationError{Name: "last_synced_at", err: errors.New(`ent: missing required field "UpstreamGroup.last_synced_at"`)}
	}
	if len(_c.mutation.SiteIDs()) == 0 {
		return &ValidationError{Name: "site", err: errors.New(`ent: missing required edge "UpstreamGroup.site"`)}
	}
	return nil
}

func (_c *UpstreamGroupCreate) sqlSave(ctx context.Context) (*UpstreamGroup, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UpstreamGroupCreate) createSpec() (*UpstreamGroup, *sqlgraph.CreateSpec) {
	var (
		_node = &UpstreamGroup{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(upstreamgroup.Table, sqlgraph.NewFieldSpec(upstreamgroup.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(upstreamgroup.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(upstreamgroup.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.RemoteID(); ok {
		_spec.SetField(upstreamgroup.FieldRemoteID, field.TypeString, value)
		_node.RemoteID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(upstreamgroup.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Platform(); ok {
		_spec.SetField(upstreamgroup.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(upstreamgroup.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Multiplier(); ok {
		_spec.SetField(upstreamgroup.FieldMultiplier, field.TypeFloat64, value)
		_node.Multiplier = &value
	}
	if value, ok := _c.mutation.TodayTokens(); ok {
		_spec.SetField(upstreamgroup.FieldTodayTokens, field.TypeInt64, value)
		_node.TodayTokens = value
	}
	if value, ok := _c.mutation.TodayCostUsd(); ok {
		_spec.SetField(upstreamgroup.FieldTodayCostUsd, field.TypeFloat64, value)
		_node.TodayCostUsd = value
	}
	if value, ok := _c.mutation.Displayed(); ok {
		_spec.SetField(upstreamgroup.FieldDisplayed, field.TypeBool, value)
		_node.Displayed = value
	}
	if value, ok := _c.mutation.Available(); ok {
		_spec.SetField(upstreamgroup.FieldAvailable, field.TypeBool, value)
		_node.Available = value
	}
	if value, ok := _c.mutation.LastSyncedAt(); ok {
		_spec.SetField(upstreamgroup.FieldLastSyncedAt, field.TypeTime, value)
		_node.LastSyncedAt = value
	}
	if nodes := _c.mutation.SiteIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   upstreamgroup.SiteTable,
			Columns: []string{upstreamgroup.SiteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamsite.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SiteID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UpstreamGroup.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UpstreamGroupUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UpstreamGroupCreate) OnConflict(opts ...sql.ConflictOption) *UpstreamGroupUpsertOne {
	_c.conflict = opts
	return &UpstreamGroupUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UpstreamGroup.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UpstreamGroupCreate) OnConflictColumns(columns ...string) *UpstreamGroupUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UpstreamGroupUpsertOne{
		create: _c,
	}
}

type (
	// UpstreamGroupUpsertOne is the builder for "upsert"-ing
	//  one UpstreamGroup node.
	UpstreamGroupUpsertOne struct {
		create *UpstreamGroupCreate
	}

	// UpstreamGroupUpsert is the "OnConflict" setter.
	UpstreamGroupUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *UpstreamGroupUpsert) SetUpdatedAt(v time.Time) *UpstreamGroupUpsert {
	u.Set(upstreamgroup.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UpstreamGroupUpsert) UpdateUpdatedAt() *UpstreamGroupUpsert {
	u.SetExcluded(upstreamgroup.FieldUpdatedAt)
	return u
}

// SetSiteID sets the "site_id" field.
func (u *UpstreamGroupUpsert) SetSiteID(v int64) *UpstreamGroupUpsert {
	u.Set(upstreamgroup.FieldSiteID, v)
	return u
}

// UpdateSiteID sets the "site_id" field to the value that was provided on create.
func (u *UpstreamGroupUpsert) UpdateSiteID() *UpstreamGroupUpsert {
	u.SetExcluded(upstreamgroup.FieldSiteID)
	return u
}

// SetRemoteID sets the "remote_id" field.
func (u *UpstreamGroupUpsert) SetRemoteID(v string) *UpstreamGroupUpsert {
	u.Set(upstreamgroup.FieldRemoteID, v)
	return u
}

// UpdateRemoteID sets the "remote_id" field to the value that was provided on create.
func (u *UpstreamGroupUpsert) UpdateRemoteID() *UpstreamGroupUpsert {
	u.SetExcluded(upstreamgroup.FieldRemoteID)
	return u
}

// SetName sets the "name" field.
func (u *UpstreamGroupUpsert) SetName(v string) *UpstreamGroupUpsert {
	u.Set(upstreamgroup.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UpstreamGroupUpsert) UpdateName() *UpstreamGroupUpsert {
	u.SetExcluded(upstreamgroup.FieldName)
	return u
}

// SetPlatform sets the "platform" field.
func (u *UpstreamGroupUpsert) SetPlatform(v string) *UpstreamGroupUpsert {
	u.Set(upstreamgroup.FieldPlatform, v)
	return u
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *UpstreamGroupUpsert) UpdatePlatform() *UpstreamGroupUpsert {
	u.SetExcluded(upstreamgroup.FieldPlatform)
	return u
}

// SetDescription sets the "description" field.
func (u *UpstreamGroupUpsert) SetDescription(v string) *UpstreamGroupUpsert {
	u.Set(upstreamgroup.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *UpstreamGroupUpsert) UpdateDescription() *UpstreamGroupUpsert {
	u.SetExcluded(upstreamgroup.FieldDescription)
	return u
}

// SetMultiplier sets the "multiplier" field.
func (u *UpstreamGroupUpsert) SetMultiplier(v float64) *UpstreamGroupUpsert {
	u.Set(upstreamgroup.FieldMultiplier, v)
	return u
}

// UpdateMultiplier sets the "multiplier" field to the value that was provided on create.
func (u *UpstreamGroupUpsert) UpdateMultiplier() *UpstreamGroupUpsert {
	u.SetExcluded(upstreamgroup.FieldMultiplier)
	return u
}

// AddMultiplier adds v to the "multiplier" field.
func (u *UpstreamGroupUpsert) AddMultiplier(v float64) *UpstreamGroupUpsert {
	u.Add(upstreamgroup.FieldMultiplier, v)
	return u
}

// ClearMultiplier clears the value of the "multiplier" field.
func (u *UpstreamGroupUpsert) ClearMultiplier() *UpstreamGroupUpsert {
	u.SetNull(upstreamgroup.FieldMultiplier)
	return u
}

// SetTodayTokens sets the "today_tokens" field.
func (u *UpstreamGroupUpsert) SetTodayTokens(v int64) *UpstreamGroupUpsert {
	u.Set(upstreamgroup.FieldTodayTokens, v)
	return u
}

// UpdateTodayTokens sets the "today_tokens" field to the value that was provided on create.
func (u *UpstreamGroupUpsert) UpdateTodayTokens() *UpstreamGroupUpsert {
	u.SetExcluded(upstreamgroup.FieldTodayTokens)
	return u
}

// AddTodayTokens adds v to the "today_tokens" field.
func (u *UpstreamGroupUpsert) AddTodayTokens(v int64) *UpstreamGroupUpsert {
	u.Add(upstreamgroup.FieldTodayTokens, v)
	return u
}

// SetTodayCostUsd sets the "today_cost_usd" field.
func (u *UpstreamGroupUpsert) SetTodayCostUsd(v float64) *UpstreamGroupUpsert {
	u.Set(upstreamgroup.FieldTodayCostUsd, v)
	return u
}

// UpdateTodayCostUsd sets the "today_cost_usd" field to the value that was provided on create.
func (u *UpstreamGroupUpsert) UpdateTodayCostUsd() *UpstreamGroupUpsert {
	u.SetExcluded(upstreamgroup.FieldTodayCostUsd)
	return u
}

// AddTodayCostUsd adds v to the "today_cost_usd" field.
func (u *UpstreamGroupUpsert) AddTodayCostUsd(v float64) *UpstreamGroupUpsert {
	u.Add(upstreamgroup.FieldTodayCostUsd, v)
	return u
}

// SetDisplayed sets the "displayed" field.
func (u *UpstreamGroupUpsert) SetDisplayed(v bool) *UpstreamGroupUpsert {
	u.Set(upstreamgroup.FieldDisplayed, v)
	return u
}

// UpdateDisplayed sets the "displayed" field to the value that was provided on create.
func (u *UpstreamGroupUpsert) UpdateDisplayed() *UpstreamGroupUpsert {
	u.SetExcluded(upstreamgroup.FieldDisplayed)
	return u
}

// SetAvailable sets the "available" field.
func (u *UpstreamGroupUpsert) SetAvailable(v bool) *UpstreamGroupUpsert {
	u.Set(upstreamgroup.FieldAvailable, v)
	return u
}

// UpdateAvailable sets the "available" field to the value that was provided on create.
func (u *UpstreamGroupUpsert) UpdateAvailable() *UpstreamGroupUpsert {
	u.SetExcluded(upstreamgroup.FieldAvailable)
	return u
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (u *UpstreamGroupUpsert) SetLastSyncedAt(v time.Time) *UpstreamGroupUpsert {
	u.Set(upstreamgroup.FieldLastSyncedAt, v)
	return u
}

// UpdateLastSyncedAt sets the "last_synced_at" field to the value that was provided on create.
func (u *UpstreamGroupUpsert) UpdateLastSyncedAt() *UpstreamGroupUpsert {
	u.SetExcluded(upstreamgroup.FieldLastSyncedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UpstreamGroup.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UpstreamGroupUpsertOne) UpdateNewValues() *UpstreamGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(upstreamgroup.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UpstreamGroup.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UpstreamGroupUpsertOne) Ignore() *UpstreamGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UpstreamGroupUpsertOne) DoNothing() *UpstreamGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UpstreamGroupCreate.OnConflict
// documentation for more info.
func (u *UpstreamGroupUpsertOne) Update(set func(*UpstreamGroupUpsert)) *UpstreamGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UpstreamGroupUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UpstreamGroupUpsertOne) SetUpdatedAt(v time.Time) *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UpstreamGroupUpsertOne) UpdateUpdatedAt() *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetSiteID sets the "site_id" field.
func (u *UpstreamGroupUpsertOne) SetSiteID(v int64) *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.SetSiteID(v)
	})
}

// UpdateSiteID sets the "site_id" field to the value that was provided on create.
func (u *UpstreamGroupUpsertOne) UpdateSiteID() *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.UpdateSiteID()
	})
}

// SetRemoteID sets the "remote_id" field.
func (u *UpstreamGroupUpsertOne) SetRemoteID(v string) *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.SetRemoteID(v)
	})
}

// UpdateRemoteID sets the "remote_id" field to the value that was provided on create.
func (u *UpstreamGroupUpsertOne) UpdateRemoteID() *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.UpdateRemoteID()
	})
}

// SetName sets the "name" field.
func (u *UpstreamGroupUpsertOne) SetName(v string) *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UpstreamGroupUpsertOne) UpdateName() *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.UpdateName()
	})
}

// SetPlatform sets the "platform" field.
func (u *UpstreamGroupUpsertOne) SetPlatform(v string) *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *UpstreamGroupUpsertOne) UpdatePlatform() *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.UpdatePlatform()
	})
}

// SetDescription sets the "description" field.
func (u *UpstreamGroupUpsertOne) SetDescription(v string) *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *UpstreamGroupUpsertOne) UpdateDescription() *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.UpdateDescription()
	})
}

// SetMultiplier sets the "multiplier" field.
func (u *UpstreamGroupUpsertOne) SetMultiplier(v float64) *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.SetMultiplier(v)
	})
}

// AddMultiplier adds v to the "multiplier" field.
func (u *UpstreamGroupUpsertOne) AddMultiplier(v float64) *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.AddMultiplier(v)
	})
}

// UpdateMultiplier sets the "multiplier" field to the value that was provided on create.
func (u *UpstreamGroupUpsertOne) UpdateMultiplier() *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.UpdateMultiplier()
	})
}

// ClearMultiplier clears the value of the "multiplier" field.
func (u *UpstreamGroupUpsertOne) ClearMultiplier() *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.ClearMultiplier()
	})
}

// SetTodayTokens sets the "today_tokens" field.
func (u *UpstreamGroupUpsertOne) SetTodayTokens(v int64) *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.SetTodayTokens(v)
	})
}

// AddTodayTokens adds v to the "today_tokens" field.
func (u *UpstreamGroupUpsertOne) AddTodayTokens(v int64) *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.AddTodayTokens(v)
	})
}

// UpdateTodayTokens sets the "today_tokens" field to the value that was provided on create.
func (u *UpstreamGroupUpsertOne) UpdateTodayTokens() *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.UpdateTodayTokens()
	})
}

// SetTodayCostUsd sets the "today_cost_usd" field.
func (u *UpstreamGroupUpsertOne) SetTodayCostUsd(v float64) *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.SetTodayCostUsd(v)
	})
}

// AddTodayCostUsd adds v to the "today_cost_usd" field.
func (u *UpstreamGroupUpsertOne) AddTodayCostUsd(v float64) *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.AddTodayCostUsd(v)
	})
}

// UpdateTodayCostUsd sets the "today_cost_usd" field to the value that was provided on create.
func (u *UpstreamGroupUpsertOne) UpdateTodayCostUsd() *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.UpdateTodayCostUsd()
	})
}

// SetDisplayed sets the "displayed" field.
func (u *UpstreamGroupUpsertOne) SetDisplayed(v bool) *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.SetDisplayed(v)
	})
}

// UpdateDisplayed sets the "displayed" field to the value that was provided on create.
func (u *UpstreamGroupUpsertOne) UpdateDisplayed() *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.UpdateDisplayed()
	})
}

// SetAvailable sets the "available" field.
func (u *UpstreamGroupUpsertOne) SetAvailable(v bool) *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.SetAvailable(v)
	})
}

// UpdateAvailable sets the "available" field to the value that was provided on create.
func (u *UpstreamGroupUpsertOne) UpdateAvailable() *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.UpdateAvailable()
	})
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (u *UpstreamGroupUpsertOne) SetLastSyncedAt(v time.Time) *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.SetLastSyncedAt(v)
	})
}

// UpdateLastSyncedAt sets the "last_synced_at" field to the value that was provided on create.
func (u *UpstreamGroupUpsertOne) UpdateLastSyncedAt() *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.UpdateLastSyncedAt()
	})
}

// Exec executes the query.
func (u *UpstreamGroupUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UpstreamGroupCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UpstreamGroupUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UpstreamGroupUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UpstreamGroupUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UpstreamGroupCreateBulk is the builder for creating many UpstreamGroup entities in bulk.
type UpstreamGroupCreateBulk struct {
	config
	err      error
	builders []*UpstreamGroupCreate
	conflict []sql.ConflictOption
}

// Save creates the UpstreamGroup entities in the database.
func (_c *UpstreamGroupCreateBulk) Save(ctx context.Context) ([]*UpstreamGroup, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UpstreamGroup, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UpstreamGroupMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UpstreamGroupCreateBulk) SaveX(ctx context.Context) []*UpstreamGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UpstreamGroupCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UpstreamGroupCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UpstreamGroup.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UpstreamGroupUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UpstreamGroupCreateBulk) OnConflict(opts ...sql.ConflictOption) *UpstreamGroupUpsertBulk {
	_c.conflict = opts
	return &UpstreamGroupUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UpstreamGroup.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UpstreamGroupCreateBulk) OnConflictColumns(columns ...string) *UpstreamGroupUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UpstreamGroupUpsertBulk{
		create: _c,
	}
}

// UpstreamGroupUpsertBulk is the builder for "upsert"-ing
// a bulk of UpstreamGroup nodes.
type UpstreamGroupUpsertBulk struct {
	create *UpstreamGroupCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UpstreamGroup.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UpstreamGroupUpsertBulk) UpdateNewValues() *UpstreamGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(upstreamgroup.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UpstreamGroup.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UpstreamGroupUpsertBulk) Ignore() *UpstreamGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UpstreamGroupUpsertBulk) DoNothing() *UpstreamGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UpstreamGroupCreateBulk.OnConflict
// documentation for more info.
func (u *UpstreamGroupUpsertBulk) Update(set func(*UpstreamGroupUpsert)) *UpstreamGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UpstreamGroupUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UpstreamGroupUpsertBulk) SetUpdatedAt(v time.Time) *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UpstreamGroupUpsertBulk) UpdateUpdatedAt() *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetSiteID sets the "site_id" field.
func (u *UpstreamGroupUpsertBulk) SetSiteID(v int64) *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.SetSiteID(v)
	})
}

// UpdateSiteID sets the "site_id" field to the value that was provided on create.
func (u *UpstreamGroupUpsertBulk) UpdateSiteID() *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.UpdateSiteID()
	})
}

// SetRemoteID sets the "remote_id" field.
func (u *UpstreamGroupUpsertBulk) SetRemoteID(v string) *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.SetRemoteID(v)
	})
}

// UpdateRemoteID sets the "remote_id" field to the value that was provided on create.
func (u *UpstreamGroupUpsertBulk) UpdateRemoteID() *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.UpdateRemoteID()
	})
}

// SetName sets the "name" field.
func (u *UpstreamGroupUpsertBulk) SetName(v string) *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UpstreamGroupUpsertBulk) UpdateName() *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.UpdateName()
	})
}

// SetPlatform sets the "platform" field.
func (u *UpstreamGroupUpsertBulk) SetPlatform(v string) *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *UpstreamGroupUpsertBulk) UpdatePlatform() *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.UpdatePlatform()
	})
}

// SetDescription sets the "description" field.
func (u *UpstreamGroupUpsertBulk) SetDescription(v string) *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *UpstreamGroupUpsertBulk) UpdateDescription() *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.UpdateDescription()
	})
}

// SetMultiplier sets the "multiplier" field.
func (u *UpstreamGroupUpsertBulk) SetMultiplier(v float64) *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.SetMultiplier(v)
	})
}

// AddMultiplier adds v to the "multiplier" field.
func (u *UpstreamGroupUpsertBulk) AddMultiplier(v float64) *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.AddMultiplier(v)
	})
}

// UpdateMultiplier sets the "multiplier" field to the value that was provided on create.
func (u *UpstreamGroupUpsertBulk) UpdateMultiplier() *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.UpdateMultiplier()
	})
}

// ClearMultiplier clears the value of the "multiplier" field.
func (u *UpstreamGroupUpsertBulk) ClearMultiplier() *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.ClearMultiplier()
	})
}

// SetTodayTokens sets the "today_tokens" field.
func (u *UpstreamGroupUpsertBulk) SetTodayTokens(v int64) *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.SetTodayTokens(v)
	})
}

// AddTodayTokens adds v to the "today_tokens" field.
func (u *UpstreamGroupUpsertBulk) AddTodayTokens(v int64) *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.AddTodayTokens(v)
	})
}

// UpdateTodayTokens sets the "today_tokens" field to the value that was provided on create.
func (u *UpstreamGroupUpsertBulk) UpdateTodayTokens() *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.UpdateTodayTokens()
	})
}

// SetTodayCostUsd sets the "today_cost_usd" field.
func (u *UpstreamGroupUpsertBulk) SetTodayCostUsd(v float64) *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.SetTodayCostUsd(v)
	})
}

// AddTodayCostUsd adds v to the "today_cost_usd" field.
func (u *UpstreamGroupUpsertBulk) AddTodayCostUsd(v float64) *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.AddTodayCostUsd(v)
	})
}

// UpdateTodayCostUsd sets the "today_cost_usd" field to the value that was provided on create.
func (u *UpstreamGroupUpsertBulk) UpdateTodayCostUsd() *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.UpdateTodayCostUsd()
	})
}

// SetDisplayed sets the "displayed" field.
func (u *UpstreamGroupUpsertBulk) SetDisplayed(v bool) *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.SetDisplayed(v)
	})
}

// UpdateDisplayed sets the "displayed" field to the value that was provided on create.
func (u *UpstreamGroupUpsertBulk) UpdateDisplayed() *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.UpdateDisplayed()
	})
}

// SetAvailable sets the "available" field.
func (u *UpstreamGroupUpsertBulk) SetAvailable(v bool) *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.SetAvailable(v)
	})
}

// UpdateAvailable sets the "available" field to the value that was provided on create.
func (u *UpstreamGroupUpsertBulk) UpdateAvailable() *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.UpdateAvailable()
	})
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (u *UpstreamGroupUpsertBulk) SetLastSyncedAt(v time.Time) *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.SetLastSyncedAt(v)
	})
}

// UpdateLastSyncedAt sets the "last_synced_at" field to the value that was provided on create.
func (u *UpstreamGroupUpsertBulk) UpdateLastSyncedAt() *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.UpdateLastSyncedAt()
	})
}

// Exec executes the query.
func (u *UpstreamGroupUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UpstreamGroupCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UpstreamGroupCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UpstreamGroupUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
