// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/upstreamgroup"
	"github.com/Wei-Shaw/sub2api/ent/upstreamgroupaccountbinding"
	"github.com/Wei-Shaw/sub2api/ent/upstreamsite"
)

// UpstreamGroupUpdate is the builder for updating UpstreamGroup entities.
type UpstreamGroupUpdate struct {
	config
	hooks    []Hook
	mutation *UpstreamGroupMutation
}

// Where appends a list predicates to the UpstreamGroupUpdate builder.
func (_u *UpstreamGroupUpdate) Where(ps ...predicate.UpstreamGroup) *UpstreamGroupUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UpstreamGroupUpdate) SetUpdatedAt(v time.Time) *UpstreamGroupUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSiteID sets the "site_id" field.
func (_u *UpstreamGroupUpdate) SetSiteID(v int64) *UpstreamGroupUpdate {
	_u.mutation.SetSiteID(v)
	return _u
}

// SetNillableSiteID sets the "site_id" field if the given value is not nil.
func (_u *UpstreamGroupUpdate) SetNillableSiteID(v *int64) *UpstreamGroupUpdate {
	if v != nil {
		_u.SetSiteID(*v)
	}
	return _u
}

// SetRemoteID sets the "remote_id" field.
func (_u *UpstreamGroupUpdate) SetRemoteID(v string) *UpstreamGroupUpdate {
	_u.mutation.SetRemoteID(v)
	return _u
}

// SetNillableRemoteID sets the "remote_id" field if the given value is not nil.
func (_u *UpstreamGroupUpdate) SetNillableRemoteID(v *string) *UpstreamGroupUpdate {
	if v != nil {
		_u.SetRemoteID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *UpstreamGroupUpdate) SetName(v string) *UpstreamGroupUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UpstreamGroupUpdate) SetNillableName(v *string) *UpstreamGroupUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *UpstreamGroupUpdate) SetPlatform(v string) *UpstreamGroupUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *UpstreamGroupUpdate) SetNillablePlatform(v *string) *UpstreamGroupUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *UpstreamGroupUpdate) SetDescription(v string) *UpstreamGroupUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *UpstreamGroupUpdate) SetNillableDescription(v *string) *UpstreamGroupUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetMultiplier sets the "multiplier" field.
func (_u *UpstreamGroupUpdate) SetMultiplier(v float64) *UpstreamGroupUpdate {
	_u.mutation.ResetMultiplier()
	_u.mutation.SetMultiplier(v)
	return _u
}

// SetNillableMultiplier sets the "multiplier" field if the given value is not nil.
func (_u *UpstreamGroupUpdate) SetNillableMultiplier(v *float64) *UpstreamGroupUpdate {
	if v != nil {
		_u.SetMultiplier(*v)
	}
	return _u
}

// AddMultiplier adds value to the "multiplier" field.
func (_u *UpstreamGroupUpdate) AddMultiplier(v float64) *UpstreamGroupUpdate {
	_u.mutation.AddMultiplier(v)
	return _u
}

// ClearMultiplier clears the value of the "multiplier" field.
func (_u *UpstreamGroupUpdate) ClearMultiplier() *UpstreamGroupUpdate {
	_u.mutation.ClearMultiplier()
	return _u
}

// SetTodayTokens sets the "today_tokens" field.
func (_u *UpstreamGroupUpdate) SetTodayTokens(v int64) *UpstreamGroupUpdate {
	_u.mutation.ResetTodayTokens()
	_u.mutation.SetTodayTokens(v)
	return _u
}

// SetNillableTodayTokens sets the "today_tokens" field if the given value is not nil.
func (_u *UpstreamGroupUpdate) SetNillableTodayTokens(v *int64) *UpstreamGroupUpdate {
	if v != nil {
		_u.SetTodayTokens(*v)
	}
	return _u
}

// AddTodayTokens adds value to the "today_tokens" field.
func (_u *UpstreamGroupUpdate) AddTodayTokens(v int64) *UpstreamGroupUpdate {
	_u.mutation.AddTodayTokens(v)
	return _u
}

// SetTodayCostUsd sets the "today_cost_usd" field.
func (_u *UpstreamGroupUpdate) SetTodayCostUsd(v float64) *UpstreamGroupUpdate {
	_u.mutation.ResetTodayCostUsd()
	_u.mutation.SetTodayCostUsd(v)
	return _u
}

// SetNillableTodayCostUsd sets the "today_cost_usd" field if the given value is not nil.
func (_u *UpstreamGroupUpdate) SetNillableTodayCostUsd(v *float64) *UpstreamGroupUpdate {
	if v != nil {
		_u.SetTodayCostUsd(*v)
	}
	return _u
}

// AddTodayCostUsd adds value to the "today_cost_usd" field.
func (_u *UpstreamGroupUpdate) AddTodayCostUsd(v float64) *UpstreamGroupUpdate {
	_u.mutation.AddTodayCostUsd(v)
	return _u
}

// SetDisplayed sets the "displayed" field.
func (_u *UpstreamGroupUpdate) SetDisplayed(v bool) *UpstreamGroupUpdate {
	_u.mutation.SetDisplayed(v)
	return _u
}

// SetNillableDisplayed sets the "displayed" field if the given value is not nil.
func (_u *UpstreamGroupUpdate) SetNillableDisplayed(v *bool) *UpstreamGroupUpdate {
	if v != nil {
		_u.SetDisplayed(*v)
	}
	return _u
}

// SetAvailable sets the "available" field.
func (_u *UpstreamGroupUpdate) SetAvailable(v bool) *UpstreamGroupUpdate {
	_u.mutation.SetAvailable(v)
	return _u
}

// SetNillableAvailable sets the "available" field if the given value is not nil.
func (_u *UpstreamGroupUpdate) SetNillableAvailable(v *bool) *UpstreamGroupUpdate {
	if v != nil {
		_u.SetAvailable(*v)
	}
	return _u
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (_u *UpstreamGroupUpdate) SetLastSyncedAt(v time.Time) *UpstreamGroupUpdate {
	_u.mutation.SetLastSyncedAt(v)
	return _u
}

// SetNillableLastSyncedAt sets the "last_synced_at" field if the given value is not nil.
func (_u *UpstreamGroupUpdate) SetNillableLastSyncedAt(v *time.Time) *UpstreamGroupUpdate {
	if v != nil {
		_u.SetLastSyncedAt(*v)
	}
	return _u
}

// SetSite sets the "site" edge to the UpstreamSite entity.
func (_u *UpstreamGroupUpdate) SetSite(v *UpstreamSite) *UpstreamGroupUpdate {
	return _u.SetSiteID(v.ID)
}

// AddAccountBindingIDs adds the "account_bindings" edge to the UpstreamGroupAccountBinding entity by IDs.
func (_u *UpstreamGroupUpdate) AddAccountBindingIDs(ids ...int64) *UpstreamGroupUpdate {
	_u.mutation.AddAccountBindingIDs(ids...)
	return _u
}

// AddAccountBindings adds the "account_bindings" edges to the UpstreamGroupAccountBinding entity.
func (_u *UpstreamGroupUpdate) AddAccountBindings(v ...*UpstreamGroupAccountBinding) *UpstreamGroupUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAccountBindingIDs(ids...)
}

// Mutation returns the UpstreamGroupMutation object of the builder.
func (_u *UpstreamGroupUpdate) Mutation() *UpstreamGroupMutation {
	return _u.mutation
}

// ClearSite clears the "site" edge to the UpstreamSite entity.
func (_u *UpstreamGroupUpdate) ClearSite() *UpstreamGroupUpdate {
	_u.mutation.ClearSite()
	return _u
}

// ClearAccountBindings clears all "account_bindings" edges to the UpstreamGroupAccountBinding entity.
func (_u *UpstreamGroupUpdate) ClearAccountBindings() *UpstreamGroupUpdate {
	_u.mutation.ClearAccountBindings()
	return _u
}

// RemoveAccountBindingIDs removes the "account_bindings" edge to UpstreamGroupAccountBinding entities by IDs.
func (_u *UpstreamGroupUpdate) RemoveAccountBindingIDs(ids ...int64) *UpstreamGroupUpdate {
	_u.mutation.RemoveAccountBindingIDs(ids...)
	return _u
}

// RemoveAccountBindings removes "account_bindings" edges to UpstreamGroupAccountBinding entities.
func (_u *UpstreamGroupUpdate) RemoveAccountBindings(v ...*UpstreamGroupAccountBinding) *UpstreamGroupUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAccountBindingIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UpstreamGroupUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UpstreamGroupUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UpstreamGroupUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UpstreamGroupUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UpstreamGroupUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := upstreamgroup.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UpstreamGroupUpdate) check() error {
	if v, ok := _u.mutation.RemoteID(); ok {
		if err := upstreamgroup.RemoteIDValidator(v); err != nil {
			return &ValidationError{Name: "remote_id", err: fmt.Errorf(`ent: validator failed for field "UpstreamGroup.remote_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := upstreamgroup.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "UpstreamGroup.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := upstreamgroup.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "UpstreamGroup.platform": %w`, err)}
		}
	}
	if _u.mutation.SiteCleared() && len(_u.mutation.SiteIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UpstreamGroup.site"`)
	}
	return nil
}

func (_u *UpstreamGroupUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(upstreamgroup.Table, upstreamgroup.Columns, sqlgraph.NewFieldSpec(upstreamgroup.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(upstreamgroup.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RemoteID(); ok {
		_spec.SetField(upstreamgroup.FieldRemoteID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(upstreamgroup.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(upstreamgroup.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(upstreamgroup.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Multiplier(); ok {
		_spec.SetField(upstreamgroup.FieldMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMultiplier(); ok {
		_spec.AddField(upstreamgroup.FieldMultiplier, field.TypeFloat64, value)
	}
	if _u.mutation.MultiplierCleared() {
		_spec.ClearField(upstreamgroup.FieldMultiplier, field.TypeFloat64)
	}
	if value, ok := _u.mutation.TodayTokens(); ok {
		_spec.SetField(upstreamgroup.FieldTodayTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTodayTokens(); ok {
		_spec.AddField(upstreamgroup.FieldTodayTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TodayCostUsd(); ok {
		_spec.SetField(upstreamgroup.FieldTodayCostUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTodayCostUsd(); ok {
		_spec.AddField(upstreamgroup.FieldTodayCostUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Displayed(); ok {
		_spec.SetField(upstreamgroup.FieldDisplayed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Available(); ok {
		_spec.SetField(upstreamgroup.FieldAvailable, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastSyncedAt(); ok {
		_spec.SetField(upstreamgroup.FieldLastSyncedAt, field.TypeTime, value)
	}
	if _u.mutation.SiteCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   upstreamgroup.SiteTable,
			Columns: []string{upstreamgroup.SiteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamsite.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SiteIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   upstreamgroup.SiteTable,
			Columns: []string{upstreamgroup.SiteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamsite.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccountBindingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreamgroup.AccountBindingsTable,
			Columns: []string{upstreamgroup.AccountBindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamgroupaccountbinding.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAccountBindingsIDs(); len(nodes) > 0 && !_u.mutation.AccountBindingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreamgroup.AccountBindingsTable,
			Columns: []string{upstreamgroup.AccountBindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamgroupaccountbinding.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountBindingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreamgroup.AccountBindingsTable,
			Columns: []string{upstreamgroup.AccountBindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamgroupaccountbinding.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upstreamgroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UpstreamGroupUpdateOne is the builder for updating a single UpstreamGroup entity.
type UpstreamGroupUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UpstreamGroupMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UpstreamGroupUpdateOne) SetUpdatedAt(v time.Time) *UpstreamGroupUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSiteID sets the "site_id" field.
func (_u *UpstreamGroupUpdateOne) SetSiteID(v int64) *UpstreamGroupUpdateOne {
	_u.mutation.SetSiteID(v)
	return _u
}

// SetNillableSiteID sets the "site_id" field if the given value is not nil.
func (_u *UpstreamGroupUpdateOne) SetNillableSiteID(v *int64) *UpstreamGroupUpdateOne {
	if v != nil {
		_u.SetSiteID(*v)
	}
	return _u
}

// SetRemoteID sets the "remote_id" field.
func (_u *UpstreamGroupUpdateOne) SetRemoteID(v string) *UpstreamGroupUpdateOne {
	_u.mutation.SetRemoteID(v)
	return _u
}

// SetNillableRemoteID sets the "remote_id" field if the given value is not nil.
func (_u *UpstreamGroupUpdateOne) SetNillableRemoteID(v *string) *UpstreamGroupUpdateOne {
	if v != nil {
		_u.SetRemoteID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *UpstreamGroupUpdateOne) SetName(v string) *UpstreamGroupUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UpstreamGroupUpdateOne) SetNillableName(v *string) *UpstreamGroupUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *UpstreamGroupUpdateOne) SetPlatform(v string) *UpstreamGroupUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *UpstreamGroupUpdateOne) SetNillablePlatform(v *string) *UpstreamGroupUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *UpstreamGroupUpdateOne) SetDescription(v string) *UpstreamGroupUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *UpstreamGroupUpdateOne) SetNillableDescription(v *string) *UpstreamGroupUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetMultiplier sets the "multiplier" field.
func (_u *UpstreamGroupUpdateOne) SetMultiplier(v float64) *UpstreamGroupUpdateOne {
	_u.mutation.ResetMultiplier()
	_u.mutation.SetMultiplier(v)
	return _u
}

// SetNillableMultiplier sets the "multiplier" field if the given value is not nil.
func (_u *UpstreamGroupUpdateOne) SetNillableMultiplier(v *float64) *UpstreamGroupUpdateOne {
	if v != nil {
		_u.SetMultiplier(*v)
	}
	return _u
}

// AddMultiplier adds value to the "multiplier" field.
func (_u *UpstreamGroupUpdateOne) AddMultiplier(v float64) *UpstreamGroupUpdateOne {
	_u.mutation.AddMultiplier(v)
	return _u
}

// ClearMultiplier clears the value of the "multiplier" field.
func (_u *UpstreamGroupUpdateOne) ClearMultiplier() *UpstreamGroupUpdateOne {
	_u.mutation.ClearMultiplier()
	return _u
}

// SetTodayTokens sets the "today_tokens" field.
func (_u *UpstreamGroupUpdateOne) SetTodayTokens(v int64) *UpstreamGroupUpdateOne {
	_u.mutation.ResetTodayTokens()
	_u.mutation.SetTodayTokens(v)
	return _u
}

// SetNillableTodayTokens sets the "today_tokens" field if the given value is not nil.
func (_u *UpstreamGroupUpdateOne) SetNillableTodayTokens(v *int64) *UpstreamGroupUpdateOne {
	if v != nil {
		_u.SetTodayTokens(*v)
	}
	return _u
}

// AddTodayTokens adds value to the "today_tokens" field.
func (_u *UpstreamGroupUpdateOne) AddTodayTokens(v int64) *UpstreamGroupUpdateOne {
	_u.mutation.AddTodayTokens(v)
	return _u
}

// SetTodayCostUsd sets the "today_cost_usd" field.
func (_u *UpstreamGroupUpdateOne) SetTodayCostUsd(v float64) *UpstreamGroupUpdateOne {
	_u.mutation.ResetTodayCostUsd()
	_u.mutation.SetTodayCostUsd(v)
	return _u
}

// SetNillableTodayCostUsd sets the "today_cost_usd" field if the given value is not nil.
func (_u *UpstreamGroupUpdateOne) SetNillableTodayCostUsd(v *float64) *UpstreamGroupUpdateOne {
	if v != nil {
		_u.SetTodayCostUsd(*v)
	}
	return _u
}

// AddTodayCostUsd adds value to the "today_cost_usd" field.
func (_u *UpstreamGroupUpdateOne) AddTodayCostUsd(v float64) *UpstreamGroupUpdateOne {
	_u.mutation.AddTodayCostUsd(v)
	return _u
}

// SetDisplayed sets the "displayed" field.
func (_u *UpstreamGroupUpdateOne) SetDisplayed(v bool) *UpstreamGroupUpdateOne {
	_u.mutation.SetDisplayed(v)
	return _u
}

// SetNillableDisplayed sets the "displayed" field if the given value is not nil.
func (_u *UpstreamGroupUpdateOne) SetNillableDisplayed(v *bool) *UpstreamGroupUpdateOne {
	if v != nil {
		_u.SetDisplayed(*v)
	}
	return _u
}

// SetAvailable sets the "available" field.
func (_u *UpstreamGroupUpdateOne) SetAvailable(v bool) *UpstreamGroupUpdateOne {
	_u.mutation.SetAvailable(v)
	return _u
}

// SetNillableAvailable sets the "available" field if the given value is not nil.
func (_u *UpstreamGroupUpdateOne) SetNillableAvailable(v *bool) *UpstreamGroupUpdateOne {
	if v != nil {
		_u.SetAvailable(*v)
	}
	return _u
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (_u *UpstreamGroupUpdateOne) SetLastSyncedAt(v time.Time) *UpstreamGroupUpdateOne {
	_u.mutation.SetLastSyncedAt(v)
	return _u
}

// SetNillableLastSyncedAt sets the "last_synced_at" field if the given value is not nil.
func (_u *UpstreamGroupUpdateOne) SetNillableLastSyncedAt(v *time.Time) *UpstreamGroupUpdateOne {
	if v != nil {
		_u.SetLastSyncedAt(*v)
	}
	return _u
}

// SetSite sets the "site" edge to the UpstreamSite entity.
func (_u *UpstreamGroupUpdateOne) SetSite(v *UpstreamSite) *UpstreamGroupUpdateOne {
	return _u.SetSiteID(v.ID)
}

// AddAccountBindingIDs adds the "account_bindings" edge to the UpstreamGroupAccountBinding entity by IDs.
func (_u *UpstreamGroupUpdateOne) AddAccountBindingIDs(ids ...int64) *UpstreamGroupUpdateOne {
	_u.mutation.AddAccountBindingIDs(ids...)
	return _u
}

// AddAccountBindings adds the "account_bindings" edges to the UpstreamGroupAccountBinding entity.
func (_u *UpstreamGroupUpdateOne) AddAccountBindings(v ...*UpstreamGroupAccountBinding) *UpstreamGroupUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAccountBindingIDs(ids...)
}

// Mutation returns the UpstreamGroupMutation object of the builder.
func (_u *UpstreamGroupUpdateOne) Mutation() *UpstreamGroupMutation {
	return _u.mutation
}

// ClearSite clears the "site" edge to the UpstreamSite entity.
func (_u *UpstreamGroupUpdateOne) ClearSite() *UpstreamGroupUpdateOne {
	_u.mutation.ClearSite()
	return _u
}

// ClearAccountBindings clears all "account_bindings" edges to the UpstreamGroupAccountBinding entity.
func (_u *UpstreamGroupUpdateOne) ClearAccountBindings() *UpstreamGroupUpdateOne {
	_u.mutation.ClearAccountBindings()
	return _u
}

// RemoveAccountBindingIDs removes the "account_bindings" edge to UpstreamGroupAccountBinding entities by IDs.
func (_u *UpstreamGroupUpdateOne) RemoveAccountBindingIDs(ids ...int64) *UpstreamGroupUpdateOne {
	_u.mutation.RemoveAccountBindingIDs(ids...)
	return _u
}

// RemoveAccountBindings removes "account_bindings" edges to UpstreamGroupAccountBinding entities.
func (_u *UpstreamGroupUpdateOne) RemoveAccountBindings(v ...*UpstreamGroupAccountBinding) *UpstreamGroupUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAccountBindingIDs(ids...)
}

// Where appends a list predicates to the UpstreamGroupUpdate builder.
func (_u *UpstreamGroupUpdateOne) Where(ps ...predicate.UpstreamGroup) *UpstreamGroupUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UpstreamGroupUpdateOne) Select(field string, fields ...string) *UpstreamGroupUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UpstreamGroup entity.
func (_u *UpstreamGroupUpdateOne) Save(ctx context.Context) (*UpstreamGroup, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UpstreamGroupUpdateOne) SaveX(ctx context.Context) *UpstreamGroup {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UpstreamGroupUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UpstreamGroupUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UpstreamGroupUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := upstreamgroup.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UpstreamGroupUpdateOne) check() error {
	if v, ok := _u.mutation.RemoteID(); ok {
		if err := upstreamgroup.RemoteIDValidator(v); err != nil {
			return &ValidationError{Name: "remote_id", err: fmt.Errorf(`ent: validator failed for field "UpstreamGroup.remote_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := upstreamgroup.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "UpstreamGroup.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := upstreamgroup.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "UpstreamGroup.platform": %w`, err)}
		}
	}
	if _u.mutation.SiteCleared() && len(_u.mutation.SiteIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UpstreamGroup.site"`)
	}
	return nil
}

func (_u *UpstreamGroupUpdateOne) sqlSave(ctx context.Context) (_node *UpstreamGroup, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(upstreamgroup.Table, upstreamgroup.Columns, sqlgraph.NewFieldSpec(upstreamgroup.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UpstreamGroup.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, upstreamgroup.FieldID)
		for _, f := range fields {
			if !upstreamgroup.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != upstreamgroup.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(upstreamgroup.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RemoteID(); ok {
		_spec.SetField(upstreamgroup.FieldRemoteID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(upstreamgroup.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(upstreamgroup.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(upstreamgroup.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Multiplier(); ok {
		_spec.SetField(upstreamgroup.FieldMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMultiplier(); ok {
		_spec.AddField(upstreamgroup.FieldMultiplier, field.TypeFloat64, value)
	}
	if _u.mutation.MultiplierCleared() {
		_spec.ClearField(upstreamgroup.FieldMultiplier, field.TypeFloat64)
	}
	if value, ok := _u.mutation.TodayTokens(); ok {
		_spec.SetField(upstreamgroup.FieldTodayTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTodayTokens(); ok {
		_spec.AddField(upstreamgroup.FieldTodayTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TodayCostUsd(); ok {
		_spec.SetField(upstreamgroup.FieldTodayCostUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTodayCostUsd(); ok {
		_spec.AddField(upstreamgroup.FieldTodayCostUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Displayed(); ok {
		_spec.SetField(upstreamgroup.FieldDisplayed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Available(); ok {
		_spec.SetField(upstreamgroup.FieldAvailable, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastSyncedAt(); ok {
		_spec.SetField(upstreamgroup.FieldLastSyncedAt, field.TypeTime, value)
	}
	if _u.mutation.SiteCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   upstreamgroup.SiteTable,
			Columns: []string{upstreamgroup.SiteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamsite.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SiteIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   upstreamgroup.SiteTable,
			Columns: []string{upstreamgroup.SiteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamsite.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccountBindingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreamgroup.AccountBindingsTable,
			Columns: []string{upstreamgroup.AccountBindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamgroupaccountbinding.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAccountBindingsIDs(); len(nodes) > 0 && !_u.mutation.AccountBindingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreamgroup.AccountBindingsTable,
			Columns: []string{upstreamgroup.AccountBindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamgroupaccountbinding.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountBindingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreamgroup.AccountBindingsTable,
			Columns: []string{upstreamgroup.AccountBindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamgroupaccountbinding.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UpstreamGroup{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upstreamgroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
