// Code generated by ent, DO NOT EDIT.

package upstreamgroupaccountbinding

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the upstreamgroupaccountbinding type in the database.
	Label = "upstream_group_account_binding"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUpstreamGroupID holds the string denoting the upstream_group_id field in the database.
	FieldUpstreamGroupID = "upstream_group_id"
	// FieldLocalGroupID holds the string denoting the local_group_id field in the database.
	FieldLocalGroupID = "local_group_id"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeUpstreamGroup holds the string denoting the upstream_group edge name in mutations.
	EdgeUpstreamGroup = "upstream_group"
	// EdgeLocalGroup holds the string denoting the local_group edge name in mutations.
	EdgeLocalGroup = "local_group"
	// EdgeAccount holds the string denoting the account edge name in mutations.
	EdgeAccount = "account"
	// Table holds the table name of the upstreamgroupaccountbinding in the database.
	Table = "upstream_group_account_bindings"
	// UpstreamGroupTable is the table that holds the upstream_group relation/edge.
	UpstreamGroupTable = "upstream_group_account_bindings"
	// UpstreamGroupInverseTable is the table name for the UpstreamGroup entity.
	// It exists in this package in order to avoid circular dependency with the "upstreamgroup" package.
	UpstreamGroupInverseTable = "upstream_groups"
	// UpstreamGroupColumn is the table column denoting the upstream_group relation/edge.
	UpstreamGroupColumn = "upstream_group_id"
	// LocalGroupTable is the table that holds the local_group relation/edge.
	LocalGroupTable = "upstream_group_account_bindings"
	// LocalGroupInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	LocalGroupInverseTable = "groups"
	// LocalGroupColumn is the table column denoting the local_group relation/edge.
	LocalGroupColumn = "local_group_id"
	// AccountTable is the table that holds the account relation/edge.
	AccountTable = "upstream_group_account_bindings"
	// AccountInverseTable is the table name for the Account entity.
	// It exists in this package in order to avoid circular dependency with the "account" package.
	AccountInverseTable = "accounts"
	// AccountColumn is the table column denoting the account relation/edge.
	AccountColumn = "account_id"
)

// Columns holds all SQL columns for upstreamgroupaccountbinding fields.
var Columns = []string{
	FieldID,
	FieldUpstreamGroupID,
	FieldLocalGroupID,
	FieldAccountID,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the UpstreamGroupAccountBinding queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUpstreamGroupID orders the results by the upstream_group_id field.
func ByUpstreamGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamGroupID, opts...).ToFunc()
}

// ByLocalGroupID orders the results by the local_group_id field.
func ByLocalGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLocalGroupID, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpstreamGroupField orders the results by upstream_group field.
func ByUpstreamGroupField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUpstreamGroupStep(), sql.OrderByField(field, opts...))
	}
}

// ByLocalGroupField orders the results by local_group field.
func ByLocalGroupField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLocalGroupStep(), sql.OrderByField(field, opts...))
	}
}

// ByAccountField orders the results by account field.
func ByAccountField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAccountStep(), sql.OrderByField(field, opts...))
	}
}
func newUpstreamGroupStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UpstreamGroupInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UpstreamGroupTable, UpstreamGroupColumn),
	)
}
func newLocalGroupStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LocalGroupInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, LocalGroupTable, LocalGroupColumn),
	)
}
func newAccountStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AccountInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, AccountTable, AccountColumn),
	)
}
