// Code generated by ent, DO NOT EDIT.

package upstreamgroupaccountbinding

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UpstreamGroupAccountBinding {
	return predicate.UpstreamGroupAccountBinding(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UpstreamGroupAccountBinding {
	return predicate.UpstreamGroupAccountBinding(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UpstreamGroupAccountBinding {
	return predicate.UpstreamGroupAccountBinding(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UpstreamGroupAccountBinding {
	return predicate.UpstreamGroupAccountBinding(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UpstreamGroupAccountBinding {
	return predicate.UpstreamGroupAccountBinding(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UpstreamGroupAccountBinding {
	return predicate.UpstreamGroupAccountBinding(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UpstreamGroupAccountBinding {
	return predicate.UpstreamGroupAccountBinding(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UpstreamGroupAccountBinding {
	return predicate.UpstreamGroupAccountBinding(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UpstreamGroupAccountBinding {
	return predicate.UpstreamGroupAccountBinding(sql.FieldLTE(FieldID, id))
}

// UpstreamGroupID applies equality check predicate on the "upstream_group_id" field. It's identical to UpstreamGroupIDEQ.
func UpstreamGroupID(v int64) predicate.UpstreamGroupAccountBinding {
	return predicate.UpstreamGroupAccountBinding(sql.FieldEQ(FieldUpstreamGroupID, v))
}

// LocalGroupID applies equality check predicate on the "local_group_id" field. It's identical to LocalGroupIDEQ.
func LocalGroupID(v int64) predicate.UpstreamGroupAccountBinding {
	return predicate.UpstreamGroupAccountBinding(sql.FieldEQ(FieldLocalGroupID, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.UpstreamGroupAccountBinding {
	return predicate.UpstreamGroupAccountBinding(sql.FieldEQ(FieldAccountID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UpstreamGroupAccountBinding {
	return predicate.UpstreamGroupAccountBinding(sql.FieldEQ(FieldCreatedAt, v))
}

// UpstreamGroupIDEQ applies the EQ predicate on the "upstream_group_id" field.
func UpstreamGroupIDEQ(v int64) predicate.UpstreamGroupAccountBinding {
	return predicate.UpstreamGroupAccountBinding(sql.FieldEQ(FieldUpstreamGroupID, v))
}

// UpstreamGroupIDNEQ applies the NEQ predicate on the "upstream_group_id" field.
func UpstreamGroupIDNEQ(v int64) predicate.UpstreamGroupAccountBinding {
	return predicate.UpstreamGroupAccountBinding(sql.FieldNEQ(FieldUpstreamGroupID, v))
}

// UpstreamGroupIDIn applies the In predicate on the "upstream_group_id" field.
func UpstreamGroupIDIn(vs ...int64) predicate.UpstreamGroupAccountBinding {
	return predicate.UpstreamGroupAccountBinding(sql.FieldIn(FieldUpstreamGroupID, vs...))
}

// UpstreamGroupIDNotIn applies the NotIn predicate on the "upstream_group_id" field.
func UpstreamGroupIDNotIn(vs ...int64) predicate.UpstreamGroupAccountBinding {
	return predicate.UpstreamGroupAccountBinding(sql.FieldNotIn(FieldUpstreamGroupID, vs...))
}

// LocalGroupIDEQ applies the EQ predicate on the "local_group_id" field.
func LocalGroupIDEQ(v int64) predicate.UpstreamGroupAccountBinding {
	return predicate.UpstreamGroupAccountBinding(sql.FieldEQ(FieldLocalGroupID, v))
}

// LocalGroupIDNEQ applies the NEQ predicate on the "local_group_id" field.
func LocalGroupIDNEQ(v int64) predicate.UpstreamGroupAccountBinding {
	return predicate.UpstreamGroupAccountBinding(sql.FieldNEQ(FieldLocalGroupID, v))
}

// LocalGroupIDIn applies the In predicate on the "local_group_id" field.
func LocalGroupIDIn(vs ...int64) predicate.UpstreamGroupAccountBinding {
	return predicate.UpstreamGroupAccountBinding(sql.FieldIn(FieldLocalGroupID, vs...))
}

// LocalGroupIDNotIn applies the NotIn predicate on the "local_group_id" field.
func LocalGroupIDNotIn(vs ...int64) predicate.UpstreamGroupAccountBinding {
	return predicate.UpstreamGroupAccountBinding(sql.FieldNotIn(FieldLocalGroupID, vs...))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.UpstreamGroupAccountBinding {
	return predicate.UpstreamGroupAccountBinding(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.UpstreamGroupAccountBinding {
	return predicate.UpstreamGroupAccountBinding(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.UpstreamGroupAccountBinding {
	return predicate.UpstreamGroupAccountBinding(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.UpstreamGroupAccountBinding {
	return predicate.UpstreamGroupAccountBinding(sql.FieldNotIn(FieldAccountID, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UpstreamGroupAccountBinding {
	return predicate.UpstreamGroupAccountBinding(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UpstreamGroupAccountBinding {
	return predicate.UpstreamGroupAccountBinding(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UpstreamGroupAccountBinding {
	return predicate.UpstreamGroupAccountBinding(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UpstreamGroupAccountBinding {
	return predicate.UpstreamGroupAccountBinding(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UpstreamGroupAccountBinding {
	return predicate.UpstreamGroupAccountBinding(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UpstreamGroupAccountBinding {
	return predicate.UpstreamGroupAccountBinding(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UpstreamGroupAccountBinding {
	return predicate.UpstreamGroupAccountBinding(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UpstreamGroupAccountBinding {
	return predicate.UpstreamGroupAccountBinding(sql.FieldLTE(FieldCreatedAt, v))
}

// HasUpstreamGroup applies the HasEdge predicate on the "upstream_group" edge.
func HasUpstreamGroup() predicate.UpstreamGroupAccountBinding {
	return predicate.UpstreamGroupAccountBinding(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UpstreamGroupTable, UpstreamGroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUpstreamGroupWith applies the HasEdge predicate on the "upstream_group" edge with a given conditions (other predicates).
func HasUpstreamGroupWith(preds ...predicate.UpstreamGroup) predicate.UpstreamGroupAccountBinding {
	return predicate.UpstreamGroupAccountBinding(func(s *sql.Selector) {
		step := newUpstreamGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasLocalGroup applies the HasEdge predicate on the "local_group" edge.
func HasLocalGroup() predicate.UpstreamGroupAccountBinding {
	return predicate.UpstreamGroupAccountBinding(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, LocalGroupTable, LocalGroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLocalGroupWith applies the HasEdge predicate on the "local_group" edge with a given conditions (other predicates).
func HasLocalGroupWith(preds ...predicate.Group) predicate.UpstreamGroupAccountBinding {
	return predicate.UpstreamGroupAccountBinding(func(s *sql.Selector) {
		step := newLocalGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAccount applies the HasEdge predicate on the "account" edge.
func HasAccount() predicate.UpstreamGroupAccountBinding {
	return predicate.UpstreamGroupAccountBinding(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, AccountTable, AccountColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountWith applies the HasEdge predicate on the "account" edge with a given conditions (other predicates).
func HasAccountWith(preds ...predicate.Account) predicate.UpstreamGroupAccountBinding {
	return predicate.UpstreamGroupAccountBinding(func(s *sql.Selector) {
		step := newAccountStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UpstreamGroupAccountBinding) predicate.UpstreamGroupAccountBinding {
	return predicate.UpstreamGroupAccountBinding(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UpstreamGroupAccountBinding) predicate.UpstreamGroupAccountBinding {
	return predicate.UpstreamGroupAccountBinding(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UpstreamGroupAccountBinding) predicate.UpstreamGroupAccountBinding {
	return predicate.UpstreamGroupAccountBinding(sql.NotPredicates(p))
}
