// Code generated by ent, DO NOT EDIT.

package upstreamdailystat

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the upstreamdailystat type in the database.
	Label = "upstream_daily_stat"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSiteID holds the string denoting the site_id field in the database.
	FieldSiteID = "site_id"
	// FieldUsageDate holds the string denoting the usage_date field in the database.
	FieldUsageDate = "usage_date"
	// FieldBalanceUsd holds the string denoting the balance_usd field in the database.
	FieldBalanceUsd = "balance_usd"
	// FieldTokens holds the string denoting the tokens field in the database.
	FieldTokens = "tokens"
	// FieldCostUsd holds the string denoting the cost_usd field in the database.
	FieldCostUsd = "cost_usd"
	// FieldCostBasisVersion holds the string denoting the cost_basis_version field in the database.
	FieldCostBasisVersion = "cost_basis_version"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeSite holds the string denoting the site edge name in mutations.
	EdgeSite = "site"
	// Table holds the table name of the upstreamdailystat in the database.
	Table = "upstream_daily_stats"
	// SiteTable is the table that holds the site relation/edge.
	SiteTable = "upstream_daily_stats"
	// SiteInverseTable is the table name for the UpstreamSite entity.
	// It exists in this package in order to avoid circular dependency with the "upstreamsite" package.
	SiteInverseTable = "upstream_sites"
	// SiteColumn is the table column denoting the site relation/edge.
	SiteColumn = "site_id"
)

// Columns holds all SQL columns for upstreamdailystat fields.
var Columns = []string{
	FieldID,
	FieldSiteID,
	FieldUsageDate,
	FieldBalanceUsd,
	FieldTokens,
	FieldCostUsd,
	FieldCostBasisVersion,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultTokens holds the default value on creation for the "tokens" field.
	DefaultTokens int64
	// DefaultCostUsd holds the default value on creation for the "cost_usd" field.
	DefaultCostUsd float64
	// DefaultCostBasisVersion holds the default value on creation for the "cost_basis_version" field.
	DefaultCostBasisVersion int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the UpstreamDailyStat queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySiteID orders the results by the site_id field.
func BySiteID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSiteID, opts...).ToFunc()
}

// ByUsageDate orders the results by the usage_date field.
func ByUsageDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsageDate, opts...).ToFunc()
}

// ByBalanceUsd orders the results by the balance_usd field.
func ByBalanceUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalanceUsd, opts...).ToFunc()
}

// ByTokens orders the results by the tokens field.
func ByTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokens, opts...).ToFunc()
}

// ByCostUsd orders the results by the cost_usd field.
func ByCostUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCostUsd, opts...).ToFunc()
}

// ByCostBasisVersion orders the results by the cost_basis_version field.
func ByCostBasisVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCostBasisVersion, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// BySiteField orders the results by site field.
func BySiteField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSiteStep(), sql.OrderByField(field, opts...))
	}
}
func newSiteStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SiteInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SiteTable, SiteColumn),
	)
}
