// Code generated by ent, DO NOT EDIT.

package upstreamsite

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldEQ(FieldUpdatedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldEQ(FieldName, v))
}

// BaseURL applies equality check predicate on the "base_url" field. It's identical to BaseURLEQ.
func BaseURL(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldEQ(FieldBaseURL, v))
}

// Account applies equality check predicate on the "account" field. It's identical to AccountEQ.
func Account(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldEQ(FieldAccount, v))
}

// CredentialEncrypted applies equality check predicate on the "credential_encrypted" field. It's identical to CredentialEncryptedEQ.
func CredentialEncrypted(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldEQ(FieldCredentialEncrypted, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldEQ(FieldEnabled, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldEQ(FieldErrorMessage, v))
}

// BalanceUsd applies equality check predicate on the "balance_usd" field. It's identical to BalanceUsdEQ.
func BalanceUsd(v float64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldEQ(FieldBalanceUsd, v))
}

// TodayTokens applies equality check predicate on the "today_tokens" field. It's identical to TodayTokensEQ.
func TodayTokens(v int64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldEQ(FieldTodayTokens, v))
}

// TodayCostUsd applies equality check predicate on the "today_cost_usd" field. It's identical to TodayCostUsdEQ.
func TodayCostUsd(v float64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldEQ(FieldTodayCostUsd, v))
}

// TotalTokens applies equality check predicate on the "total_tokens" field. It's identical to TotalTokensEQ.
func TotalTokens(v int64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldEQ(FieldTotalTokens, v))
}

// TotalCostUsd applies equality check predicate on the "total_cost_usd" field. It's identical to TotalCostUsdEQ.
func TotalCostUsd(v float64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldEQ(FieldTotalCostUsd, v))
}

// TrackingStartedAt applies equality check predicate on the "tracking_started_at" field. It's identical to TrackingStartedAtEQ.
func TrackingStartedAt(v time.Time) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldEQ(FieldTrackingStartedAt, v))
}

// LastSyncedAt applies equality check predicate on the "last_synced_at" field. It's identical to LastSyncedAtEQ.
func LastSyncedAt(v time.Time) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldEQ(FieldLastSyncedAt, v))
}

// NextSyncAt applies equality check predicate on the "next_sync_at" field. It's identical to NextSyncAtEQ.
func NextSyncAt(v time.Time) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldEQ(FieldNextSyncAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v int64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldLTE(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldContainsFold(FieldName, v))
}

// BaseURLEQ applies the EQ predicate on the "base_url" field.
func BaseURLEQ(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldEQ(FieldBaseURL, v))
}

// BaseURLNEQ applies the NEQ predicate on the "base_url" field.
func BaseURLNEQ(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldNEQ(FieldBaseURL, v))
}

// BaseURLIn applies the In predicate on the "base_url" field.
func BaseURLIn(vs ...string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldIn(FieldBaseURL, vs...))
}

// BaseURLNotIn applies the NotIn predicate on the "base_url" field.
func BaseURLNotIn(vs ...string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldNotIn(FieldBaseURL, vs...))
}

// BaseURLGT applies the GT predicate on the "base_url" field.
func BaseURLGT(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldGT(FieldBaseURL, v))
}

// BaseURLGTE applies the GTE predicate on the "base_url" field.
func BaseURLGTE(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldGTE(FieldBaseURL, v))
}

// BaseURLLT applies the LT predicate on the "base_url" field.
func BaseURLLT(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldLT(FieldBaseURL, v))
}

// BaseURLLTE applies the LTE predicate on the "base_url" field.
func BaseURLLTE(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldLTE(FieldBaseURL, v))
}

// BaseURLContains applies the Contains predicate on the "base_url" field.
func BaseURLContains(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldContains(FieldBaseURL, v))
}

// BaseURLHasPrefix applies the HasPrefix predicate on the "base_url" field.
func BaseURLHasPrefix(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldHasPrefix(FieldBaseURL, v))
}

// BaseURLHasSuffix applies the HasSuffix predicate on the "base_url" field.
func BaseURLHasSuffix(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldHasSuffix(FieldBaseURL, v))
}

// BaseURLEqualFold applies the EqualFold predicate on the "base_url" field.
func BaseURLEqualFold(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldEqualFold(FieldBaseURL, v))
}

// BaseURLContainsFold applies the ContainsFold predicate on the "base_url" field.
func BaseURLContainsFold(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldContainsFold(FieldBaseURL, v))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v Platform) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v Platform) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...Platform) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...Platform) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldNotIn(FieldPlatform, vs...))
}

// AuthModeEQ applies the EQ predicate on the "auth_mode" field.
func AuthModeEQ(v AuthMode) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldEQ(FieldAuthMode, v))
}

// AuthModeNEQ applies the NEQ predicate on the "auth_mode" field.
func AuthModeNEQ(v AuthMode) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldNEQ(FieldAuthMode, v))
}

// AuthModeIn applies the In predicate on the "auth_mode" field.
func AuthModeIn(vs ...AuthMode) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldIn(FieldAuthMode, vs...))
}

// AuthModeNotIn applies the NotIn predicate on the "auth_mode" field.
func AuthModeNotIn(vs ...AuthMode) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldNotIn(FieldAuthMode, vs...))
}

// AccountEQ applies the EQ predicate on the "account" field.
func AccountEQ(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldEQ(FieldAccount, v))
}

// AccountNEQ applies the NEQ predicate on the "account" field.
func AccountNEQ(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldNEQ(FieldAccount, v))
}

// AccountIn applies the In predicate on the "account" field.
func AccountIn(vs ...string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldIn(FieldAccount, vs...))
}

// AccountNotIn applies the NotIn predicate on the "account" field.
func AccountNotIn(vs ...string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldNotIn(FieldAccount, vs...))
}

// AccountGT applies the GT predicate on the "account" field.
func AccountGT(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldGT(FieldAccount, v))
}

// AccountGTE applies the GTE predicate on the "account" field.
func AccountGTE(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldGTE(FieldAccount, v))
}

// AccountLT applies the LT predicate on the "account" field.
func AccountLT(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldLT(FieldAccount, v))
}

// AccountLTE applies the LTE predicate on the "account" field.
func AccountLTE(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldLTE(FieldAccount, v))
}

// AccountContains applies the Contains predicate on the "account" field.
func AccountContains(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldContains(FieldAccount, v))
}

// AccountHasPrefix applies the HasPrefix predicate on the "account" field.
func AccountHasPrefix(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldHasPrefix(FieldAccount, v))
}

// AccountHasSuffix applies the HasSuffix predicate on the "account" field.
func AccountHasSuffix(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldHasSuffix(FieldAccount, v))
}

// AccountEqualFold applies the EqualFold predicate on the "account" field.
func AccountEqualFold(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldEqualFold(FieldAccount, v))
}

// AccountContainsFold applies the ContainsFold predicate on the "account" field.
func AccountContainsFold(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldContainsFold(FieldAccount, v))
}

// CredentialEncryptedEQ applies the EQ predicate on the "credential_encrypted" field.
func CredentialEncryptedEQ(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldEQ(FieldCredentialEncrypted, v))
}

// CredentialEncryptedNEQ applies the NEQ predicate on the "credential_encrypted" field.
func CredentialEncryptedNEQ(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldNEQ(FieldCredentialEncrypted, v))
}

// CredentialEncryptedIn applies the In predicate on the "credential_encrypted" field.
func CredentialEncryptedIn(vs ...string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldIn(FieldCredentialEncrypted, vs...))
}

// CredentialEncryptedNotIn applies the NotIn predicate on the "credential_encrypted" field.
func CredentialEncryptedNotIn(vs ...string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldNotIn(FieldCredentialEncrypted, vs...))
}

// CredentialEncryptedGT applies the GT predicate on the "credential_encrypted" field.
func CredentialEncryptedGT(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldGT(FieldCredentialEncrypted, v))
}

// CredentialEncryptedGTE applies the GTE predicate on the "credential_encrypted" field.
func CredentialEncryptedGTE(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldGTE(FieldCredentialEncrypted, v))
}

// CredentialEncryptedLT applies the LT predicate on the "credential_encrypted" field.
func CredentialEncryptedLT(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldLT(FieldCredentialEncrypted, v))
}

// CredentialEncryptedLTE applies the LTE predicate on the "credential_encrypted" field.
func CredentialEncryptedLTE(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldLTE(FieldCredentialEncrypted, v))
}

// CredentialEncryptedContains applies the Contains predicate on the "credential_encrypted" field.
func CredentialEncryptedContains(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldContains(FieldCredentialEncrypted, v))
}

// CredentialEncryptedHasPrefix applies the HasPrefix predicate on the "credential_encrypted" field.
func CredentialEncryptedHasPrefix(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldHasPrefix(FieldCredentialEncrypted, v))
}

// CredentialEncryptedHasSuffix applies the HasSuffix predicate on the "credential_encrypted" field.
func CredentialEncryptedHasSuffix(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldHasSuffix(FieldCredentialEncrypted, v))
}

// CredentialEncryptedEqualFold applies the EqualFold predicate on the "credential_encrypted" field.
func CredentialEncryptedEqualFold(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldEqualFold(FieldCredentialEncrypted, v))
}

// CredentialEncryptedContainsFold applies the ContainsFold predicate on the "credential_encrypted" field.
func CredentialEncryptedContainsFold(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldContainsFold(FieldCredentialEncrypted, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldNEQ(FieldEnabled, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldNotIn(FieldStatus, vs...))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldContainsFold(FieldErrorMessage, v))
}

// BalanceUsdEQ applies the EQ predicate on the "balance_usd" field.
func BalanceUsdEQ(v float64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldEQ(FieldBalanceUsd, v))
}

// BalanceUsdNEQ applies the NEQ predicate on the "balance_usd" field.
func BalanceUsdNEQ(v float64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldNEQ(FieldBalanceUsd, v))
}

// BalanceUsdIn applies the In predicate on the "balance_usd" field.
func BalanceUsdIn(vs ...float64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldIn(FieldBalanceUsd, vs...))
}

// BalanceUsdNotIn applies the NotIn predicate on the "balance_usd" field.
func BalanceUsdNotIn(vs ...float64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldNotIn(FieldBalanceUsd, vs...))
}

// BalanceUsdGT applies the GT predicate on the "balance_usd" field.
func BalanceUsdGT(v float64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldGT(FieldBalanceUsd, v))
}

// BalanceUsdGTE applies the GTE predicate on the "balance_usd" field.
func BalanceUsdGTE(v float64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldGTE(FieldBalanceUsd, v))
}

// BalanceUsdLT applies the LT predicate on the "balance_usd" field.
func BalanceUsdLT(v float64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldLT(FieldBalanceUsd, v))
}

// BalanceUsdLTE applies the LTE predicate on the "balance_usd" field.
func BalanceUsdLTE(v float64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldLTE(FieldBalanceUsd, v))
}

// BalanceUsdIsNil applies the IsNil predicate on the "balance_usd" field.
func BalanceUsdIsNil() predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldIsNull(FieldBalanceUsd))
}

// BalanceUsdNotNil applies the NotNil predicate on the "balance_usd" field.
func BalanceUsdNotNil() predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldNotNull(FieldBalanceUsd))
}

// TodayTokensEQ applies the EQ predicate on the "today_tokens" field.
func TodayTokensEQ(v int64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldEQ(FieldTodayTokens, v))
}

// TodayTokensNEQ applies the NEQ predicate on the "today_tokens" field.
func TodayTokensNEQ(v int64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldNEQ(FieldTodayTokens, v))
}

// TodayTokensIn applies the In predicate on the "today_tokens" field.
func TodayTokensIn(vs ...int64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldIn(FieldTodayTokens, vs...))
}

// TodayTokensNotIn applies the NotIn predicate on the "today_tokens" field.
func TodayTokensNotIn(vs ...int64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldNotIn(FieldTodayTokens, vs...))
}

// TodayTokensGT applies the GT predicate on the "today_tokens" field.
func TodayTokensGT(v int64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldGT(FieldTodayTokens, v))
}

// TodayTokensGTE applies the GTE predicate on the "today_tokens" field.
func TodayTokensGTE(v int64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldGTE(FieldTodayTokens, v))
}

// TodayTokensLT applies the LT predicate on the "today_tokens" field.
func TodayTokensLT(v int64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldLT(FieldTodayTokens, v))
}

// TodayTokensLTE applies the LTE predicate on the "today_tokens" field.
func TodayTokensLTE(v int64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldLTE(FieldTodayTokens, v))
}

// TodayCostUsdEQ applies the EQ predicate on the "today_cost_usd" field.
func TodayCostUsdEQ(v float64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldEQ(FieldTodayCostUsd, v))
}

// TodayCostUsdNEQ applies the NEQ predicate on the "today_cost_usd" field.
func TodayCostUsdNEQ(v float64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldNEQ(FieldTodayCostUsd, v))
}

// TodayCostUsdIn applies the In predicate on the "today_cost_usd" field.
func TodayCostUsdIn(vs ...float64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldIn(FieldTodayCostUsd, vs...))
}

// TodayCostUsdNotIn applies the NotIn predicate on the "today_cost_usd" field.
func TodayCostUsdNotIn(vs ...float64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldNotIn(FieldTodayCostUsd, vs...))
}

// TodayCostUsdGT applies the GT predicate on the "today_cost_usd" field.
func TodayCostUsdGT(v float64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldGT(FieldTodayCostUsd, v))
}

// TodayCostUsdGTE applies the GTE predicate on the "today_cost_usd" field.
func TodayCostUsdGTE(v float64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldGTE(FieldTodayCostUsd, v))
}

// TodayCostUsdLT applies the LT predicate on the "today_cost_usd" field.
func TodayCostUsdLT(v float64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldLT(FieldTodayCostUsd, v))
}

// TodayCostUsdLTE applies the LTE predicate on the "today_cost_usd" field.
func TodayCostUsdLTE(v float64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldLTE(FieldTodayCostUsd, v))
}

// TotalTokensEQ applies the EQ predicate on the "total_tokens" field.
func TotalTokensEQ(v int64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldEQ(FieldTotalTokens, v))
}

// TotalTokensNEQ applies the NEQ predicate on the "total_tokens" field.
func TotalTokensNEQ(v int64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldNEQ(FieldTotalTokens, v))
}

// TotalTokensIn applies the In predicate on the "total_tokens" field.
func TotalTokensIn(vs ...int64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldIn(FieldTotalTokens, vs...))
}

// TotalTokensNotIn applies the NotIn predicate on the "total_tokens" field.
func TotalTokensNotIn(vs ...int64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldNotIn(FieldTotalTokens, vs...))
}

// TotalTokensGT applies the GT predicate on the "total_tokens" field.
func TotalTokensGT(v int64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldGT(FieldTotalTokens, v))
}

// TotalTokensGTE applies the GTE predicate on the "total_tokens" field.
func TotalTokensGTE(v int64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldGTE(FieldTotalTokens, v))
}

// TotalTokensLT applies the LT predicate on the "total_tokens" field.
func TotalTokensLT(v int64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldLT(FieldTotalTokens, v))
}

// TotalTokensLTE applies the LTE predicate on the "total_tokens" field.
func TotalTokensLTE(v int64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldLTE(FieldTotalTokens, v))
}

// TotalCostUsdEQ applies the EQ predicate on the "total_cost_usd" field.
func TotalCostUsdEQ(v float64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldEQ(FieldTotalCostUsd, v))
}

// TotalCostUsdNEQ applies the NEQ predicate on the "total_cost_usd" field.
func TotalCostUsdNEQ(v float64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldNEQ(FieldTotalCostUsd, v))
}

// TotalCostUsdIn applies the In predicate on the "total_cost_usd" field.
func TotalCostUsdIn(vs ...float64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldIn(FieldTotalCostUsd, vs...))
}

// TotalCostUsdNotIn applies the NotIn predicate on the "total_cost_usd" field.
func TotalCostUsdNotIn(vs ...float64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldNotIn(FieldTotalCostUsd, vs...))
}

// TotalCostUsdGT applies the GT predicate on the "total_cost_usd" field.
func TotalCostUsdGT(v float64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldGT(FieldTotalCostUsd, v))
}

// TotalCostUsdGTE applies the GTE predicate on the "total_cost_usd" field.
func TotalCostUsdGTE(v float64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldGTE(FieldTotalCostUsd, v))
}

// TotalCostUsdLT applies the LT predicate on the "total_cost_usd" field.
func TotalCostUsdLT(v float64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldLT(FieldTotalCostUsd, v))
}

// TotalCostUsdLTE applies the LTE predicate on the "total_cost_usd" field.
func TotalCostUsdLTE(v float64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldLTE(FieldTotalCostUsd, v))
}

// TrackingStartedAtEQ applies the EQ predicate on the "tracking_started_at" field.
func TrackingStartedAtEQ(v time.Time) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldEQ(FieldTrackingStartedAt, v))
}

// TrackingStartedAtNEQ applies the NEQ predicate on the "tracking_started_at" field.
func TrackingStartedAtNEQ(v time.Time) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldNEQ(FieldTrackingStartedAt, v))
}

// TrackingStartedAtIn applies the In predicate on the "tracking_started_at" field.
func TrackingStartedAtIn(vs ...time.Time) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldIn(FieldTrackingStartedAt, vs...))
}

// TrackingStartedAtNotIn applies the NotIn predicate on the "tracking_started_at" field.
func TrackingStartedAtNotIn(vs ...time.Time) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldNotIn(FieldTrackingStartedAt, vs...))
}

// TrackingStartedAtGT applies the GT predicate on the "tracking_started_at" field.
func TrackingStartedAtGT(v time.Time) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldGT(FieldTrackingStartedAt, v))
}

// TrackingStartedAtGTE applies the GTE predicate on the "tracking_started_at" field.
func TrackingStartedAtGTE(v time.Time) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldGTE(FieldTrackingStartedAt, v))
}

// TrackingStartedAtLT applies the LT predicate on the "tracking_started_at" field.
func TrackingStartedAtLT(v time.Time) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldLT(FieldTrackingStartedAt, v))
}

// TrackingStartedAtLTE applies the LTE predicate on the "tracking_started_at" field.
func TrackingStartedAtLTE(v time.Time) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldLTE(FieldTrackingStartedAt, v))
}

// LastSyncedAtEQ applies the EQ predicate on the "last_synced_at" field.
func LastSyncedAtEQ(v time.Time) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldEQ(FieldLastSyncedAt, v))
}

// LastSyncedAtNEQ applies the NEQ predicate on the "last_synced_at" field.
func LastSyncedAtNEQ(v time.Time) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldNEQ(FieldLastSyncedAt, v))
}

// LastSyncedAtIn applies the In predicate on the "last_synced_at" field.
func LastSyncedAtIn(vs ...time.Time) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldIn(FieldLastSyncedAt, vs...))
}

// LastSyncedAtNotIn applies the NotIn predicate on the "last_synced_at" field.
func LastSyncedAtNotIn(vs ...time.Time) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldNotIn(FieldLastSyncedAt, vs...))
}

// LastSyncedAtGT applies the GT predicate on the "last_synced_at" field.
func LastSyncedAtGT(v time.Time) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldGT(FieldLastSyncedAt, v))
}

// LastSyncedAtGTE applies the GTE predicate on the "last_synced_at" field.
func LastSyncedAtGTE(v time.Time) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldGTE(FieldLastSyncedAt, v))
}

// LastSyncedAtLT applies the LT predicate on the "last_synced_at" field.
func LastSyncedAtLT(v time.Time) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldLT(FieldLastSyncedAt, v))
}

// LastSyncedAtLTE applies the LTE predicate on the "last_synced_at" field.
func LastSyncedAtLTE(v time.Time) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldLTE(FieldLastSyncedAt, v))
}

// LastSyncedAtIsNil applies the IsNil predicate on the "last_synced_at" field.
func LastSyncedAtIsNil() predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldIsNull(FieldLastSyncedAt))
}

// LastSyncedAtNotNil applies the NotNil predicate on the "last_synced_at" field.
func LastSyncedAtNotNil() predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldNotNull(FieldLastSyncedAt))
}

// NextSyncAtEQ applies the EQ predicate on the "next_sync_at" field.
func NextSyncAtEQ(v time.Time) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldEQ(FieldNextSyncAt, v))
}

// NextSyncAtNEQ applies the NEQ predicate on the "next_sync_at" field.
func NextSyncAtNEQ(v time.Time) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldNEQ(FieldNextSyncAt, v))
}

// NextSyncAtIn applies the In predicate on the "next_sync_at" field.
func NextSyncAtIn(vs ...time.Time) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldIn(FieldNextSyncAt, vs...))
}

// NextSyncAtNotIn applies the NotIn predicate on the "next_sync_at" field.
func NextSyncAtNotIn(vs ...time.Time) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldNotIn(FieldNextSyncAt, vs...))
}

// NextSyncAtGT applies the GT predicate on the "next_sync_at" field.
func NextSyncAtGT(v time.Time) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldGT(FieldNextSyncAt, v))
}

// NextSyncAtGTE applies the GTE predicate on the "next_sync_at" field.
func NextSyncAtGTE(v time.Time) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldGTE(FieldNextSyncAt, v))
}

// NextSyncAtLT applies the LT predicate on the "next_sync_at" field.
func NextSyncAtLT(v time.Time) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldLT(FieldNextSyncAt, v))
}

// NextSyncAtLTE applies the LTE predicate on the "next_sync_at" field.
func NextSyncAtLTE(v time.Time) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldLTE(FieldNextSyncAt, v))
}

// NextSyncAtIsNil applies the IsNil predicate on the "next_sync_at" field.
func NextSyncAtIsNil() predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldIsNull(FieldNextSyncAt))
}

// NextSyncAtNotNil applies the NotNil predicate on the "next_sync_at" field.
func NextSyncAtNotNil() predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldNotNull(FieldNextSyncAt))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v int64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v int64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...int64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...int64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v int64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v int64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v int64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v int64) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.FieldLTE(FieldCreatedBy, v))
}

// HasGroups applies the HasEdge predicate on the "groups" edge.
func HasGroups() predicate.UpstreamSite {
	return predicate.UpstreamSite(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, GroupsTable, GroupsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupsWith applies the HasEdge predicate on the "groups" edge with a given conditions (other predicates).
func HasGroupsWith(preds ...predicate.UpstreamGroup) predicate.UpstreamSite {
	return predicate.UpstreamSite(func(s *sql.Selector) {
		step := newGroupsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDailyStats applies the HasEdge predicate on the "daily_stats" edge.
func HasDailyStats() predicate.UpstreamSite {
	return predicate.UpstreamSite(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DailyStatsTable, DailyStatsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDailyStatsWith applies the HasEdge predicate on the "daily_stats" edge with a given conditions (other predicates).
func HasDailyStatsWith(preds ...predicate.UpstreamDailyStat) predicate.UpstreamSite {
	return predicate.UpstreamSite(func(s *sql.Selector) {
		step := newDailyStatsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UpstreamSite) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UpstreamSite) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UpstreamSite) predicate.UpstreamSite {
	return predicate.UpstreamSite(sql.NotPredicates(p))
}
