// Code generated by ent, DO NOT EDIT.

package upstreamgroupmultiplierhistory

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldLTE(FieldID, id))
}

// SiteID applies equality check predicate on the "site_id" field. It's identical to SiteIDEQ.
func SiteID(v int64) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldEQ(FieldSiteID, v))
}

// RemoteID applies equality check predicate on the "remote_id" field. It's identical to RemoteIDEQ.
func RemoteID(v string) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldEQ(FieldRemoteID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldEQ(FieldName, v))
}

// Platform applies equality check predicate on the "platform" field. It's identical to PlatformEQ.
func Platform(v string) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldEQ(FieldPlatform, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldEQ(FieldDescription, v))
}

// Multiplier applies equality check predicate on the "multiplier" field. It's identical to MultiplierEQ.
func Multiplier(v float64) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldEQ(FieldMultiplier, v))
}

// RecordedAt applies equality check predicate on the "recorded_at" field. It's identical to RecordedAtEQ.
func RecordedAt(v time.Time) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldEQ(FieldRecordedAt, v))
}

// SiteIDEQ applies the EQ predicate on the "site_id" field.
func SiteIDEQ(v int64) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldEQ(FieldSiteID, v))
}

// SiteIDNEQ applies the NEQ predicate on the "site_id" field.
func SiteIDNEQ(v int64) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldNEQ(FieldSiteID, v))
}

// SiteIDIn applies the In predicate on the "site_id" field.
func SiteIDIn(vs ...int64) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldIn(FieldSiteID, vs...))
}

// SiteIDNotIn applies the NotIn predicate on the "site_id" field.
func SiteIDNotIn(vs ...int64) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldNotIn(FieldSiteID, vs...))
}

// RemoteIDEQ applies the EQ predicate on the "remote_id" field.
func RemoteIDEQ(v string) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldEQ(FieldRemoteID, v))
}

// RemoteIDNEQ applies the NEQ predicate on the "remote_id" field.
func RemoteIDNEQ(v string) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldNEQ(FieldRemoteID, v))
}

// RemoteIDIn applies the In predicate on the "remote_id" field.
func RemoteIDIn(vs ...string) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldIn(FieldRemoteID, vs...))
}

// RemoteIDNotIn applies the NotIn predicate on the "remote_id" field.
func RemoteIDNotIn(vs ...string) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldNotIn(FieldRemoteID, vs...))
}

// RemoteIDGT applies the GT predicate on the "remote_id" field.
func RemoteIDGT(v string) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldGT(FieldRemoteID, v))
}

// RemoteIDGTE applies the GTE predicate on the "remote_id" field.
func RemoteIDGTE(v string) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldGTE(FieldRemoteID, v))
}

// RemoteIDLT applies the LT predicate on the "remote_id" field.
func RemoteIDLT(v string) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldLT(FieldRemoteID, v))
}

// RemoteIDLTE applies the LTE predicate on the "remote_id" field.
func RemoteIDLTE(v string) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldLTE(FieldRemoteID, v))
}

// RemoteIDContains applies the Contains predicate on the "remote_id" field.
func RemoteIDContains(v string) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldContains(FieldRemoteID, v))
}

// RemoteIDHasPrefix applies the HasPrefix predicate on the "remote_id" field.
func RemoteIDHasPrefix(v string) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldHasPrefix(FieldRemoteID, v))
}

// RemoteIDHasSuffix applies the HasSuffix predicate on the "remote_id" field.
func RemoteIDHasSuffix(v string) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldHasSuffix(FieldRemoteID, v))
}

// RemoteIDEqualFold applies the EqualFold predicate on the "remote_id" field.
func RemoteIDEqualFold(v string) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldEqualFold(FieldRemoteID, v))
}

// RemoteIDContainsFold applies the ContainsFold predicate on the "remote_id" field.
func RemoteIDContainsFold(v string) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldContainsFold(FieldRemoteID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldContainsFold(FieldName, v))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v string) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v string) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...string) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...string) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldNotIn(FieldPlatform, vs...))
}

// PlatformGT applies the GT predicate on the "platform" field.
func PlatformGT(v string) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldGT(FieldPlatform, v))
}

// PlatformGTE applies the GTE predicate on the "platform" field.
func PlatformGTE(v string) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldGTE(FieldPlatform, v))
}

// PlatformLT applies the LT predicate on the "platform" field.
func PlatformLT(v string) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldLT(FieldPlatform, v))
}

// PlatformLTE applies the LTE predicate on the "platform" field.
func PlatformLTE(v string) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldLTE(FieldPlatform, v))
}

// PlatformContains applies the Contains predicate on the "platform" field.
func PlatformContains(v string) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldContains(FieldPlatform, v))
}

// PlatformHasPrefix applies the HasPrefix predicate on the "platform" field.
func PlatformHasPrefix(v string) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldHasPrefix(FieldPlatform, v))
}

// PlatformHasSuffix applies the HasSuffix predicate on the "platform" field.
func PlatformHasSuffix(v string) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldHasSuffix(FieldPlatform, v))
}

// PlatformEqualFold applies the EqualFold predicate on the "platform" field.
func PlatformEqualFold(v string) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldEqualFold(FieldPlatform, v))
}

// PlatformContainsFold applies the ContainsFold predicate on the "platform" field.
func PlatformContainsFold(v string) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldContainsFold(FieldPlatform, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldContainsFold(FieldDescription, v))
}

// MultiplierEQ applies the EQ predicate on the "multiplier" field.
func MultiplierEQ(v float64) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldEQ(FieldMultiplier, v))
}

// MultiplierNEQ applies the NEQ predicate on the "multiplier" field.
func MultiplierNEQ(v float64) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldNEQ(FieldMultiplier, v))
}

// MultiplierIn applies the In predicate on the "multiplier" field.
func MultiplierIn(vs ...float64) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldIn(FieldMultiplier, vs...))
}

// MultiplierNotIn applies the NotIn predicate on the "multiplier" field.
func MultiplierNotIn(vs ...float64) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldNotIn(FieldMultiplier, vs...))
}

// MultiplierGT applies the GT predicate on the "multiplier" field.
func MultiplierGT(v float64) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldGT(FieldMultiplier, v))
}

// MultiplierGTE applies the GTE predicate on the "multiplier" field.
func MultiplierGTE(v float64) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldGTE(FieldMultiplier, v))
}

// MultiplierLT applies the LT predicate on the "multiplier" field.
func MultiplierLT(v float64) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldLT(FieldMultiplier, v))
}

// MultiplierLTE applies the LTE predicate on the "multiplier" field.
func MultiplierLTE(v float64) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldLTE(FieldMultiplier, v))
}

// MultiplierIsNil applies the IsNil predicate on the "multiplier" field.
func MultiplierIsNil() predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldIsNull(FieldMultiplier))
}

// MultiplierNotNil applies the NotNil predicate on the "multiplier" field.
func MultiplierNotNil() predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldNotNull(FieldMultiplier))
}

// RecordedAtEQ applies the EQ predicate on the "recorded_at" field.
func RecordedAtEQ(v time.Time) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldEQ(FieldRecordedAt, v))
}

// RecordedAtNEQ applies the NEQ predicate on the "recorded_at" field.
func RecordedAtNEQ(v time.Time) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldNEQ(FieldRecordedAt, v))
}

// RecordedAtIn applies the In predicate on the "recorded_at" field.
func RecordedAtIn(vs ...time.Time) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldIn(FieldRecordedAt, vs...))
}

// RecordedAtNotIn applies the NotIn predicate on the "recorded_at" field.
func RecordedAtNotIn(vs ...time.Time) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldNotIn(FieldRecordedAt, vs...))
}

// RecordedAtGT applies the GT predicate on the "recorded_at" field.
func RecordedAtGT(v time.Time) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldGT(FieldRecordedAt, v))
}

// RecordedAtGTE applies the GTE predicate on the "recorded_at" field.
func RecordedAtGTE(v time.Time) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldGTE(FieldRecordedAt, v))
}

// RecordedAtLT applies the LT predicate on the "recorded_at" field.
func RecordedAtLT(v time.Time) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldLT(FieldRecordedAt, v))
}

// RecordedAtLTE applies the LTE predicate on the "recorded_at" field.
func RecordedAtLTE(v time.Time) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.FieldLTE(FieldRecordedAt, v))
}

// HasSite applies the HasEdge predicate on the "site" edge.
func HasSite() predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SiteTable, SiteColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSiteWith applies the HasEdge predicate on the "site" edge with a given conditions (other predicates).
func HasSiteWith(preds ...predicate.UpstreamSite) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(func(s *sql.Selector) {
		step := newSiteStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UpstreamGroupMultiplierHistory) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UpstreamGroupMultiplierHistory) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UpstreamGroupMultiplierHistory) predicate.UpstreamGroupMultiplierHistory {
	return predicate.UpstreamGroupMultiplierHistory(sql.NotPredicates(p))
}
