// Code generated by ent, DO NOT EDIT.

package upstreamgroup

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the upstreamgroup type in the database.
	Label = "upstream_group"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldSiteID holds the string denoting the site_id field in the database.
	FieldSiteID = "site_id"
	// FieldRemoteID holds the string denoting the remote_id field in the database.
	FieldRemoteID = "remote_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldPlatform holds the string denoting the platform field in the database.
	FieldPlatform = "platform"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldMultiplier holds the string denoting the multiplier field in the database.
	FieldMultiplier = "multiplier"
	// FieldTodayTokens holds the string denoting the today_tokens field in the database.
	FieldTodayTokens = "today_tokens"
	// FieldTodayCostUsd holds the string denoting the today_cost_usd field in the database.
	FieldTodayCostUsd = "today_cost_usd"
	// FieldDisplayed holds the string denoting the displayed field in the database.
	FieldDisplayed = "displayed"
	// FieldAvailable holds the string denoting the available field in the database.
	FieldAvailable = "available"
	// FieldLastSyncedAt holds the string denoting the last_synced_at field in the database.
	FieldLastSyncedAt = "last_synced_at"
	// EdgeSite holds the string denoting the site edge name in mutations.
	EdgeSite = "site"
	// Table holds the table name of the upstreamgroup in the database.
	Table = "upstream_groups"
	// SiteTable is the table that holds the site relation/edge.
	SiteTable = "upstream_groups"
	// SiteInverseTable is the table name for the UpstreamSite entity.
	// It exists in this package in order to avoid circular dependency with the "upstreamsite" package.
	SiteInverseTable = "upstream_sites"
	// SiteColumn is the table column denoting the site relation/edge.
	SiteColumn = "site_id"
)

// Columns holds all SQL columns for upstreamgroup fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldSiteID,
	FieldRemoteID,
	FieldName,
	FieldPlatform,
	FieldDescription,
	FieldMultiplier,
	FieldTodayTokens,
	FieldTodayCostUsd,
	FieldDisplayed,
	FieldAvailable,
	FieldLastSyncedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// RemoteIDValidator is a validator for the "remote_id" field. It is called by the builders before save.
	RemoteIDValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultPlatform holds the default value on creation for the "platform" field.
	DefaultPlatform string
	// PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	PlatformValidator func(string) error
	// DefaultDescription holds the default value on creation for the "description" field.
	DefaultDescription string
	// DefaultTodayTokens holds the default value on creation for the "today_tokens" field.
	DefaultTodayTokens int64
	// DefaultTodayCostUsd holds the default value on creation for the "today_cost_usd" field.
	DefaultTodayCostUsd float64
	// DefaultDisplayed holds the default value on creation for the "displayed" field.
	DefaultDisplayed bool
	// DefaultAvailable holds the default value on creation for the "available" field.
	DefaultAvailable bool
	// DefaultLastSyncedAt holds the default value on creation for the "last_synced_at" field.
	DefaultLastSyncedAt func() time.Time
)

// OrderOption defines the ordering options for the UpstreamGroup queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// BySiteID orders the results by the site_id field.
func BySiteID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSiteID, opts...).ToFunc()
}

// ByRemoteID orders the results by the remote_id field.
func ByRemoteID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemoteID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByPlatform orders the results by the platform field.
func ByPlatform(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatform, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByMultiplier orders the results by the multiplier field.
func ByMultiplier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMultiplier, opts...).ToFunc()
}

// ByTodayTokens orders the results by the today_tokens field.
func ByTodayTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTodayTokens, opts...).ToFunc()
}

// ByTodayCostUsd orders the results by the today_cost_usd field.
func ByTodayCostUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTodayCostUsd, opts...).ToFunc()
}

// ByDisplayed orders the results by the displayed field.
func ByDisplayed(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisplayed, opts...).ToFunc()
}

// ByAvailable orders the results by the available field.
func ByAvailable(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAvailable, opts...).ToFunc()
}

// ByLastSyncedAt orders the results by the last_synced_at field.
func ByLastSyncedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSyncedAt, opts...).ToFunc()
}

// BySiteField orders the results by site field.
func BySiteField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSiteStep(), sql.OrderByField(field, opts...))
	}
}
func newSiteStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SiteInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SiteTable, SiteColumn),
	)
}
