// Code generated by ent, DO NOT EDIT.

package upstreamgroup

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldUpdatedAt, v))
}

// SiteID applies equality check predicate on the "site_id" field. It's identical to SiteIDEQ.
func SiteID(v int64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldSiteID, v))
}

// RemoteID applies equality check predicate on the "remote_id" field. It's identical to RemoteIDEQ.
func RemoteID(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldRemoteID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldName, v))
}

// Platform applies equality check predicate on the "platform" field. It's identical to PlatformEQ.
func Platform(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldPlatform, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldDescription, v))
}

// Multiplier applies equality check predicate on the "multiplier" field. It's identical to MultiplierEQ.
func Multiplier(v float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldMultiplier, v))
}

// TodayTokens applies equality check predicate on the "today_tokens" field. It's identical to TodayTokensEQ.
func TodayTokens(v int64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldTodayTokens, v))
}

// TodayCostUsd applies equality check predicate on the "today_cost_usd" field. It's identical to TodayCostUsdEQ.
func TodayCostUsd(v float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldTodayCostUsd, v))
}

// Displayed applies equality check predicate on the "displayed" field. It's identical to DisplayedEQ.
func Displayed(v bool) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldDisplayed, v))
}

// Available applies equality check predicate on the "available" field. It's identical to AvailableEQ.
func Available(v bool) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldAvailable, v))
}

// LastSyncedAt applies equality check predicate on the "last_synced_at" field. It's identical to LastSyncedAtEQ.
func LastSyncedAt(v time.Time) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldLastSyncedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldLTE(FieldUpdatedAt, v))
}

// SiteIDEQ applies the EQ predicate on the "site_id" field.
func SiteIDEQ(v int64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldSiteID, v))
}

// SiteIDNEQ applies the NEQ predicate on the "site_id" field.
func SiteIDNEQ(v int64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNEQ(FieldSiteID, v))
}

// SiteIDIn applies the In predicate on the "site_id" field.
func SiteIDIn(vs ...int64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldIn(FieldSiteID, vs...))
}

// SiteIDNotIn applies the NotIn predicate on the "site_id" field.
func SiteIDNotIn(vs ...int64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNotIn(FieldSiteID, vs...))
}

// RemoteIDEQ applies the EQ predicate on the "remote_id" field.
func RemoteIDEQ(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldRemoteID, v))
}

// RemoteIDNEQ applies the NEQ predicate on the "remote_id" field.
func RemoteIDNEQ(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNEQ(FieldRemoteID, v))
}

// RemoteIDIn applies the In predicate on the "remote_id" field.
func RemoteIDIn(vs ...string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldIn(FieldRemoteID, vs...))
}

// RemoteIDNotIn applies the NotIn predicate on the "remote_id" field.
func RemoteIDNotIn(vs ...string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNotIn(FieldRemoteID, vs...))
}

// RemoteIDGT applies the GT predicate on the "remote_id" field.
func RemoteIDGT(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldGT(FieldRemoteID, v))
}

// RemoteIDGTE applies the GTE predicate on the "remote_id" field.
func RemoteIDGTE(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldGTE(FieldRemoteID, v))
}

// RemoteIDLT applies the LT predicate on the "remote_id" field.
func RemoteIDLT(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldLT(FieldRemoteID, v))
}

// RemoteIDLTE applies the LTE predicate on the "remote_id" field.
func RemoteIDLTE(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldLTE(FieldRemoteID, v))
}

// RemoteIDContains applies the Contains predicate on the "remote_id" field.
func RemoteIDContains(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldContains(FieldRemoteID, v))
}

// RemoteIDHasPrefix applies the HasPrefix predicate on the "remote_id" field.
func RemoteIDHasPrefix(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldHasPrefix(FieldRemoteID, v))
}

// RemoteIDHasSuffix applies the HasSuffix predicate on the "remote_id" field.
func RemoteIDHasSuffix(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldHasSuffix(FieldRemoteID, v))
}

// RemoteIDEqualFold applies the EqualFold predicate on the "remote_id" field.
func RemoteIDEqualFold(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEqualFold(FieldRemoteID, v))
}

// RemoteIDContainsFold applies the ContainsFold predicate on the "remote_id" field.
func RemoteIDContainsFold(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldContainsFold(FieldRemoteID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldContainsFold(FieldName, v))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNotIn(FieldPlatform, vs...))
}

// PlatformGT applies the GT predicate on the "platform" field.
func PlatformGT(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldGT(FieldPlatform, v))
}

// PlatformGTE applies the GTE predicate on the "platform" field.
func PlatformGTE(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldGTE(FieldPlatform, v))
}

// PlatformLT applies the LT predicate on the "platform" field.
func PlatformLT(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldLT(FieldPlatform, v))
}

// PlatformLTE applies the LTE predicate on the "platform" field.
func PlatformLTE(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldLTE(FieldPlatform, v))
}

// PlatformContains applies the Contains predicate on the "platform" field.
func PlatformContains(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldContains(FieldPlatform, v))
}

// PlatformHasPrefix applies the HasPrefix predicate on the "platform" field.
func PlatformHasPrefix(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldHasPrefix(FieldPlatform, v))
}

// PlatformHasSuffix applies the HasSuffix predicate on the "platform" field.
func PlatformHasSuffix(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldHasSuffix(FieldPlatform, v))
}

// PlatformEqualFold applies the EqualFold predicate on the "platform" field.
func PlatformEqualFold(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEqualFold(FieldPlatform, v))
}

// PlatformContainsFold applies the ContainsFold predicate on the "platform" field.
func PlatformContainsFold(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldContainsFold(FieldPlatform, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldContainsFold(FieldDescription, v))
}

// MultiplierEQ applies the EQ predicate on the "multiplier" field.
func MultiplierEQ(v float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldMultiplier, v))
}

// MultiplierNEQ applies the NEQ predicate on the "multiplier" field.
func MultiplierNEQ(v float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNEQ(FieldMultiplier, v))
}

// MultiplierIn applies the In predicate on the "multiplier" field.
func MultiplierIn(vs ...float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldIn(FieldMultiplier, vs...))
}

// MultiplierNotIn applies the NotIn predicate on the "multiplier" field.
func MultiplierNotIn(vs ...float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNotIn(FieldMultiplier, vs...))
}

// MultiplierGT applies the GT predicate on the "multiplier" field.
func MultiplierGT(v float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldGT(FieldMultiplier, v))
}

// MultiplierGTE applies the GTE predicate on the "multiplier" field.
func MultiplierGTE(v float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldGTE(FieldMultiplier, v))
}

// MultiplierLT applies the LT predicate on the "multiplier" field.
func MultiplierLT(v float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldLT(FieldMultiplier, v))
}

// MultiplierLTE applies the LTE predicate on the "multiplier" field.
func MultiplierLTE(v float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldLTE(FieldMultiplier, v))
}

// MultiplierIsNil applies the IsNil predicate on the "multiplier" field.
func MultiplierIsNil() predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldIsNull(FieldMultiplier))
}

// MultiplierNotNil applies the NotNil predicate on the "multiplier" field.
func MultiplierNotNil() predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNotNull(FieldMultiplier))
}

// TodayTokensEQ applies the EQ predicate on the "today_tokens" field.
func TodayTokensEQ(v int64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldTodayTokens, v))
}

// TodayTokensNEQ applies the NEQ predicate on the "today_tokens" field.
func TodayTokensNEQ(v int64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNEQ(FieldTodayTokens, v))
}

// TodayTokensIn applies the In predicate on the "today_tokens" field.
func TodayTokensIn(vs ...int64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldIn(FieldTodayTokens, vs...))
}

// TodayTokensNotIn applies the NotIn predicate on the "today_tokens" field.
func TodayTokensNotIn(vs ...int64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNotIn(FieldTodayTokens, vs...))
}

// TodayTokensGT applies the GT predicate on the "today_tokens" field.
func TodayTokensGT(v int64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldGT(FieldTodayTokens, v))
}

// TodayTokensGTE applies the GTE predicate on the "today_tokens" field.
func TodayTokensGTE(v int64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldGTE(FieldTodayTokens, v))
}

// TodayTokensLT applies the LT predicate on the "today_tokens" field.
func TodayTokensLT(v int64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldLT(FieldTodayTokens, v))
}

// TodayTokensLTE applies the LTE predicate on the "today_tokens" field.
func TodayTokensLTE(v int64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldLTE(FieldTodayTokens, v))
}

// TodayCostUsdEQ applies the EQ predicate on the "today_cost_usd" field.
func TodayCostUsdEQ(v float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldTodayCostUsd, v))
}

// TodayCostUsdNEQ applies the NEQ predicate on the "today_cost_usd" field.
func TodayCostUsdNEQ(v float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNEQ(FieldTodayCostUsd, v))
}

// TodayCostUsdIn applies the In predicate on the "today_cost_usd" field.
func TodayCostUsdIn(vs ...float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldIn(FieldTodayCostUsd, vs...))
}

// TodayCostUsdNotIn applies the NotIn predicate on the "today_cost_usd" field.
func TodayCostUsdNotIn(vs ...float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNotIn(FieldTodayCostUsd, vs...))
}

// TodayCostUsdGT applies the GT predicate on the "today_cost_usd" field.
func TodayCostUsdGT(v float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldGT(FieldTodayCostUsd, v))
}

// TodayCostUsdGTE applies the GTE predicate on the "today_cost_usd" field.
func TodayCostUsdGTE(v float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldGTE(FieldTodayCostUsd, v))
}

// TodayCostUsdLT applies the LT predicate on the "today_cost_usd" field.
func TodayCostUsdLT(v float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldLT(FieldTodayCostUsd, v))
}

// TodayCostUsdLTE applies the LTE predicate on the "today_cost_usd" field.
func TodayCostUsdLTE(v float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldLTE(FieldTodayCostUsd, v))
}

// DisplayedEQ applies the EQ predicate on the "displayed" field.
func DisplayedEQ(v bool) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldDisplayed, v))
}

// DisplayedNEQ applies the NEQ predicate on the "displayed" field.
func DisplayedNEQ(v bool) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNEQ(FieldDisplayed, v))
}

// AvailableEQ applies the EQ predicate on the "available" field.
func AvailableEQ(v bool) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldAvailable, v))
}

// AvailableNEQ applies the NEQ predicate on the "available" field.
func AvailableNEQ(v bool) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNEQ(FieldAvailable, v))
}

// LastSyncedAtEQ applies the EQ predicate on the "last_synced_at" field.
func LastSyncedAtEQ(v time.Time) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldLastSyncedAt, v))
}

// LastSyncedAtNEQ applies the NEQ predicate on the "last_synced_at" field.
func LastSyncedAtNEQ(v time.Time) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNEQ(FieldLastSyncedAt, v))
}

// LastSyncedAtIn applies the In predicate on the "last_synced_at" field.
func LastSyncedAtIn(vs ...time.Time) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldIn(FieldLastSyncedAt, vs...))
}

// LastSyncedAtNotIn applies the NotIn predicate on the "last_synced_at" field.
func LastSyncedAtNotIn(vs ...time.Time) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNotIn(FieldLastSyncedAt, vs...))
}

// LastSyncedAtGT applies the GT predicate on the "last_synced_at" field.
func LastSyncedAtGT(v time.Time) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldGT(FieldLastSyncedAt, v))
}

// LastSyncedAtGTE applies the GTE predicate on the "last_synced_at" field.
func LastSyncedAtGTE(v time.Time) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldGTE(FieldLastSyncedAt, v))
}

// LastSyncedAtLT applies the LT predicate on the "last_synced_at" field.
func LastSyncedAtLT(v time.Time) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldLT(FieldLastSyncedAt, v))
}

// LastSyncedAtLTE applies the LTE predicate on the "last_synced_at" field.
func LastSyncedAtLTE(v time.Time) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldLTE(FieldLastSyncedAt, v))
}

// HasSite applies the HasEdge predicate on the "site" edge.
func HasSite() predicate.UpstreamGroup {
	return predicate.UpstreamGroup(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SiteTable, SiteColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSiteWith applies the HasEdge predicate on the "site" edge with a given conditions (other predicates).
func HasSiteWith(preds ...predicate.UpstreamSite) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(func(s *sql.Selector) {
		step := newSiteStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAccountBindings applies the HasEdge predicate on the "account_bindings" edge.
func HasAccountBindings() predicate.UpstreamGroup {
	return predicate.UpstreamGroup(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AccountBindingsTable, AccountBindingsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountBindingsWith applies the HasEdge predicate on the "account_bindings" edge with a given conditions (other predicates).
func HasAccountBindingsWith(preds ...predicate.UpstreamGroupAccountBinding) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(func(s *sql.Selector) {
		step := newAccountBindingsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UpstreamGroup) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UpstreamGroup) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UpstreamGroup) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.NotPredicates(p))
}
